### DISCUSSION TITLE
Remote schema relationships not generating types through code-gen

### DISCUSSION THREAD

**Discussion by eduardo-barley** [hasura/graphql-engine#10159] [Question]
Description
When using remote schema relationships in Hasura, the generated types through code generation are not reflecting these relationships. This leads to inconsistencies and difficulties in managing the schema.
Below is the code-gen schema

```yaml
overwrite: true
schema:
  - ${hasura)}:
      headers:
        'x-hasura-admin-secret': ${VITE_HASURA_X_API_KEY}
documents: ./src/**/*.graphql
generates:
  ./src/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-query
    config:
      fetcher: 'src/utils/fetcher'
      skipTypename: true
      namingConvention:
        enumValues: 'keep'
  ./graphql.schema.json:
    plugins:
      - introspection

```

Does create remote schema types. 

Does not keep db types when going from remote schema to db (hasura).
Tracks "string" any other type is `any`

```
{
id: "string"
db_table : {
value: any
}

}

```
