### DISCUSSION TITLE
How to set the timeout for DC Agents

### DISCUSSION THREAD

**Discussion by DmitriyBrashevets** [hasura/graphql-engine#10181] [Question]
Hello. 

I've originally asked the question here https://github.com/hasura/graphql-engine/commit/607497f#commitcomment-140299258. 

Duplicating it below.

Could you please tell how to set the timeout for DC Agents? 

In particular I'm interested in setting of the timeout for clickhouse-data connector https://github.com/hasura/clickhouse_gdc_v2

I'm facing with this error when I'm trying to replace metadata object which has more than ~2750 tables per connection :
```json
{
    "error": "cannot continue due to inconsistent metadata",
    "path": "$.args",
    "code": "unexpected",
    "internal": [
        {
            "definition": "${clickhouseDatabaseName}",
            "name": "source ${clickhouseDatabaseName}",
            "reason": "Inconsistent object: Error communicating with data connector agent: No response data received",
            "type": "source"
        }
    ]
}
```

Here is how the `HASURA_GRAPHQL_METADATA_DEFAULTS` looks like:
```yaml
- name: HASURA_GRAPHQL_METADATA_DEFAULTS
          value: >-
            {"backend_configs":{"dataconnector":{"clickhouse":{"uri":"http://hasura-clickhouse-data-connector:8080"}}}}
```

I'm using these images:
```yaml
image:
    repository: hasura/graphql-engine
    tag: v2.37.0
    
image:
    repository: hasura/clickhouse-data-connector
    tag: v2.36.0
```
