### DISCUSSION TITLE
How to update connection parameters after metatdata init

### DISCUSSION THREAD

**Discussion by ksi9302** [hasura/graphql-engine#10211] [Question]
Hi, I'm using CE of hasura and recently found that the server is not able to handle the default number of connections resulting in exhausting the CPU.
So, I tried setting the below params in docker-compose.yml and restarting the instances

HASURA_GRAPHQL_EVENTS_HTTP_POOL_SIZE
HASURA_GRAPHQL_PG_CONNECTIONS

But it didn't seem to work and I found the below page in your docs.

[Doc](https://hasura.io/docs/latest/resources/upgrade-hasura-v2/#hasura-v2-env-changes)

So I believe the changes I've made in the docker compose file won't take effect after the first initialization.
If this is the case, how am I to update the params?
Or if I'm knocking on the wrong doors, would be nice to know where I should look for.

Thanks in advance.

my current docker-compose file

```
version: "3.6"
name: ...
services:
  postgres:
    image: postgres:15
    command: postgres -c jit=off
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ...
  graphql-engine:
    image: hasura/graphql-engine:v2.35.0
    ports:
      - "8080:8080"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: ...
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: ...
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_METADATA_DEFAULTS: '{"backend_configs":{"dataconnector":{"athena":{"uri":"http://data-connector-agent:8081/api/v1/athena"},"mariadb":{"uri":"http://data-connector-agent:8081/api/v1/mariadb"},"mysql8":{"uri":"http://data-connector-agent:8081/api/v1/mysql"},"oracle":{"uri":"http://data-connector-agent:8081/api/v1/oracle"},"snowflake":{"uri":"http://data-connector-agent:8081/api/v1/snowflake"}}}}'
      HASURA_GRAPHQL_ADMIN_SECRET: ...
      HASURA_GRAPHQL_JWT_SECRET: ...
      HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_REFETCH_INTERVAL: 3000
      HASURA_GRAPHQL_PG_CONNECTIONS: 4
      HASURA_GRAPHQL_EVENTS_HTTP_POOL_SIZE: 10
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      API_ENDPOINT: ...

    depends_on:
      data-connector-agent:
        condition: service_healthy
  data-connector-agent:
    image: hasura/graphql-data-connector:v2.35.0
    restart: always
    ports:
      - 8081:8081
    environment:
      QUARKUS_LOG_LEVEL: ERROR # FATAL, ERROR, WARN, INFO, DEBUG, TRACE
      ## https://quarkus.io/guides/opentelemetry#configuration-reference
      QUARKUS_OPENTELEMETRY_ENABLED: "false"
      ## QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/athena/health"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
volumes:
  db_data:

```
