### DISCUSSION TITLE
fieldPresets doesn't work properly

### DISCUSSION THREAD

**Discussion by socheatleang** [hasura/graphql-engine#10653] [Question]
I am working with insert mutation which require the fieldPresets. 
* I have ProfileLinks which have (id, link_id, profile_id, created_at, etc...)
* profile_id has exist inside the jwt-token sessionVariable: x-hasura-profile-id

So far, I would love to have fieldPresets with profile_id from the session variable.

```
---
kind: TypePermissions
version: v1
definition:
  typeName: InsertProfileMediasObject
  permissions:
    - role: user
      output:
        allowedFields:
          - createdAt
          - id
          - image
          - profileId
          - sequence
          - type
          - updatedAt
      input:
        fieldPresets:
          - field: profileId
            value:
              sessionVariable: "x-hasura-profile-id"
```

neither **literal value** inside the fieldPresets. I am sure that the x-hasura-profile-id has value. 

Suprisely, which that data were insert into db is null instead of the id of profile. 

Anyone meet this issue before, I am using **hasura ddn v3**.

**Comment by robertjdominguez** [comment]
@socheatleang — thanks for starting this discussion! I've run into a similar issue — though with `ArgumentPresets` — and solved it this way:

First, I created a native query:

```sql
INSERT INTO public."registrations" ("user_id", "ip_address", "lat", "long") VALUES (
  {{user_id}},
  {{ip_address}},
  {{lat}},
  {{long}}
)
RETURNING *
```

Then, generated the metadata for it and — as part of the `CommandPermissions` — added the `ArgumentPreset` using the session variable:

```yaml
---
kind: CommandPermissions
version: v1
definition:
  commandName: insert_registration
  permissions:
    - role: admin
      allowExecution: true
    - role: user
      allowExecution: true
      argumentPresets:
        - argument: user_id
          value:
            sessionVariable: x-hasura-user-id
```

This then allows for a mutation such as:

```gql
mutation INSERT_REGISTRATION($ip_address: text!, $lat: text!, $long: text!) {
    insert_registration(ip_address: $ip_address, lat: $lat, long: $long) {
      affected_rows
    }
  }
```

IIRC, there's some issue with passing non-array values to an autogenerated mutation. @danieljharvey — is there anything you'd add or change from what I shared above?
