### DISCUSSION TITLE
How can one configure query tags?

### DISCUSSION THREAD

**Discussion by miran248** [hasura/graphql-engine#10704] [Question]
Hey,

Where can one configure [query tags](https://hasura.io/docs/2.0/observability/query-tags/)?
Not sure if the docs are outdated or i'm just looking at the wrong place.
I went and modified `metadata/databases/databases.yaml` but so far nothing has changed.
The goal is to map generated sql statements, seen in gcp query insights with the original gql queries.

```yaml
- name: default
  kind: postgres
  configuration:
    connection_info:
      database_url:
        from_env: HASURA_GRAPHQL_DATABASE_URL
      isolation_level: read-committed
      pool_settings:
        connection_lifetime: 600
        idle_timeout: 180
        max_connections: 50
        retries: 0
      use_prepared_statements: false
  tables: "!include default/tables/tables.yaml"
  functions: "!include default/functions/functions.yaml"
  query_tags:
    disabled: false
    format: sqlcommenter
    omit_request_id: false
```

Hasura v2.44.0
Config v3

Thanks!
