### DISCUSSION TITLE
MySQL server has gone away

### DISCUSSION THREAD

**Discussion by niekcandaele** [hasura/graphql-engine#6294] [General] [answered]
Having issues sometimes with Hasura MySQL.

![image](https://user-images.githubusercontent.com/22315101/101060509-c9f7fc80-358f-11eb-977d-1face8c14c88.png)

This usually happens after the gql engine and mysql server have been running for a (relatively) long time, eh overnight. Some googling resulted me with [an article in mysql docs](https://dev.mysql.com/doc/refman/8.0/en/gone-away.html). I have no idea what I would change with this information though. As far as I understand, expected behaviour is that the mysql client would automatically create a fresh connection

Any guidance is appreciated!

```yml
version: "3.0"
services:
  web:
    image: wordpress
    links:
      - mysql
    environment:
      - WORDPRESS_DB_PASSWORD=supersecret
    ports:
      - "127.0.0.4:8080:80"
    volumes:
      - ./wordpress:/var/www/html
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=my-wpdb
    volumes:
      - mysql:/var/lib/mysql
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - hasura_mysql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:pull5655-633f084f
    ports:
      - "127.0.0.4:8081:8080"
    depends_on:
      - "postgres"
    command:
      - graphql-engine
      - --mysql-host
      - mysql
      - --mysql-user
      - root
      - --mysql-port
      - "3306"
      - --mysql-dbname
      - my-wpdb
      - --mysql-password
      - supersecret
      - serve
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: xxx
volumes:
  hasura_mysql:
  mysql:

```

```
graphql-engine_1  | "SELECT  coalesce(JSON_ARRAYAGG(`root` ), json_array( ) ) AS `root` FROM  (SELECT  json_object('status', (SELECT  `_0_root.base`.`status` AS `status`       ), 'net_total', (SELECT  `_0_root.base`.`net_total` AS `net_total`       ), 'num_items_sold', (SELECT  `_0_root.base`.`num_items_sold` AS `num_items_sold`       ), 'order_id', (SELECT  `_0_root.base`.`order_id` AS `order_id`       ) ) AS `root` FROM  (SELECT  *  FROM `wordpress`.`wp_wc_order_stats`  WHERE ((`wordpress`.`wp_wc_order_stats`.`status`) = (('wc-processing')))     ) AS `_0_root.base`      ) AS `_1_root`      "
graphql-engine_1  | {"type":"http-log","timestamp":"2020-12-03T16:56:37.797+0000","level":"info","detail":{"operation":{"query_execution_time":5.914457e-3,"user_vars":{"x-hasura-spanid":"15699751531939687584","x-hasura-role":"admin","x-hasura-traceid":"3078733648561482393"},"request_id":"f7ff6ea5-0bfb-43de-873e-951c7a1af5cd","response_size":85,"request_read_time":3.4336e-5},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"192.168.0.1","method":"POST","content_encoding":"gzip"}}}
```
