### DISCUSSION TITLE
Track all Public Tables on Init

### DISCUSSION THREAD

**Discussion by jesseflorig** [hasura/graphql-engine#8558] [Question] [answered]
I have the following `docker-compose.yml`:

```
version: '3.6'
services:
  postgres:
    image: postgres:12
    ports:
    - "5432:5432"
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  graphql-engine:
    image: hasura/graphql-engine:v2.7.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      ## DEV: enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      ## DEV: enable debugging mode.
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
```
When the containers start, my seeded database is already connected to Hasura. However, I still have to use the UI to "track all" the tables in the `public` schema. Is it possible to automatically track those tables via configuration?

It looks like there used to be a Hasura CLI command for this:
```
asura metadata track --all-tables [--schema public]
```
It would be great to include something like this in the `docker-compose.yaml`.
