### DISCUSSION TITLE
Cant upgrade docker compose to v2.8.1 - ERROR: UtilConnectToInteropServer:307

### DISCUSSION THREAD

**Discussion by costas90** [hasura/graphql-engine#8629] [Question] [answered]
My  `docker-compose.yml`

```
version: "3.6"
services:
  postgres:
    ports:
      - "5432:5432"
    image: mdillon/postgis:11
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.8.1
    env_file:
      - .env
    ports:
      - "7070:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console

volumes:
  db_data:
```

On `docker-compose up -d` I get:
> <3>init: (5504) ERROR: UtilConnectToInteropServer:307: connect failed 2
[+] Running 0/0
 ⠋ graphql-engine Pulling                                                                0.0s
error getting credentials - err: exit status 1, out: ``
