### DISCUSSION TITLE
path based routing on hasura

### DISCUSSION THREAD

**Discussion by moshtab** [hasura/graphql-engine#8817] [General]
Can we do path based routing on hasura? If we can then what should be the context path. Please suggest

**Comment by adas98012** [comment]
Hasura does not have a "routing" feature, much less "path based routing".

Can you expand on what you mean by "path based routing"?
Perhaps links to external resources so we can understand your question?

**Comment by moshtab** [comment]
Hi,
Suppose if we writing ingress rules which is pointing to hasura service
For example
spec: rules: - http: paths: - path: /What should be mentioned here? backend:
serviceName: hasura-service servicePort: 8080


So, in the above example, what should be the value for path, if iam going
with path based routing.....

**Reply by BenoitRanque** [reply]
Hasura does not have routing functionality.
If you are handling routing in a reverse proxy or similar, you would need to defer to the documentation of that server.

If you are using hasura cloud you would typically point to your hasura instance's endpoint.

**Reply by dsandip** [reply]
I could be wrong, but perhaps the path in the ingress/reverse-proxy will be something like `<domain-where-hasura-is-deployed>/v1/graphql` (e.g. https://localhost:8080/v1/graphql or `https://moshtab.hasura.app/v1/graphql`

**Comment by 86label** [comment]
I have tried what you're suggesting, and found the following to be needed in an ingress to point to 2 different services using one ingress.
```yaml
rules:
  - host: my-host.someurl.com
    http:
      paths:
      - backend:
          service:
            name: hasura-service
            port:
              number: 443
        path: /console
        pathType: ImplementationSpecific
      - backend:
          service:
            name: hasura-service
            port:
              number: 443
        path: /v1
        pathType: ImplementationSpecific
      - backend:
          service:
            name: hasura-service
            port:
              number: 443
        path: /v2
        pathType: ImplementationSpecific
      - backend:
          service:
            name: otherapp-service
            port:
              number: 443
        path: /
        pathType: ImplementationSpecific
```

**Reply by BenoitRanque** [reply]
I see, you seem to be setting up some ingress configuration for some third party service.

Besides the /console endpoint, you could look at our [API Reference](https://hasura.io/docs/latest/api-reference/index/) for a list of endpoints hasura has.

**Comment by moshtab** [comment]
Hi Hasura/Graphql-Engine

Can we change the hasura console context path?

Suppose i want to add a prefix to my hasura url like below

<my_domain>/test/console

Can we do this?
If we can then what are the possible ways..

**Comment by akhil-naidu** [comment]
Jumping here to clarify a few things. Let us assume the below was your ingress configuration.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hasura-ingress
  namespace: hasura
spec:
  rules:
  - host: hasura.yourdomian.com
    http:
      paths:
      - path: /hasura
        backend:
          serviceName: hasura-svc
          servicePort: 8080
```

**Note 1**: The above configuration alias to, when a public user reaches to `https://hasura.yourdoman.com/hasura` it will reach out to the `hasura-svc:8080` which can be multiple instances.

**Note 2**: To work with the Hasura GraphQL engine, one should be able to send a POST request to the URI: `hasura-svc:8080/v1/graphql`

**Note 3**: Based on the above path-based ingress configuration,
1. You can access Hasura Console(Web UI) at `https://hasura.yourdomian.com/hasura/console`
2. You need to send a POST request to `https://hasura.yourdomian.com/hasura/v1/graphql` to execute your GQL Queries/Mutation/Subscriptions
