### DISCUSSION TITLE
Webhook Auth call failed without making the call

### DISCUSSION THREAD

**Discussion by ssamsundar** [hasura/graphql-engine#9199] [Question]
We've different sub-domain for Hasura and different sub-domain for webhook auth URL. When we make API call to Hasura, it is failing with `internal server error` . When we try to make the Auth API call using Curl inside the container, it is working fine. 

We don't see any logs for API call in the API end, when we try to use Hasura API. What's the issue in Hasura? 

Here's the docker compose.yml
```
version: '3.6'
services:
    graphql-engine:
        image: hasura/graphql-engine:v2.14.0
        ports:
        - "8081:8080"
        restart: always
        environment:
         HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password#12345@myhost:5432/Hasura
         ## enable the console served by server
         HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
         ## enable debugging mode. It is recommended to disable this in production
         HASURA_GRAPHQL_DEV_MODE: "true"
         HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
         ## uncomment next line to set an admin secret
         HASURA_GRAPHQL_ADMIN_SECRET: myadminsecret
         HASURA_GRAPHQL_AUTH_HOOK: https://myenv.mysub1.domain.com/hasura-auth/api/Auth
         HASURA_GRAPHQL_AUTH_HOOK_MODE: GET
```

Here's the log, when we call the Hasura API `https://myenv1.mysub2.domain.com/Hasura/api/rest/myendpoint`
```
{
    "detail": {
        "http_error": {
            "message": "Internal Exception",
            "request": {
                "host": "myenv.mysub1.domain.com",
                "method": "GET",
                "path": "/hasura-auth/api/Auth",
                "port": 443,
                "queryString": "",
                "requestHeaders": {
                    "Authorization": "<REDACTED>",
                    "Content-Type": "application/json",
                    "Postman-Token": "f4986118-b645-43a4-bd6f-1aa9e8ba5973",
                    "User-Agent": "hasura-graphql-engine/v2.14.0",
                    "X-Forwarded-For": "10.156.162.114",
                    "X-Forwarded-Proto": "https",
                    "x-request-id": "c5344b47-7e75-4a2a-b8b9-9bb2f858d310"
                },
                "responseTimeout": "ResponseTimeoutDefault",
                "secure": true
            },
            "type": "http_exception"
        },
        "message": null,
        "method": "GET",
        "response": null,
        "status_code": null,
        "url": "https://myenv.mysub1.domain.com/hasura-auth/api/Auth"
    },
    "level": "error",
    "timestamp": "2022-11-09T11:54:49.751+0000",
    "type": "webhook-log"
}
```
