### DISCUSSION TITLE
Changes not reflected on migration file for a dockerized hasura container

### DISCUSSION THREAD

**Discussion by RyadMM** [hasura/graphql-engine#9410] [Question]
Hey guys we are stuck in an odd issue. We are setting up a new env for a project 
- We dockerized the hasura engine
- We want the CLI to run on the docker and be able to automatically generate the migration when changes are made using the hasura console (like adding a new column for example) 
- We set the CONSOLE env var to TRUE and added a volume that links to the local file system but for some reason, we are unable to see the corresponding migration file changes once we make an update via the console.
- We are using : “hasura-cli”: “^2.17.0"

Our (simplified) docker-compose.yml

```
api:
    # restart: always
    env_file: .env
    build:
      dockerfile: ./apps/api/Dockerfile
    container_name: api
    volumes:
      - ./apps/api:/app/apps/api
      - /app/apps/api/node_modules
    ports:
      - 3000:3000
    depends_on:
      - "graphql-engine"
  postgres:
    image: postgres:12
    # restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.16.1
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - ./apps/hasura/migrations:/hasura-migrations
      - ./apps/hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, webhook-log, websocket-log, query-log"
      HASURA_GRAPHQL_ADMIN_SECRET: XXXXX
      HASURA_GRAPHQL_JWT_SECRET: '{ "type": "HS256", "key": "XXXXX" }'
volumes:
  db_data:
  ```
