### DISCUSSION TITLE
How to properly create a preview instance?

### DISCUSSION THREAD

**Discussion by flasd** [hasura/graphql-engine#9639] [Question]
I'm running the suggested actions as document on https://github.com/hasura/hasura-cloud-preview-apps. I'm getting

```
{
  id: '681701b8-004f-4725-951c-70[28](https://github.com/arvo-dot/arvo/actions/runs/4974061328/jobs/8900293326#step:5:29)8496c095',
  event_type: 'failed',
  public_event_data: null,
  error: "error creating tenant: Message: user doesn't have access to create Hasura Cloud Project, Locations: [], Extensions: map[code:legacyError id:2de5340f-a943-412c-a0eb-7caf200e2dfc]"
}
```

I've checked, replaced and logged my Hasura Cloud access token to make sure it was set properly and it is.

Failing portion of my workflow:

```yaml
- uses: hasura/hasura-cloud-preview-apps@v0.1.7
  with:
    hasuraProjectDirectoryPath: hasura
    name: 'arvo-hasura-preview-${{steps.get_pull_request_id.outputs.pull_request_id}}'
    tier: cloud_free
    hasuraEnv: |
      PG_DATABASE_URL=${{steps.create_branch.outputs.db_url}}
      HASURA_GRAPHQL_ADMIN_SECRET=$(jq --raw-output .pull_request.base.sha "$GITHUB_EVENT_PATH" | cut -c1-8)
      HASURA_GRAPHQL_JWT_SECRET={"claims_namespace_path":"$.hasura.claims","jwk_url":"https://arvo-preview-pr-${{steps.get_pull_request_id.outputs.pull_request_id}}.herokuapp.com/auth/jwks"}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE=anonymous
      HASURA_GRAPHQL_CORS_DOMAIN=https://arvo-preview-pr-${{steps.get_pull_request_id.outputs.pull_request_id}}.herokuapp.com
  env:
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    HASURA_CLOUD_ACCESS_TOKEN: ${{secrets.HASURA_CLOUD_ACCESS_TOKEN}}
```

Also passing `tier: cloud_free_v2` will fail to complete but will create ~4 or 5 projects on the console.
