### DISCUSSION TITLE
Hasura graphql-engine server does not start properly on local environment after version 2.17.1

### DISCUSSION THREAD

**Discussion by maria-nemeti** [hasura/graphql-engine#9676] [Question]
Hi all,
We are using hasura in production and currently the cloud version is at [v2.25.1-cloud.1], but we didn’t manage to keep up to date with our local development environment where we did get stuck to version 2.17.1 (hasura/graphql-engine:v2.17.1.cli-migrations-v3). The reason is that any newer version just cannot start properly even if we did not change anything in our docker compose yaml file:

```
version: '3.8'
services:
  postgres:
    image: safenow/hasura-alarmdata-db:latest
    environment:
      POSTGRES_PASSWORD: postgrespassword
    networks:
      - alarmdata2
    ports:
      - "5432:5432"
  graphql-engine:
    image: safenow/hasura-alarmdata-with-migrations:latest
    ports:
      - "7070:7070"
    restart: always
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_SERVER_PORT: 7070
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "true" to enable console, but be aware that then the migrations/metadata are not written to disc
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup,http-log,webhook-log,websocket-log,query-log,livequery-poller-log,action-handler-log,data-connector-log # all allowed log-types
      HASURA_GRAPHQL_LOG_LEVEL: "debug"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"Secret"}'
      HASURA_GRAPHQL_ADMIN_SECRET: "sss"
      WAIT_BEFORE_START_ENDPOINT: "postgres:5432"
      HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
    networks:
      - alarmdata2
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

In the logs didn't find anything suspicious, the last thing logged is an invocation of the cron trigger, so it looks like will start, but then it just stops..

Any idea how to fix this?
Thanks in advance,
Maria

```
{"detail":{"info":"gracefully shutting down server","kind":"server"},"level":"info","timestamp":"2023-05-25T19:43:23.259+0000","type":"startup"}
{"detail":"Shutting websockets server down","level":"debug","timestamp":"2023-05-25T19:43:23.259+0000","type":"unstructured"}
{"detail":"Stopping immortal update JWK thread","level":"info","timestamp":"2023-05-25T19:43:23.259+0000","type":"unstructured"}
{"detail":"Stopping immortal runTelemetry thread","level":"info","timestamp":"2023-05-25T19:43:23.259+0000","type":"unstructured"}
{"detail":"Stopping immortal websocket connection reaper thread thread","level":"info","timestamp":"2023-05-25T19:43:23.259+0000","type":"unstructured"}
{"detail":"Stopping immortal sourcePingPoller thread","level":"info","timestamp":"2023-05-25T19:43:23.259+0000","type":"unstructured"}
{"detail":"Stopping immortal checkForUpdates thread","level":"info","timestamp":"2023-05-25T19:43:23.259+0000","type":"unstructured"}
{"detail":{"info":"All in-flight events have finished processing","kind":"scheduled_events"},"level":"info","timestamp":"2023-05-25T19:43:23.259+0000","type":"startup"}
{"detail":{"info":{"database_url":"postgres://postgres:...@postgres:5432/postgres","retries":1},"kind":"postgres_connection"},"level":"info","timestamp":"2023-05-25T19:43:23.624+0000","type":"startup"}
{"detail":{"info":"Already at the latest catalog version (48); nothing to do.","kind":"catalog_migrate"},"level":"info","timestamp":"2023-05-25T19:43:23.624+0000","type":"startup"}
{"detail":{"info":"Schema sync enabled. Polling at Refined (Milliseconds {milliseconds = 1s})","kind":"schema-sync"},"level":"info","timestamp":"2023-05-25T19:43:23.624+0000","type":"startup"}
{"detail":{"info":{"instance_id":"adb44e24-87d9-4c37-837d-4e57a049bc00","message":"listener thread started","thread_id":"ThreadId 28"},"kind":"schema-sync"},"level":"info","timestamp":"2023-05-25T19:43:23.624+0000","type":"startup"}
{"detail":{"info":"EE client credentials not present in the metadata database. Hasura EE features are disabled.","kind":"license_info"},"level":"warn","timestamp":"2023-05-25T19:43:23.624+0000","type":"startup"}
{"detail":{"info":"Successfully resolved source","kind":"resolve_source"},"level":"debug","timestamp":"2023-05-25T19:43:23.624+0000","type":"startup"}
{"detail":{"info":{"message":"source \"default\" is already at the latest catalog version (3).","source":"default"},"kind":"source_catalog_migrate"},"level":"info","timestamp":"2023-05-25T19:43:23.624+0000","type":"startup"}
{"detail":"Thread ourIdleGC (re)started","level":"info","timestamp":"2023-05-25T19:43:23.624+0000","type":"unstructured"}
{"detail":"Thread SchemeUpdate.listener (re)started","level":"info","timestamp":"2023-05-25T19:43:23.624+0000","type":"unstructured"}
{"detail":"Stopping immortal processScheduledTriggers thread","level":"info","timestamp":"2023-05-25T19:43:25.525+0000","type":"unstructured"}
{"detail":{"num_cron_events_fetched":2,"num_fetches":1,"num_one_off_scheduled_events_fetched":0},"level":"info","timestamp":"2023-05-25T19:43:25.525+0000","type":"scheduled-trigger-process"}
{"detail":"Stopping immortal runCronEventsGenerator thread","level":"info","timestamp":"2023-05-25T19:43:25.525+0000","type":"unstructured"}
{"detail":"Stopping immortal asyncActionSubscriptionsProcessor thread","level":"info","timestamp":"2023-05-25T19:43:25.525+0000","type":"unstructured"}
{"detail":{"info":"All in-flight events have finished processing","kind":"async_actions"},"level":"info","timestamp":"2023-05-25T19:43:25.525+0000","type":"startup"}
{"detail":"Stopping immortal asyncActionsProcessor thread","level":"info","timestamp":"2023-05-25T19:43:25.525+0000","type":"unstructured"}
{"detail":{"info":"All in-flight events have finished processing","kind":"event_triggers"},"level":"info","timestamp":"2023-05-25T19:43:25.525+0000","type":"startup"}
{"detail":"Stopping immortal processEventQueue thread","level":"info","timestamp":"2023-05-25T19:43:25.525+0000","type":"unstructured"}
{"detail":"Stopping immortal SchemeUpdate.processor thread","level":"info","timestamp":"2023-05-25T19:43:25.525+0000","type":"unstructured"}
{"detail":"Stopping immortal SchemeUpdate.listener thread","level":"info","timestamp":"2023-05-25T19:43:25.525+0000","type":"unstructured"}
{"detail":{"cron_triggers":[],"num_fetches":1},"level":"info","timestamp":"2023-05-25T19:43:25.525+0000","type":"cron-event-generator-process"}
{"detail":{"num_events_fetched":{},"num_fetches":11},"level":"info","timestamp":"2023-05-25T19:43:25.525+0000","type":"event-trigger-process"}
{"detail":"The following environment variables are deprecated and moved to metadata: HASURA_GRAPHQL_NO_OF_RETRIES","level":"warn","timestamp":"2023-05-25T19:43:25.856+0000","type":"unstructured"}
{"detail":{"info":{"instance_id":"adb44e24-87d9-4c37-837d-4e57a049bc00","message":"processor thread started","thread_id":"ThreadId 93"},"kind":"schema-sync"},"level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"startup"}
{"detail":{"info":"starting workers","kind":"event_triggers"},"level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"startup"}
{"detail":"Thread asyncActionSubscriptionsProcessor (re)started","level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"unstructured"}
{"detail":"Thread processScheduledTriggers (re)started","level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"unstructured"}
{"detail":"Thread update JWK (re)started","level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"unstructured"}
{"detail":"Thread runCronEventsGenerator (re)started","level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"unstructured"}
{"detail":"Thread checkForUpdates (re)started","level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"unstructured"}
{"detail":"Thread SchemeUpdate.processor (re)started","level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"unstructured"}
{"detail":"Thread processEventQueue (re)started","level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"unstructured"}
{"detail":{"info":"preparing data","kind":"scheduled_triggers"},"level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"startup"}
{"detail":"Thread sourcePingPoller (re)started","level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"unstructured"}
{"detail":{"info":"Help us improve Hasura! The graphql-engine server collects anonymized usage stats which allows us to keep improving Hasura at warp speed. To read more or opt-out, visit https://hasura.io/docs/latest/graphql/core/guides/telemetry.html","kind":"telemetry"},"level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"startup"}
{"detail":{"info":{"message":"starting API server","time_taken":2.2845795},"kind":"server"},"level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"startup"}
{"detail":"Thread asyncActionsProcessor (re)started","level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"unstructured"}
{"detail":"Thread websocket connection reaper thread (re)started","level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"unstructured"}
{"detail":"Thread runTelemetry (re)started","level":"info","timestamp":"2023-05-25T19:43:25.856+0000","type":"unstructured"}
{"detail":{"event_id":"5bc4e154-06ed-45c9-bc33-885ddf14a0be","event_name":"ResetOutdatedLocations","request":{"original_request":{"body":"{\"comment\":\"This endpoint executes bulk update operation which sets all locations to latitude=null, longitude=null for all person_locations with old phonestatuses\",\"id\":\"5bc4e154-06ed-45c9-bc33-885ddf14a0be\",\"name\":\"ResetOutdatedLocations\",\"payload\":{},\"scheduled_time\":\"2023-05-25T19:44:00Z\"}","headers":{"Content-Type":"application/json","User-Agent":"hasura-graphql-engine/v2.25.1","caller":"hasura"},"method":"POST","query_string":"","response_timeout":"5000000","url":"{{SAFENOW_PHONESTATUS_RECEIVER_BASEURL}}/resetOutdatedLocations"},"original_size":293,"req_transform_ctx":null,"session_vars":null,"transformed_request":null,"transformed_size":null},"response":{"detail":{"message":"Connection failure","request":{"host":"host.docker.internal","method":"POST","path":"/resetOutdatedLocations","port":8901,"queryString":"","requestHeaders":{"Content-Type":"application/json","User-Agent":"hasura-graphql-engine/v2.25.1","X-B3-ParentSpanId":"7d8382c6cee1c905","X-B3-Sampled":"1","X-B3-SpanId":"6fe4c9d044bdf3bf","X-B3-TraceId":"58e2d58bbf9309a2fa2f933b6828c015","caller":"hasura"},"responseTimeout":"ResponseTimeoutMicro 5000000","secure":false},"type":"http_exception"},"type":"client"}},"level":"info","timestamp":"2023-05-25T19:44:05.892+0000","type":"scheduled-trigger"}
{"detail":{"event_id":"c220196d-b189-4293-b088-00e6ec27b7aa","event_name":"EvaluateRules","request":{"original_request":{"body":"{\"comment\":\"Cron that triggers the rule-engine\",\"id\":\"c220196d-b189-4293-b088-00e6ec27b7aa\",\"name\":\"EvaluateRules\",\"payload\":{},\"scheduled_time\":\"2023-05-25T19:44:00Z\"}","headers":{"Content-Type":"application/json","User-Agent":"hasura-graphql-engine/v2.25.1","caller":"hasura"},"method":"POST","query_string":"","response_timeout":"60000000","url":"{{SAFENOW_RULE_ENGINE_BASEURL}}/evaluateRules"},"original_size":168,"req_transform_ctx":null,"session_vars":null,"transformed_request":null,"transformed_size":null},"response":{"detail":{"message":"Connection failure","request":{"host":"host.docker.internal","method":"POST","path":"/evaluateRules","port":8712,"queryString":"","requestHeaders":{"Content-Type":"application/json","User-Agent":"hasura-graphql-engine/v2.25.1","X-B3-ParentSpanId":"7ff53e914c1d096b","X-B3-Sampled":"1","X-B3-SpanId":"3a0da82feac908fa","X-B3-TraceId":"a59118fac4af8b493321cbfcb640cba1","caller":"hasura"},"responseTimeout":"ResponseTimeoutMicro 60000000","secure":false},"type":"http_exception"},"type":"client"}},"level":"info","timestamp":"2023-05-25T19:44:05.892+0000","type":"scheduled-trigger"}
```
