### ISSUE TITLE
update docs css for better in-line monospace highlighting

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#1011]
We need to add the following CSS to docs:

```css
code .docutils .literal {
    padding: 0.2em 0.4em;
    margin: 0;
    background-color: rgba(27,31,35,0.05);
    border-radius: 3px;
}
```

This gives better highlighting for in-line monospace text, wrapped in ` ``<text>`` ` blocks within `rst`.

before:
![image](https://user-images.githubusercontent.com/4124733/48331820-78fad000-e677-11e8-9f46-cc381e3e6939.png)

after:
![image](https://user-images.githubusercontent.com/4124733/48331810-71d3c200-e677-11e8-91c0-8bb5637e1645.png)
