### ISSUE TITLE
V3 README steps for running in Docker do not work

### ISSUE THREAD

**Issue by TristenHarr** [hasura/graphql-engine#10219]
The V3 repo has a section on running with Docker that states to run with Docker you can use this command: 

`METADATA_PATH=crates/open-dds/examples/reference.json AUTHN_CONFIG_PATH=auth_config.json docker compose up`

However, when running this command the container fails to start because of missing volume mounts. 

Editting the docker-compose.yaml to properly mount the volumes like this:

```
  engine:
    build:
      dockerfile: debug.Dockerfile
    entrypoint:
      - ./bin/engine
    environment:
      - METADATA_PATH
      - AUTHN_CONFIG_PATH
      - OTLP_ENDPOINT=http://jaeger:4317
    ports:
      # Binding to localhost:3001 avoids conflict with dev_setup
      - 3001:3000
    depends_on:
      reference_agent:
        condition: service_started
      jaeger:
        condition: service_started
      auth_hook:
        condition: service_started
    volumes:
      - ./auth_config.json:/app/auth_config.json
      - ./crates/open-dds/examples/reference.json:/app/crates/open-dds/examples/reference.json
```

The above fixes the volume mount issue, however there seems to be an issue with the reference schema, as the engine still fails to start. 

`2024-04-29 14:42:19 Error while starting up the engine: could not read the schema - unable to build schema: metadata is not consistent: the collection authors in the data connector db (in subgraph default) for model Authors (in subgraph default) has not been defined`

This was originally surfaced on Discord in our forum in [this thread](https://discord.com/channels/407792526867693568/1233485068610048306). 

To reproduce this, clone the graphql-engine and attempt to start the V3-engine using the reference command from the README in the section about Docker. (The command referenced at the top of the issue!)
