### ISSUE TITLE
Remote relationships predicates are not working across SQLServer and Postgres connectors

### ISSUE THREAD

**Issue by codingkarthik** [hasura/graphql-engine#10415]
### What is the current behaviour?

Running the following GraphQL query:

```graphql
query MyQuery {
  // Top-level root field that queries the SQL server DB with a remote relationship predicate 
  sqlSubgraph_album1(where: {remote_artist1: {name: {_eq: "Santana"}}}) {
    title
    artist1 { // local relationship 
      name
    }
    remote_artist1 { // Remote relationship querying the PG connector
      name
    }
  }
}
```

```json
{
  "data": null,
  "errors": [
    {
      "message": "internal error"
    }
  ]
}
```

P.S: Also, the traces are not viewable.

### What is the expected behaviour?

Get the correct response.

### How to reproduce the issue?

1. Create a subgraph with a postgres and a SQL server connector.
2. Add the following remote relationship to the `Album` type:
```yaml
kind: Relationship
version: v1
definition:
  name: remote_artist1
  sourceType: Album_1
  target:
    model:
      name: Artist
      subgraph: sql_subgraph
      relationshipType: Object
  mapping:
    - source:
        fieldPath:
          - fieldName: artistId
      target:
        modelField:
          - fieldName: artistId
```
4. Create a new supergraph build.
5. Run the following GraphQL query:

```graphql
query MyQuery {
  // Top-level root field that queries the SQL server DB with a remote relationship predicate 
  sqlSubgraph_album1(where: {remote_artist1: {name: {_eq: "Santana"}}}) {
    title
    artist1 { // local relationship 
      name
    }
    remote_artist1 { // Remote relationship querying the PG connector
      name
    }
  }
}
```
