### ISSUE TITLE
docs: multi-region routing documentation is out of date

### ISSUE THREAD

**Issue by scriptnull** [hasura/graphql-engine#10453]
### Component

Docs

### What is the current behaviour?

The multi-region routing documentation here is outdated and contains a reference to the connector manifest:

https://hasura.io/docs/3.0/graphql-api/multi-region-routing#configuration

### What is the expected behaviour?

It has to resemble the new format. It will be something like

```
kind: Connector
version: v1
definition:
  name: my_clickhouse
  subgraph: my_subgraph
  source: hasura/clickhouse:<version>
  context: .
  envFile: .env.cloud
  regionConfiguration:
    - region: <region> # choose one of these supported regions: https://hasura.io/docs/3.0/graphql-api/multi-region-routing#supported-regions
      mode: ReadWrite
```

### How to reproduce the issue?

N/A

### Screenshots or Screencast

N/A

### Please provide any traces or logs that could help here.

N/A

### Keywords

docs
