### ISSUE TITLE
Invalid OpenTelemetry logs shape

### ISSUE THREAD

**Issue by ValentinH** [hasura/graphql-engine#10472]
### Version Information

Server Version: v2.40.0-cloud.1

### Environment

Cloud

### What is the current behaviour?

We are using the OpenTelemetry feature to forward the Hasura Logs. I recently noticed that the shape of the logs was not matching anymore was it documented [here](https://hasura.io/docs/latest/observability/opentelemetry/graphql-engine/#log-structure).

Instead, inside the `body` property, we have an intermediate empty key:
![image](https://github.com/user-attachments/assets/77d717cc-eca8-4802-a9dd-954e0fd830ed)

This is messing with standard OTEL tools that are ingesting these logs.

### What is the expected behaviour?

The `body` property should directly have the right properties without the intermediate object with the empty key.

### How to reproduce the issue?

Enable the OpenTelemetry exporter.

### Screenshots or Screencast

![image](https://github.com/user-attachments/assets/1ad5732c-37aa-47d5-8a13-dd177be4b74a)

### Keywords

OTEL, OpenTelemetry, Logs

**Comment by hgiasac** [comment]
@ValentinH Can you provide more information about your OTEL setup? We don’t set the empty key on purpose and this issue hasn’t been reported by our other users.
- The observability service you are using.
- OpenTelemetry collector configuration.

The structure of OTEL logs is different from the standard logging because we follow the OTEL logs model spec. It's mentioned in the docs
https://hasura.io/docs/latest/observability/opentelemetry/graphql-engine/#log-structure

**Comment by ValentinH** [comment]
Thanks for the quick answer.

Here is the opentelemetry.yaml file:
```yaml
status: enabled
data_types:
  - logs
exporter_otlp:
  headers:
    - name: x-axiom-dataset
      value_from_env: AXIOM_INGEST_DATASET
    - name: authorization
      value_from_env: AXIOM_INGEST_API_TOKEN
  otlp_logs_endpoint: https://api.axiom.co/v1/logs
  protocol: http/protobuf
  resource_attributes: []
  traces_propagators:
    - b3
batch_span_processor:
  max_export_batch_size: 512
```

We are using Axiom to collect these logs: https://axiom.co/docs/send-data/opentelemetry
