### ISSUE TITLE
Query Usage Analytics: Incorrect reporting of field usage in permissions

### ISSUE THREAD

**Issue by rakeshkky** [hasura/graphql-engine#10481]
### What is the current behaviour?

When permissions involve filtering with relationships, the field comparisions used in the relationship predicate are reported as the root field usage. This is incorrect.
Example: Consider the following permission filter.
```
filter:
  relationship:
    name: Album
    predicate:
      fieldComparison:
        field: released_year
        operator: _gte
        value:
          literal: "2020"
```
Query: Fetching tracks which permission defined on its `Album` relationship
```
query {tracks {Id Name} }
```
Reported analytics:
```
used:
  permission:
    relationships:
    - name: Album
      source:
        name: Track
        subgraph: default
      target:
        model:
          model_name:
            name: tracks
            subgraph: default
          relationship_type: Object
    fields:
    - name: released_year
      opendd_type:
        subgraph: default
        name: album
```

### What is the expected behaviour?

Each relationship usage reported in the permission filters should have an additional field that reports the fields/relationships usage in its inner predicate. In the above example, the `released_year` permission field usage should be reported with in `Album` relationship field usage.
```
used:
  permission:
    relationships:
    - name: Album
      source:
        name: Track
        subgraph: default
      target:
        model:
          model_name:
            name: tracks
            subgraph: default
          relationship_type: Object
      predicate_usage:
        fields:
        - name: released_year
          opendd_type:
            subgraph: default
            name: album
```

### How to reproduce the issue?

1. Create a model permission with a select filter with relationships.
2. Make a query with the permission enforced.
3. Query usage analytics is reported in the traces as a JSON string attached to `internal.query_usage_analytics` attribute in the `execute` span.
