### ISSUE TITLE
Docker compose up results in all containers being in "restarting" state

### ISSUE THREAD

**Issue by sgaseretto** [hasura/graphql-engine#1048]
Each time I run docker-compose up -d from this docker-compose.yaml
```
version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha29
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
    command:
      - graphql-engine
      - serve
      - --enable-console
volumes:
  db_data:
```
The containers appear as always restarting and the ports aren't mapped
```
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                          PORTS               NAMES
8bc9eba39958        hasura/graphql-engine:v1.0.0-alpha29   "graphql-engine serv…"   3 minutes ago       Restarting (1) 58 seconds ago                       hasura_graphql-engine_1
28ecf57f9548        postgres                               "docker-entrypoint.s…"   3 minutes ago       Restarting (1) 8 seconds ago                        hasura_postgres_1
```
