### ISSUE TITLE
Support Enum Types

### ISSUE THREAD

**Issue by plcplc** [hasura/graphql-engine#10495]
### Component

Graphql Engine (for features that relates to graphql features; metadata modeling)

### Is your proposal related to a problem?

It should be possible to specify that certain DDN types be represented as [Enum types](https://spec.graphql.org/October2021/#sec-Enums) in GraphQL.

### Describe the solution you'd like

I should be able to add a piece of DDN metadata such as the following:

```yaml
kind: EnumType
version: v1
definition:
  name: MyEnum
  values:
    - VALUE_1
    - VALUE_2
    - VALUE_3
  graphql:
    typeName: My_Enum
```

This should define a ddn type `MyEnum` which I can refer to in my API metadata and map to ndc types.

Additionally, when an NDC advertises a type has an [Enum Type Representation](https://hasura.github.io/ndc-spec/specification/schema/scalar-types.html#enum-representations), the `ddn` cli commands should assist me in defining the corresponding `kind: EnumType` ddn metadata.
