### ISSUE TITLE
Segmentation fault issue not referenced in the docs

### ISSUE THREAD

**Issue by zameel7** [hasura/graphql-engine#10516]
Isn't this something that needs to be added in the quickstart docs for V2?

For anyone following the getting started guide you have to specify the platform in the docker-compose.yml
```
graphql-engine:
    image: hasura/graphql-engine:v2.36.0
    platform: linux/arm64
    ...
```

_Originally posted by @matiasmir in https://github.com/hasura/graphql-engine/issues/6511#issuecomment-1895377508_
