### ISSUE TITLE
Building metadata with non-existent subgraphs succeeds without warning or errors

### ISSUE THREAD

**Issue by TristenHarr** [hasura/graphql-engine#10583]
When building the metadata and defining relationships in the HML, if you reference a non-existent subgraph the metadata will still build and then the relationships won't appear.

```
---
kind: Relationship
version: v1
definition:
  name: HelloWorld
  sourceType: Users
  target:
    command:
      name: Hello
      subgraph: some_subgraph_that_doesnt_exist // This silently fails
  mapping:
    - source:
        fieldPath:
          - fieldName: name
      target:
        argument: name
```

It would be good to validate the metadata and warn the user if a subgraph doesn't exist.
