### ISSUE TITLE
Enable Relationships on Fields not visible to Role

### ISSUE THREAD

**Issue by olmohake** [hasura/graphql-engine#10598]
### Is your proposal related to a problem?

I have a *user* table with *id, stripe_customer_id* etc and a relationship to stripe *getCustomersCustomer* and *GetPaymentMethods*. 
The relationship are defined as follows:

```yaml
---
kind: Relationship
version: v1
definition:
  name: customer
  sourceType: User
  target:
    command:
      name: GetCustomersCustomer
  mapping:
    - source:
        fieldPath:
          - fieldName: stripeId
      target:
        argument: 
          argumentName: id

---
kind: Relationship
version: v1
definition:
  name: payment_methods
  sourceType: User
  target:
    command:
      name: GetPaymentMethods
  mapping:
    - source:
        fieldPath:
          - fieldName: stripeId
      target:
        argument: 
          argumentName: customer
```
to enable the following query:

```gql
{
  user{
    id
    customer{
      invoiceSettings{
        defaultPaymentMethod
      }
      
    }
  }
}
```

As soon as i remove stripe_customer_id from the list of a allowedField the relationships are removed as well. 

### Describe the solution you'd like

If a role has the permission to view a subset of an ObjectType and the permission to call a Command, a relationship from ObjectType to Command should be accessible for the role, even if the role has no permission to access the field the relationship is based on directly .

I don't want to expose the stripe_customer_id to the user, but using it in the query-engine to resolve the related data should still be supported.

### Alternatives

Call commands with argumentPresets based on session variables.
