### ISSUE TITLE
fix(c/v3-engine): wrong node id when being a subgraph of apollo federation

### ISSUE THREAD

**Issue by jjangga0214** [hasura/graphql-engine#10650]
### Component

c/v3-engine

### What is the current behaviour?

node id is given like this.

```
eyJ2ZXJzaW9uIjoxLCJ0eXBlbmFtZSI6IkNoYXQiLCJpZCI6eyJ1aWQiOiJkODAzMWY1OC1kZWZlLTQzNDMtYjlkZS02MDI0OTRkMWQ5MzMifX0=
```

where base64-decoded result is like this.

```
{"version":1,"typename":"Chat","id":{"uid":"d8031f58-defe-4343-b9de-602494d1d933"}}
```

### What is the expected behaviour?

The `typename` should be different.

```
{"version":1,"typename":"Thread","id":{"uid":"d8031f58-defe-4343-b9de-602494d1d933"}}
```

### How to reproduce the issue?

1. I configured DDN to support Relay.

```yaml
kind: Model
version: v1
definition:
  globalIdSource: true
---
kind: ObjectType
version: v1
definition:
  globalIdFields:
    - uid
```

2. I enabled Apollo Federation.

```yaml
kind: GraphqlConfig
version: v1
definition:
  apolloFederation:
    enableRootFields: true
---
kind: Model
definition:
  graphql:
    apolloFederation:
      entitySource: true
---
kind: ObjectType
version: v1
definition:
  graphql:
    apolloFederation:
      keys:
        - fields:
            - uid
```

3. Postgres has tables `thread` and `chat`, each of whose pk is `uid`.

4. I created another GraphQL server whose schema is like this. 

```graphql
type Thread @key(fields: "uid") {
  uid: Uuid
}

type Chat @key(fields: "uid") {
  uid: Uuid
}

type Chunk {
  id: ID!
  chat: Chat!
  text: String!
  isLast: Boolean!
}

extend type Subscription {
  chunk: Chunk!
}
```

5. I federated DDN and the other GraphQL server by apollo federation. 
I use [Hive](https://the-guild.dev/graphql/hive) as a gateway. 
DDN is a subgraph of the apollo federation gateway. 

6. From client, I executed this.

```graphql
  subscription ChunkSubscription {
    chunk {
      chat {
        threadUid # `chat` table has a fk threadUid
        thread {
          id
        }
      }
    }
  }
```

7. If I see the result, it's wrong.

```js
console.log(chunk.chat.thread.id)
// eyJ2ZXJzaW9uIjoxLCJ0eXBlbmFtZSI6IkNoYXQiLCJpZCI6eyJ1aWQiOiJkODAzMWY1OC1kZWZlLTQzNDMtYjlkZS02MDI0OTRkMWQ5MzMifX0=
```

The decoded result of the id is like this.

```json
{"version":1,"typename":"Chat","id":{"uid":"d8031f58-defe-4343-b9de-602494d1d933"}}
```

The `typename` should be `"Thread"`.
`uid` (`d8031f58-defe-4343-b9de-602494d1d933`) is right, but typename is wrong.

### Keywords

apollo federation
entity
subgraph
node id
global id
relay
typename
