### ISSUE TITLE
feat(c/v3-ndc-postgres): opt-out SSL/TLS

### ISSUE THREAD

**Issue by jjangga0214** [hasura/graphql-engine#10688]
### Component

c/v3-ndc-postgres

### Is your proposal related to a problem?

I have a local postgres without SSL/TLS.
When I try to connect it with Hasura connector, an error occurs.

```sh
Attaching to app_main_pg-1, engine-1, otel-collector-1, postgres-1
app_main_pg-1     | {"timestamp":"2025-02-19T08:20:25.243842Z","level":"ERROR","fields":{"message":"Initialization error","meta.signal_type":"log","event.domain":"ndc","event.name":"Initialization error","name":"Initialization error","body":"unable to initialize connection pool: encountered unexpected or invalid data: unexpected response from SSLRequest: 0x00 (sqlx_postgres::connection::tls:97)","error":true},"target":"ndc_postgres::connector"}
app_main_pg-1     | 500 Internal Server Error: unable to initialize connection pool: encountered unexpected or invalid data: unexpected response from SSLRequest: 0x00 (sqlx_postgres::connection::tls:97)
app_main_pg-1     | (details: null)
```

### Describe the solution you'd like

I want an option not to use SSL/TLS for local development.

**Comment by jjangga0214** [comment]
Sorry,

it turned out the ndc tries to connect to postgres before the database becomes ready.

It works after making sure the connector starts after postgres passed a health check.

```yaml
# Unnecessary content is omitted for brevity.
services:
  app_main_pg:
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  postgres:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
```

Thanks :)
