### ISSUE TITLE
Support `valueFromEnv` for `jwkFromUrl` & `issuer` field in `auth-config.yaml` file

### ISSUE THREAD

**Issue by sanchitdikshit** [hasura/graphql-engine#10681]
### Describe alternatives you've considered

The current workaround is to use separate Supergraphs.

**Comment by ashishtilara** [comment]
One more request related to this is the documentation on encoding the values and examples for other attributes. for example, I have following setup that works but notice `~1` in path at some places to replace `/`, without that the parsing doesn't work.

```
kind: AuthConfig
version: v2
definition:
  mode:
    jwt:
      claimsConfig:
        locations:
          x-hasura-default-role:
            path:
              path: /https:~1~1example.com~1user/context
          x-hasura-allowed-roles:
            literal:
              - ADMIN
              - USER
          x-hasura-user-id:
            path:
              path: /https:~1~1lynksupplychain.com~1user/user_id
              default: null
      tokenLocation:
        type: BearerAuthorization
      key:
        jwkFromUrl: https://auth.example.com/.well-known/jwks.json
      audience:
        - https://api.example.com
      issuer: https://auth.example.com/
```
