### ISSUE TITLE
failed to wait for port 8080 (on first postgres run)

### ISSUE THREAD

**Issue by sulliwane** [hasura/graphql-engine#1168]
Hi,

When postgres/timescale docker is up for the first time, `hasura/graphql-engine:v1.0.0-alpha31.cli-migrations` will fail to start with this message:
```
starting graphql engine on port 8080...
waiting for 8080
.Postgres connection info:
    Host: timescale
    Port: 5432
    User: postgres
    Database: qu4nt
{"internal":"could not connect to server: Connection refused\n\tIs the server running on host \"timescale\" (172.18.0.4) and accepting\n\tTCP/IP connections on port 5432?\n","path":"$","error":"connection error","code":"postgres-error"}
```
If running `docker-compose down && docker-compose up` then graphql-engine works fine. I believe it due to the time used by postgres/timescale on a first init, but graphql-engine should still be resilient to this...

thanks for your feedback :)

docker-compose.yml excerpt:
```
services:
  timescale:
    image: timescale/timescaledb:latest-pg10
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha31.cli-migrations
    depends_on:
      - "timescale"
```
