### ISSUE TITLE
Docker install doesn't work

### ISSUE THREAD

**Issue by Bronson-Brown-deVost** [hasura/graphql-engine#1177]
I recently tried a Heroku deployment and it worked beautifully.  I wanted to give the Docker install a try, but have not been able to get it fully running.

I used the docker-compose.yaml provided here:

```
version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha31
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an access key
      # HASURA_GRAPHQL_ACCESS_KEY: mysecretaccesskey
volumes:
  db_data:
```

The containers spin up.  I am able to access my postgres database fine with the credentials `postgres://postgres:@postgres:5432/postgres`, I am also able to access the Hasura web client.  

The problem is that in the Hasura web client I cannot get a listing of database schemas in the "data" tab, nor can I create any tables.  I tried manually creating a table (and even other schemas) in the database, but they do not become visible in the Hasura web client.  I do get the following errors in the Hasura web client console: 
`Failed to fetch schema "401 Unauthorized\n"`
`Failed to load schema "401 Unauthorized\n"`

I do not see any errors in the logs `docker logs hasura_graphql-engine_1_c405e0611c3a`.  It seems like I have a permissions error, but I am unsure how to debug further.  Thank you for any advice you can give.
