### ISSUE TITLE
HASURA_GRAPHQL_JWT_SECRET not working with RS256 in docker-compose

### ISSUE THREAD

**Issue by jakobrosenberg** [hasura/graphql-engine#1288]
From docker-compose.yaml
HASURA_GRAPHQL_JWT_SECRET : '{"type":"RS256", "key":"-----BEGIN PUBLIC KEY-----[mypublickey]-----END PUBLIC KEY-----"}'

``Fatal Error: JWT conf: Error in $: Invalid JWK: Could not decode PEM: invalid PEM delimiter found``

Am I doing something wrong?

**Comment by shahidhk** [comment]
@jakobrosenberg This is typically a quoting/newline error. Can you use https://hasura.io/jwt-config and generate the value with proper escaping etc. and try agian?

**Comment by shahidhk** [comment]
Yes, as mentioned [here](https://docs.hasura.io/1.0/graphql/manual/auth/jwt.html#key),

> 
> `key`
> 
> - In case of symmetric key (i.e. HMAC based key), the key as it is. (e.g. - “abcdef…”).
> - In case of asymmetric keys (RSA etc.), only the public key, in a PEM encoded string or as a X509 certificate.

**Comment by jakobrosenberg** [comment]
Thank you for your help @shahidhk .

For anyone else with this problem, my solution was to decode the public key to XML and then reencode it to PEM.
https://superdry.apphb.com/tools/online-rsa-key-converter

**Comment by mklueh** [comment]
I´m running into the same error with my Kubernetes deployment.yml.

According to the documentation we have two possibilities declaring a public key

> 1. In case of symmetric key (i.e. HMAC based key), the key as it is. (e.g. - “abcdef…”). The key must be long enough for the algorithm chosen, (e.g. for HS256 it must be at least 32 characters long).
> 2. In case of asymmetric keys (RSA etc.), only the public key, in a PEM encoded string or as a X509 certificate.

So as our key is RS256 I´ve set that as the type and attached the key within the Json.

```
      containers:
        - image: hasura/graphql-engine:v1.0.0-beta.9
          imagePullPolicy: IfNotPresent
          name: hasura
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: postgres://hasura:[MASKED]@192.168.22.11:5432/
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
            - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
              value: "startup, http-log, webhook-log, websocket-log, query-log"
            - name: HASURA_GRAPHQL_JWT_SECRET
              value: '{"type": "RS256","key": "TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxOXBSeGY0TEtTcVErT1FGMDNXdVIrY21kRThYOFd1ZjVVQ3N1T1ZwNVlqM25vWFdZVnFhMUcrOTFhamJxUEVCZkEwWTljcW1CaWVJb0Z1UVdqZURlSnIvL0dJdjNnQXNtMEZQMzhleHgvMEFtMm1lQWhrdzltVVFaYUxOcStvSHZyUDdMUEIvOTNoNnBpUUVHak9rZXQyOEoyQW5pVDlpU2JadTNBZnNFNUdrN0hhZ2xZZWp3ZjlFTjRGdVM2UjVyU2lOeTRPemNBSExpbHVUVUMzQURSZjQ0alQ4end0UDdxOUk2aTB5aUVJeUR4Wlc4NHF6SGlyU1pWUEVqc0hheTNCNXpYK3NFdVhERythc1phMDdDWm1LL1Q0NGZoUWdhdnp3eG9ZMEw1N0RKYmtJUFk3WjFsUlJIL1E2UmlBS2FzQUR2THVRNzBRQzRzWEFRa2x3SlFJREFRQUI=","claims_namespace": "hasura","claims_format": "json"}'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
```

Producing:

> Fatal Error:- Environment variable HASURA_GRAPHQL_JWT_SECRET: Error in $: Invalid JWK: Could not decode PEM: No pem found No pem found

I´m not sure why it is expecting a PEM key anyway, although it seems to be an optionality.

However I´ve tried the same with our PEM key as well which leads to the same error.

It is unclear to me what´s the issue.

The solution of @jakobrosenberg  to convert it to XML and back to PEM with the converter provided is meaningless, as the result is the same in my case.

I would appreciate any help / clarification with this issue. Thanks in advance
