### ISSUE TITLE
down migrations generated for delete event trigger needs to be updated

### ISSUE THREAD

**Issue by praveenweb** [hasura/graphql-engine#1390]
Previously the console generated down migrations with the following format.

```
- args:                                                                                           
   name: <name>                                                                                  
   table:
     name: <name>                                                                                 
     schema: <schema>                                                                                                                                                                                   
  type: create_event_trigger
```

Now additonally headers and column metadata functionalities were added but that is not reflected in the down migrations that are generated.

Between the delete button click and the next page navigation there is also a 404 that appears and goes away.
