### ISSUE TITLE
How to access pgAdmin of my docker-compose

### ISSUE THREAD

**Issue by mnlbox** [hasura/graphql-engine#1424]
Hi guys,
I want connect to Hasura database admin ui (pgAdmin).
Can you guide me how to access pgAdmin of my docker-compose?
Which type of docker-compose modification required for this?

**Comment by ilovelll** [comment]
You can add a pgAdmin service to your compose file. Like that:
```
  pgadmin:
    image: fenglc/pgadmin4
    container_name: pgadmin
    env_file:
      - ./env
    depends_on:
      - postgres
    ports:
      - 5050:5050
    networks:
      postgres:
```
