### ISSUE TITLE
Add and document how to do health checks on Hasura

### ISSUE THREAD

**Issue by patcito** [hasura/graphql-engine#1532]
Services such as Kubernetes ingress force you to do health checks on hasura, this is usually through a GET request executed every 60 seconds on <YOUR_HASURA_HOST>/. If the health check returns a negative (which it does with Hasura on /), Kubernetes considers your service to be down even though it's actually running which may be confusing as Hasura doesn't report much in its logs (except for the 404 to / which is not super obvious), it's something that has to do with Kubernetes.

Right now, you can configure Kubernetes to do an http GET to <YOUR_HASURA_HOST>/v1/version but this may be going away and doing a TCP probe on hasura servicePort is advised instead (on GKE, just select TCP instead of HTTP and select whichever port your hasura ingress node is running on, should be in your yaml spec). Hope this helps. Thanks to @shahidhk for helping me through this.

**Comment by thezjy** [comment]
@patcito Is there related docs on this? I failed to set up ingress on GKE because the health checks failed.

**Comment by thezjy** [comment]
Just tested again. On GKE, health check using `GET /v1/version` works but TCP does not work.

**Comment by plmercereau** [comment]
Hello,
I found a way to configure health checks in building a custom docker-file:
```
FROM hasura/graphql-engine:v1.0.0-alpha37
HEALTHCHECK  --interval=30s --timeout=3s CMD wget --quiet --spider http://localhost:8080/v1/version || exit 1
CMD ["graphql-engine", "serve"]
```
It works for docker swarm, I haven't tested it in Kubernetes.

I used wget instead of curl as curl is not installed in the distro Haura is based on. 

I think you can also define your health checks directly in your docker-compose file so you don't have to build a custom dockerfile.

Note that the port is hardcoded...

**Comment by plmercereau** [comment]
And of course for docker-compose:
```yaml
version: '3.4'
services:
  graphq-engine:
    image: hasura/graphql-engine:v1.0.0-alpha37
    restart: always
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--spider', 'http://localhost:8080/v1/version', '||', 'exit 1']
      interval: 30s
      timeout: 3s
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: '<admin key>'
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
  postgres:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
```

**Comment by shahidhk** [comment]
We have added a dedicated health check endpoint `/healthz` since `v1.0.0-alpha43`:

`GET /healthz` will respond with 200 if all is well and 500 if something is wrong.

Documentation is also added: https://deploy-preview-1967--hasura-docs.netlify.com/graphql/manual/api-reference/index.html#health-api (will be pushed to docs.hasura.io soon)

**Comment by pronevich** [comment]
Spent a lot of time to figure out why ECS tasks stop and what wrong with my elb to ecs setup, /helthz should be mentioned  on every hasura tutorial for containers setup )

**Comment by shahidhk** [comment]
@pronevich The API endpoint is documented in the API Reference doc: https://docs.hasura.io/1.0/graphql/manual/api-reference/index.html#health-api

We'll try to address it in more places. 

For clarification, your ECS setup was using this endpoint or was not using this endpoint?

**Comment by pronevich** [comment]
Thanks, @shahidhk. I just didn't know that it exists and needed for ELB(ALB). That's why when I was starting ECS(fargate) tasks without ALB - all works fine, but when I add load balancer - task stops with health check failing reason. Now I added /healthz to LB target group under health path and all working fine

**Comment by dvasdekis** [comment]
Hey folks! It looks like both `curl` and `wget` are missing from the current container? Neither are in `/bin` , and additionally I get:
```
docker exec -it local_env_ib-gateway9_1 wget
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"wget\": executable file not found in $PATH": unknown
docker exec -it local_env_ib-gateway9_1 curl
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"curl\": executable file not found in $PATH": unknown
```
Any idea where they've gone? They're a prerequisite for these health checks

**Comment by marcopeg** [comment]
Anybody got it work with `hasura/graphql-engine:v2.0.0-beta.1`?

There is no `wget` nor `curl` inside the container :-(

**Comment by ianschmitz** [comment]
It's easy to do if you're building your own image. For example:

```
FROM hasura/graphql-engine:v2.0.8.cli-migrations-v3

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

COPY ./metadata /hasura-metadata
COPY ./migrations /hasura-migrations

HEALTHCHECK --start-period=10s CMD curl -f http://localhost:8080/healthz || exit 1
```

**Comment by PlugFox** [comment]
I have an idea of how to do simple health checks without curl:

With that command:
```yml
    healthcheck:
      #test: curl --fail -s http://localhost:8080/healthz || exit 1
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8800' || exit 1
      interval: 30s
      timeout: 15s
      retries: 3
```

Inspired of [that article](https://medium.com/bash-tips-and-tricks/part01-tcp-udp-request-with-a-native-bash-feature-and-without-curl-wget-9dcef59c30aa)

**Comment by marcopeg** [comment]
Here is a working piece of `docker-compose.yml`:

```yml
hasura-engine:
    image: hasura/graphql-engine:v2.8.0
    restart: unless-stopped
    healthcheck:
      test: timeout 1s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 2s
      timeout: 1s
      retries: 10
```
