### ISSUE TITLE
Documentation: Max-width limiting for very wide screens.

### ISSUE THREAD

**Issue by kigiri** [hasura/graphql-engine#1955]
I use a very wide screen, and the css rules is too limiting
```css
/* _static/hasura-custom.css:86 */
[role="main"] {
  width: 90% !important;
  max-width: 800px !important;
  border: none !important;
  padding-bottom: 0 !important;
  padding-left: 15px !important;
  padding-right: 15px !important;
}
```

#### Screenshot:
![wide](https://user-images.githubusercontent.com/231748/55646103-324a7580-57d2-11e9-8303-dce83c9f01f1.png)

The menu is as big as the content and the whole page is mainly white.  
Since some of the content is wrapped horizontally it's a bit sub-optimal.
