### ISSUE TITLE
JWT Authorization Error: operator does not exist: uuid = integer

### ISSUE THREAD

**Issue by nccurry** [hasura/graphql-engine#2011]
Hasura Version: v1.0.0-alpha42

I am seeing the following error when trying to implement JWT Authorization:
```yaml
  detail: {
   detail: {
    error: {
     code:  "postgres-error"      
     error:  "postgres query error"      
     internal: {
      arguments: [0]       
      error: {
       description:  null        
       exec_status:  "FatalError"        
       hint:  "No operator matches the given name and argument types. You might need to add explicit type casts."        
       message:  "operator does not exist: uuid = integer"        
       status_code:  "42883"        
      }
      prepared:  true       
      statement:  "SELECT  coalesce(json_agg("root" ), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_1_e"  FROM  (SELECT  "_0_root.base"."created_on" AS "created_on", "_0_root.base"."owner_id" AS "owner_id", "_0_root.base"."tabletop_id" AS "tabletop_id", "_0_root.base"."tabletop_name" AS "tabletop_name", "_0_root.base"."updated_on" AS "updated_on"       ) AS "_1_e"      ) ) AS "root" FROM  (SELECT  *  FROM "dt_public"."tabletop"  WHERE ((("dt_public"."tabletop"."owner_id") = (((current_setting('hasura.user')::json->>'x-hasura-test'))::integer)) OR ((("dt_public"."tabletop"."owner_id") IS NULL) AND ((((current_setting('hasura.user')::json->>'x-hasura-test'))::integer) IS NULL)))     ) AS "_0_root.base"      ) AS "_2_root"      "       
     }
     path:  "$"      
    }
    request:  "{"query":"{\n  dt_public_tabletop {\n    created_on\n    owner_id\n    tabletop_id\n    tabletop_name\n    updated_on\n  }\n}\n","variables":null}"     
   }
```

The JWT contains the following claim:

```yaml
  "https://hasura.io/jwt/claims": {
    "x-hasura-default-role": "user",
    "X-Hasura-test": "adedb95e-47ad-43f5-b165-a9de4e406bd7",
    "x-hasura-allowed-roles": [
      "user"
    ]
  },
```

My postgresql table schema is the following:
```sql
CREATE TABLE IF NOT EXISTS dt.dt_public.tabletop
(
  tabletop_id   uuid DEFAULT gen_random_uuid(),
  tabletop_name VARCHAR(50) NOT NULL,
  owner_id      uuid         NOT NULL
    REFERENCES dt.dt_public.user (user_id)
      ON DELETE CASCADE,
  created_on    TIMESTAMP   NOT NULL,
  updated_on    TIMESTAMP   NOT NULL,
  PRIMARY KEY (tabletop_id)
);
```

I am trying to create a permissions that checks the incoming X-Hasura-test claim against the postgresql column owner_id which is of type uuid.

![image](https://user-images.githubusercontent.com/3799024/56158545-ed6bcf00-5f87-11e9-9334-2c8c893c9988.png)

It appears that Hasura is casting the JWT claim as an integer instead of a string?
```
(((current_setting('hasura.user')::json->>'x-hasura-test'))::integer)
```

I am seeing this issue regardless of the key for the JWT claim
i.e. X-Hasura-User-Id, X-Hasura-User-Uuid, X-Hasura-test, etc
