### ISSUE TITLE
Hasura fails behind nginx_openid

### ISSUE THREAD

**Issue by thebetterjort** [hasura/graphql-engine#2082]
Proxy lets me hit hasura on port 8546, but when I try and enter my admin key, I get a return from window.alert of "localhost:8546 says {}" 

I expect it to say localhost:8080 says.... 

"Hasura console is not able to reach your Hasura GraphQL engine instance. Please ensure that your instance is running and the endpoint is configured correctly."

How would I tell hasura of the new endpoint?

nginx_openid_1     | 172.23.0.1 - - [26/Apr/2019:20:10:51 +0000] "POST /v1/query HTTP/1.1" 302 167 "http://localhost:8546/console/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3683.86 Chrome/73.0.3683.86 Safari/537.36"

```
  nginx_openid:
    image: "evry/oidc-proxy"
    environment: 
      OID_DISCOVERY: http://keycloak:8080/auth/realms/master/.well-known/openid-configuration
      OID_CLIENT_ID: fathom
      OID_CLIENT_SECRET: secreykeyishere
      PROXY_HOST: graphql-engine
      PROXY_PORT: "8080"
      PROXY_PROTOCOL: http
      OID_SESSION_CHECK_SSI: "off"
      OID_SESSION_NAME: oidc_auth
    ports:
     - "8546:80"
    networks:
      fathom_network:


  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha38
    ports:
      - "9092:8080"
    depends_on:
      - "postgres_fathom"
      - "auth"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_fathom:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false" # https://docs.hasura.io/1.0/graphql/manual/guides/telemetry.html
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: mysecretaccesskey
      HASURA_GRAPHQL_AUTH_HOOK: http://auth:3000
      #HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
    networks:
      fathom_network:


  fathom:
    image: usefathom/fathom:latest
    command: ./fathom --config=/config/.env server
    depends_on:
      - postgres_fathom
    volumes:
      - ./fathom.env:/config/.env
    ports:
      - "8080/tcp"
    networks:
      fathom_network:
```
