### ISSUE TITLE
"ERROR: manifest for hasura/graphql-engine:v1.0.0-beta.01 not found" after updating from last alpha

### ISSUE THREAD

**Issue by barbalex** [hasura/graphql-engine#2217]
I updated by replacing the image name in the docker file. My docker file (docker-compose.yaml) now looks like this:

```
version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.01
    restart: always
    environment:
      # database url to connect
      HASURA_GRAPHQL_DATABASE_URL: postgres://secret@dburl/defaultdb?sslmode=require
      # enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set "false" to disable console
      ## uncomment next line to set an admin secret key
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\secret
    command:
    - graphql-engine
    - serve
  caddy:
    image: abiosoft/caddy:0.11.0
    depends_on:
    - "graphql-engine"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - caddy_certs:/root/.caddy
volumes:
  db_data:
  caddy_certs:

```

Now I get `ERROR: manifest for hasura/graphql-engine:v1.0.0-beta.01 not found` when running `sudo docker-compose up -d`
