### ISSUE TITLE
docs: document use of self-signed ssl certificates (for auth webhook, remote schema, event triggers)

### ISSUE THREAD

**Issue by marcpar** [hasura/graphql-engine#2553]
I'm having this issue using GET webhook authentication

message:  "InternalException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa)))"

**UPDATE** (since 2.0.8):

If you don't want to mount the CAs, you can disable CA verification through the new TLS Allowlist feature:

![Screen Shot 2021-10-11 at 12 03 51 PM](https://user-images.githubusercontent.com/8663570/136743735-78785118-c285-4580-906c-51b9c7c547e3.png)

**Comment by marionschleifer** [comment]
@marcpar can you give us some more information for us to understand what the problem might be? For example the full request that you're sending, as well as logs.
In the meantime, please check out the webhook authentication docs here: https://docs.hasura.io/1.0/graphql/manual/auth/authentication/webhook.html if you haven't already done so 🙂

**Comment by marionschleifer** [comment]
@marcpar any updates on this?

**Comment by marcpar** [comment]
Sorry for the late reply I'm still investigating this issue I think its a package ca-certificate

**Comment by marcpar** [comment]
do we need to add the private cert inside the hasura pod in kubernetes?

**Comment by shahidhk** [comment]
@marcpar Is the webhook using a self-signed cert issued by a private ca?

**Comment by vikastomar5983** [comment]
I am getting same error when starting Hasura with  `-e HASURA_GRAPHQL_JWT_SECRET='{"type":"RS512","jwk_url": "**https**://oauth.xxxx:xxxx/oauth/token_keyset"}'`

the webhook is using self signed cert. How to start Hasura with somehting like - `javax.net.ssl.trustStore=cacerts`

**Comment by ecthiender** [comment]
This is because the current HTTP client used by GraphQL engine only relies on the trusted CAs that are in the system keystore.

**Comment by vikastomar5983** [comment]
@ecthiender system keystore? You mean inside the hasura - image? Is there a way to modify or use something like javax.net.ssl.trustStore=cacertPath to resolve this?

**Comment by ecthiender** [comment]
@vikastomar5983 right now there is no way. We have add support for it in the server code and update docker image. Even if you mount it inside the docker image, the HTTP client does not respect that.

**Comment by 0x777** [comment]
@vikastomar5983 You can mount the `.crt` file in `/etc/ssl/certs` directory. The tls manager that we use adds all `.crt` files under `/etc/ssl/certs` into its certificate store.

**Comment by apnerve** [comment]
I'm facing similar issue. This is my setup

- Hasura graphQL engine running on port 8080 in a container
- Nginx (listenin to 443, proxied to 8080), SSL by Letencrypt managed using certbot

When I use an https endpoint, hosted on zeit now, as webhook, it works. But when I use another https endpoint hosted on EC2 and SSL certificate by Letsencrypt, it gives "certificate has unknown CA" error

The weird thing is that even zeit uses Letsencrypt for SSL but works fine there

**Comment by apnerve** [comment]
Used certbot for SSL again and it works fine now. The issue wasn't at the hasura end but how the SSL cert were configured.

**Comment by honeycruse** [comment]
I am using `docker-compose.yaml` for development, bind cert file to `/etc/ssl/certs/`:
```
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    volumes:
    - type: bind
      source: /YOUR_ROOT_CERT_FILE_DIRECTORY/ca.crt
      target: /etc/ssl/certs/selfsigned.crt
      read_only: true
    restart: always
    environment:
      http_proxy: ""
      https_proxy: ""
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:

```

**Comment by dsandip** [comment]
Note: Can also refresh the cert from a URL when it expires.

**Comment by ceck95** [comment]
hi @tirumaraiselvan i tested on remote schema but it didnt work, you can guide me about this

**Comment by mfizia** [comment]
The easiest way is to mount the ssl certs. Im my case i needed the whole ca-chain to get it working. @cerk95

The mounting of self-signed certs should be documented, somewhere.

**Comment by ceck95** [comment]
@mfizia  im mounted look like that 
![image](https://user-images.githubusercontent.com/9115256/167388185-d2e28d9b-bf7a-4294-b81b-61dda6c6e5b6.png)
actually result still not resole it

**Comment by SysPush** [comment]
Hello,

I am also having the issue with GET webhook authentication.

 "message": "InternalException (HandshakeFailed (Error_Protocol (\"certificate has unknown CA\",True,UnknownCa)))",

I have tried the steps listed in this thread by  placing the .crt into /etc/ssl/certs. Maybe I am getting the certificates placement wrong.

My webhook's host is https://abc.company.com

Do I place my webhook's host's signed certificate into /etc/ssl/certs? Or do I need a signed certificate for Hasura GraphQL?

**Comment by mfizia** [comment]
> The easiest way is to mount the ssl certs. Im my case i needed the whole ca-chain to get it working. The mounting of self-signed certs should be documented, somewhere.

I would like to share a frame of my k8s-configuration. Before you start, chain all ca's together and encode the content of this chain-ca to base64. I placed the base64 string as a secret in my k8s-configuration. Then i mount the chain-ca as a volume and copy the file to the hasura container: `cp /certs/companyca.crt /etc/ssl/certs/companyca.crt`

And that's the trick.

```
apiVersion: v1
kind: Service
metadata:
  name: hasura
  namespace: my-namespace
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: hasura
    level: live
---
apiVersion: v1
data:
  companyca.crt: >-  X...X
kind: Secret
metadata:
  name: companyca
  namespace: my-namespace
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    moniker.spinnaker.io/detail: backend
    moniker.spinnaker.io/stack: live
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: hasura-ingress
  namespace: my-namespace
spec:
  rules:
    - host: my.company.com
      http:
        paths:
          - backend:
              service:
                name: hasura
                port:
                  number: 8080
            path: /my-namespace/hasura(/|$)(.*)
            pathType: ImplementationSpecific
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    moniker.spinnaker.io/detail: backend
    moniker.spinnaker.io/stack: live
  labels:
    app: hasura
    level: live
  name: hasura
  namespace: my-namespace
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: hasura
      level: live
  template:
    metadata:
      labels:
        app: hasura
        level: live
    spec:
      containers:
        - env:
            [...some other envars...]
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: 'true'
            - name: HASURA_GRAPHQL_DEV_MODE
              value: 'true'
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              value: '123'
            - name: HASURA_GRAPHQL_METADATA_DATABASE_URL
              value: >-
                postgres://...metadatabase-uri...
            - name: MY_DATABASE_URL
              value: >-
                postgres://...my-database-uri...
          image: >-
            hasura/graphql-engine:v...hasrua-container-version...
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - cp /certs/companyca.crt /etc/ssl/certs/companyca.crt
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            tcpSocket:
              port: app-port
          name: hasura
          ports:
            - containerPort: 8080
              name: app-port
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            tcpSocket:
              port: app-port
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - mountPath: /certs
              name: certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: companyca
```
