### ISSUE TITLE
Cannot Create Migration

### ISSUE THREAD

**Issue by hynra** [hasura/graphql-engine#2633]
Versions:

  * Hasura GraphQL version:  v1.0.0-beta.2 using docker

  * CLI Version: v1.0.0-beta.2

  * OS Windwos 10

Steps to reproduce:

  * Set console to `false`

  * Launch console with `hasura.exe console` worked and no errors or warning found.

  *  I've migrated several times before, using CLI with the command `hasura.exe migrate create "migrate_name" --from-server` and generated both `.yaml` and `.sql` file.

  * I've tried migration again after some addition and changes it's getting failed with reason: 
```
cannot fetch schema dump: invalid character '<' looking for beginning of value
``` 

with the result only generated `.yaml` file. I don't know what changes have caused this situation because there are too many additions and changes made and so far no errors have been found when the client making the request (`query`, `mutation` even `sub`). So I assume it's work perfectly.

**Comment by hgiasac** [comment]
Hi @hynra

Can you check if endpoint config is correct? Did you add `--endpoint` args if you need to do migration on remote host?

Regards

**Comment by hynra** [comment]
Hi @hgiasac , like I describe above I've created migration several times and it worked. 

here my config:

```yaml
admin_secret: my_secret
endpoint: https://my-graphql-server-address
```

with this config I alos run `hasura console` and has no error.

**Comment by hynra** [comment]
Here the image:
<img width="855" alt="hasura" src="https://user-images.githubusercontent.com/3982650/62101989-78679f80-b2c1-11e9-9b81-45e02e0f80be.PNG">

I follow migration steps from here: https://docs.hasura.io/1.0/graphql/manual/migrations/existing-database.html#step-3-initialize-the-migrations-as-per-your-current-state

**Comment by hynra** [comment]
any update on this?

**Comment by hynra** [comment]
I just realized this error:
```
cannot fetch schema dump: invalid character '<' looking for beginning of value

```

the character `<` is coming from `pg_dump` process and caused error. I run `pg_dump` api via 

```
POST -> graphql_engine_url/v1alpha1/pg_dump
```

and got error:

```html
<HTML>

<HEAD>
	<TITLE>Network Error</TITLE>
</HEAD>

<BODY>
	<FONT face="Helvetica">
		<big><strong></strong></big><BR>
</FONT>
		<blockquote>
			<TABLE border=0 cellPadding=1 width="80%">
				<TR>
					<TD>
						<FONT face="Helvetica">
							<big>Network Error (tcp_error)</big>
							<BR>
							<BR>
</FONT>
					</TD>
				</TR>
				<TR>
					<TD>
						<FONT face="Helvetica">
							A communication error occurred: "Operation timed out"
						</FONT>
					</TD>
				</TR>
				<TR>
					<TD>
						<FONT face="Helvetica">
							The Web Server may be down, too busy, or experiencing other problems preventing it from
							responding to requests. You may wish to try again at a later time.
						</FONT>
					</TD>
				</TR>
				<TR>
					<TD>
						<FONT face="Helvetica" SIZE=2>
							<BR>
For assistance, contact your network support team.
</FONT>
					</TD>
				</TR>
			</TABLE>
		</blockquote>
	</FONT>
</BODY>

</HTML>
```

Is this related to this issue?

**Comment by hgiasac** [comment]
Hi @hynra, sorry for late reply. Did you resolve this issue?
I think it need to troubleshoot further steps to know the root cause:

- Is GraphQL Engine behind some reverse proxy such as nginx, apache... and there is some redirect rule, custom header configs. If yes, try do run backup on internal endpoint
- If you got sql file, try to run it on Postgres directly to see if the error is same with graphql engine. 
- Upgrade hasura cli to beta 4 version and run backup again
- Do it on linux or Mac
 
Regards

**Comment by hynra** [comment]
I solved this issue by running migration on the remote server and exclude `caddy` from `docker-compose.yaml`. We running Hasura on an existing database with a monolith architecture, we have like 80+ tables and thousands of data. When I run a manual migration, It's like take sometimes that `Caddy` rules cannot handle that (timeout or something).

This is my `docker-compose` based on Hasura doc in previous version:

```
version: '3.6'
services:
  postgres:
    image: postgres:10.5
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.4
    depends_on:
    - "postgres"
    restart: always
    environment: 
      HASURA_GRAPHQL_DATABASE_URL: postgresql://postgres:blah
      # enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set "false" to disable console
      ## uncomment next line to set an admin secret key
      # this is comment
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_ADMIN_SECRET: adminsecret
    command:
    - graphql-engine 
    - serve
  caddy:
    image: abiosoft/caddy:0.11.0
    depends_on:
    - "graphql-engine"
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - caddy_certs:/root/.caddy
volumes:
  db_data:
  caddy_certs:
```

So, I updated with `v1.0.0-beta.4` and realized that in [Install Manifest](https://raw.githubusercontent.com/hasura/graphql-engine/master/install-manifests/docker-compose/docker-compose.yaml) there is no `Caddy` anymore
