### ISSUE TITLE
Suggestion on the YAML format of migration

### ISSUE THREAD

**Issue by Albert-Gao** [hasura/graphql-engine#2692]
Thanks for the great work.
I want to achieve something like code-driven dev. YAML is a pretty good start, but a tweak on the generated format would be good.

1. Structure: make `table` the direct children instead of `array_relationships`
![image](https://user-images.githubusercontent.com/18282328/62704730-2866a680-ba40-11e9-87a8-b08e13771355.png)

It would be much better if we can see something like:

tables
- table 1
- table 2

It may make it easier to grok.

2. Make it match what we see in the GUI
For example, 
for a key in GUI:
![image](https://user-images.githubusercontent.com/18282328/62705106-e5f19980-ba40-11e9-8608-622563f81f22.png)
it becomes:
![image](https://user-images.githubusercontent.com/18282328/62704971-b2167400-ba40-11e9-9d85-1e8d4ecd0902.png)
it would be better if it is something like
![image](https://user-images.githubusercontent.com/18282328/62705351-54365c00-ba41-11e9-8071-72da1e73b401.png)

3. idealy, it could be much better if it is straightforward as

```yaml
tables
  user_table
    object_relationships:
      name: user
      from: creator_id
      to: users.id
    permission:
      # this part needs more think,
      # because it has 2 dimesions, either role based or CRUD based
```

4. if we can add another abstraction here with the column definition, that would be much better
so we can just use this yaml file to do all the table design.

5. Just think JSON is better in terms of readability, but that is just my idea.

6. File could be bloated if everything is here, so should have some idea to decouple one table per file.

It should enable a very rapid dev cycle.

Thanks!
