### ISSUE TITLE
Redirect Behavior Unexpected Using Digital Ocean with Caddy

### ISSUE THREAD

**Issue by mwood23** [hasura/graphql-engine#2743]
# Description

For my web app, I want to be able to create a reverse proxy and place all of Hasura behind `api` instead of the root of my domain (since that's where my app is served from). When I followed the [docs](https://docs.hasura.io/1.0/graphql/manual/guides/deployment/digital-ocean-one-click.html#adding-a-domain-enabling-https), I couldn't get it to work from `/api`.

## Recreation Steps
**My Caddy config**
```
my-domain.com {
    proxy /api graphql-engine:8080 {
        websocket
    }
}
```

**Result**
`{"path":"$","error":"resource does not exist","code":"not-found"}`

After talking in the chat, all you have to do is add without `/api` after `websocket` leaving you this:

```
my-domain.com {
    proxy /api graphql-engine:8080 {
        websocket
        without /api
    }
}
```

This should give you access to the console at `my-domain.com/api/console`. However, if you go to `my-domain.com/api`, it redirects you to  `my-domain.com/console`. If you add a trailing slash (`my-domain.com/api`), it redirects as expected.

**Comment by shahidhk** [comment]
This is a confirmed behaviour, which is not ideal.

We should issue the right redirect irrespective of the trailing slash.

**Comment by kevinmarrec** [comment]
@marionschleifer Seems the task have been assigned multiple times to someone different but no updates ?

It seems this issue also affect Kubernetes when using an Ingress Controller and specifying we want Hasura on a specific path :

```yml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /custom
        backend:
          serviceName: hasura
          servicePort: 8080
```

`example.com/custom` leads to `{"path":"$","error":"resource does not exist","code":"not-found"}`

**Comment by gunar** [comment]
Me too!I'd like to have Hasura live under a different URL path as well. Although, to be honest, I know this is something quite specific and I'd totally understand if this feature is never implemented.

Here's my scenario:
- Reverse proxy (e.g. api gateway) points `customdomain.com/console` to `hasura/`
- Going to `customdomain.com/console` gets me an infinite redirect
- Going to `customdomain.com/console/` gets me to `customdomain.com/console/console` (and shows the console)
- Going to `customdomain.com/console/` takes me to`customdomain.com/console/console` (and shows the console)
- The console, when displayed, isn't working because the console is pointing GraphiQL to `customdomain.com/console/v1/graphql` (but it should be pointing to `customdomain.com/console/console/v1/graphql`).

The specific scenario above is irrelevant. What matters is that it would be solved by having a server flag that tells Hasura under which url path it is being served. Anyway, the solution specific to AWS API Gateway is to use route type `http` instead of `http_proxy`—my immediate problem is solved. May this help someone.

**Comment by jkaliaSignify** [comment]
I would like to know if there any solutions to this?

**Comment by jkaliaSignify** [comment]
@kevinmarrec did you figure anything out to get this working? please guide 😄

**Comment by AhyaanTech** [comment]
So i dunno about caddy but with ingress we have to use regex for path re-writing.

Sample yaml for ingress

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testops
  labels:
    name: testops
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: my-website.com
    http:
      paths:
      - pathType: Prefix
        path: /address/(.+)
        backend:
          service:
            name: graphql-engine
            port: 
              number: 9000        
```

**Comment by jkaliaSignify** [comment]
Dunno about caddy but in nginx ingress we have to use regex for path re-writes

sample yaml
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testops
  labels:
    name: testops
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: testops.qa.signifyhealth.com
    http:
      paths:
      - pathType: Prefix
        path: /address/(.+)
        backend:
          service:
            name: graphql-engine
            port: 
              number: 9000        
```
