### ISSUE TITLE
In docker-compose with postgres, CPU jumping between 24% - 54% on mac

### ISSUE THREAD

**Issue by michaelhayman** [hasura/graphql-engine#2748]
I have a weird problem - if I use hasura + postgres together in docker-compose on my local machine (Mac Mojave), postgres spikes CPU between 6% - 54%, my fans kick in to their highest setting and my laptop gets hot and the computer starts to stutter.  docker desktop for mac in activity monitor also displays a spiked CPU usage (70-80%).

I don't remember this being a problem before.

Some logs:

Just after launching and idle (it continues like this for hours, it's not just on startup):
<img width="1572" alt="high 2 - 10 seconds after launching" src="https://user-images.githubusercontent.com/1134239/63223140-3942b500-c1c2-11e9-8650-91160eaccc8c.png">

Very high block IO (after about an hour of usage I think)  - this increases by 200 MB a *second*, and is 20 GB within 2 minutes (that being said I have no idea what it means :)):
<img width="1557" alt="crazy block io" src="https://user-images.githubusercontent.com/1134239/63223141-3d6ed280-c1c2-11e9-9d74-38ad40a142a7.png">

Postgres on its own locally without Hasura displays normal CPU usage:
<img width="1563" alt="postgres without hasura" src="https://user-images.githubusercontent.com/1134239/63223145-4790d100-c1c2-11e9-82ad-c2f7569b7f0d.png">

I have a test instance running at digitalocean with the exact same setup, and it displays normal CPU usage when idle:
<img width="1598" alt="staging" src="https://user-images.githubusercontent.com/1134239/63223142-41025980-c1c2-11e9-8a84-173ede8e7ad4.png">

Can someone help me dig into logs and diagnose what's happening?  Could it be because of Postgres 11.4?  But the staging site is running the same version.

My pretty basic docker-compose.yml:

```
version: '3'

services:
  postgres:
    image: postgres:11.4
    restart: always
    volumes:
    - hustle_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    command: postgres -c max_locks_per_transaction=2000
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.4.cli-migrations
    depends_on:
    - postgres
    ports:
    - "${HASURA_PORT}:${HASURA_PORT}"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "${SECRET}"}'
      VIRTUAL_HOST: ${HASURA_HOST}
      VIRTUAL_PORT: ${HASURA_PORT}
      LETSENCRYPT_HOST: ${HASURA_HOST}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      NODE_SCHEMA_URL: ${NODE_SCHEMA_URL}
      HOOKS_URL: ${HOOKS_URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      HASURA_GRAPHQL_ACCESS_KEY: ${HASURA_GRAPHQL_ACCESS_KEY}
    volumes:
    - ./migrations:/hasura-migrations
    command:
    - graphql-engine
    - serve
volumes:
  hustle_db_data:
  migrations:
networks:
  default:
    external:
      name: nginx-proxy
```
