### ISSUE TITLE
A metadata error during migrate apply can cause inconsistent migration state

### ISSUE THREAD

**Issue by kevboh** [hasura/graphql-engine#2890]
For sql+yaml migrations, if the sql step succeeds but the yaml step fails, hasura seems to think your migration has been applied even though your metadata was not.

Specifically, I was able to reliably get into this state by

1. running `hasura migrate create some-migration`
2. adding a valid sql file to that migration
3. putting valid-but-erroring yaml in that migration. In my case this was a create_array_relationship on a table that didn't exist:

```
- type: create_array_relationship
  args:
    comment: Demo of issue
    name: problematic
    table:
      schema: idontexist
      name: idontexist
    using:
# more here
```

It's not clear to me if the issue is that my table descriptor is bad, or if any missing data in create_array_relationship will cause the issue.

After running `hasura migrate apply`, you'll get a fatal error:

```
FATA[0000] apply failed: [not-exists] table "idontexist.idontexist" does not exist ($.args[2].args)
```

but your migration will appear applied:

```
> hasura migrate apply
Applying migrations...◐ INFO nothing to apply
INFO migrations applied
```
