### ISSUE TITLE
Hasura Docker Issues 

### ISSUE THREAD

**Issue by sebastianmacias** [hasura/graphql-engine#290]
I followed the docker-compose [getting started guide](https://docs.hasura.io/1.0/graphql/manual/deployment/docker/index.html). Everything works as expected. However I have a couple of questions:

- How can I use the [Hasura CLI ](https://docs.hasura.io/1.0/graphql/manual/hasura-cli/index.html) with the official docker-compose setup? 
- How can I add the access key using docker-compose? 
I tried adding *--access-key mysecretkey* to the graphql-engine command 

```yaml
version: '3.6'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha13
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
    command:
      - graphql-engine
      - serve
      - --enable-console
      - --access-key mysecretkey
volumes:
  ? db_data

```

However I'm getting the following error with dcoker-compose up:

```bash
graphql-engine_1  | Invalid option `--access-key mysecretkey'
graphql-engine_1  | 
graphql-engine_1  | Usage: graphql-engine [--host HOST] [-p|--port PORT] [-u|--user USER]
graphql-engine_1  |                       [-p|--password PASSWORD] [--database-url DATABASE-URL]
graphql-engine_1  |                       [-d|--dbname NAME] COMMAND

```

Thanks in advance

**Comment by karthikvt26** [comment]
Hi @sebastianmacias, 

Could you place add a `=` as follows and try doing `docker-compose up -d`
```
- --access-key=mysecretkey
```

Let me know if you still face any issue

**Comment by shahidhk** [comment]
@sebastianmacias Easiest way to add access key is to set an environment variable:

```yaml
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ACCESS_KEY: yoursecretaccesskey
    command:
      - graphql-engine
      - serve
      - --enable-console
```
