### ISSUE TITLE
Error on moving related tables to another schema in one single run_sql query

### ISSUE THREAD

**Issue by nizar-m** [hasura/graphql-engine#3059]
Consider the following setup of tables 
```sql
create table foo (id serial primary key);

create table bar (
   id serial primary key,
   foo_id integer references foo (id)
);
````
with object foreign key relationship `foo` defined on table `bar` with column `foo_id`, and array foreign key relationship `bars` on table `foo` with the same foreign key.
The following run_sql query
```yaml
type: run_sql
args:
   sql: |
      create schema hge;
      alter table foo set schema hge;
      alter table bar set schema hge;
```
fails with error
```yaml
statement: | 
  SELECT rel_def::json FROM hdb_catalog.hdb_relationship
   WHERE table_schema = $1 AND table_name = $2
     AND rel_name = $3
prepared: true
error: Rows returned != 1
arguments:
- (Oid 25,Just ("public",Binary))
- (Oid 25,Just ("foo",Binary))
- (Oid 25,Just ("bars",Binary))
```

```
