### ISSUE TITLE
Can't create one-to-many relationship with multiple primary keys

### ISSUE THREAD

**Issue by barlock** [hasura/graphql-engine#3308]
I'm trying to map Slack data into hasura.

Slack `messages` are identified by `ts` and `conversation_id`

Slack `messages` have `replies` which are other `messages`

One `message` can have many `replies`
One `reply` can have one `message` as a root

This is all expressed via a `thread_ts`.

If you set a `thread_ts` it will give you `postgres-error : insert or update on table "message" violates foreign key constraint "message_conversation_id_thread_ts_fkey"`

if you try to set a `root` as a nested object, you get `[{'extensions': {'path': '$.selectionSet.insert_slack_message.args.objects[32].root', 'code': 'validation-failed'}, 'message': 'cannot insert object relation ship "root" as "conversation_id" column values are already determined'}]`

The root insert being:

```
    "root": {
        "data": { "ts": "1521120859.000584", "conversation_id": "C0D3QELVA" },
        "on_conflict": {
          "constraint": "message_pkey",
          "update_columns": ["ts", "conversation_id"]
        }
      }
```

**Comment by barlock** [comment]
I tried creating a manual array relationship without setting up a foreign key, it seems to almost work? I'm not sure if I'm doing something wrong, I don't have all of the data, or I configured it wrong.

Querying on `root`s gives me incomplete threads. It's also quite slow which I imagine is a function of views not being indexed as well as foreign key relationships? 

![image](https://user-images.githubusercontent.com/5770007/68251208-a19a7900-fff0-11e9-91f7-dc06ce5b2c32.png)

**Comment by rikinsk** [comment]
@barlock Can you share the exact structure of your message table along with the foreign key definitions. I couldn't derive one easily based on the current provided information.
Also some insight on the eventual query you are trying to achieve will also be helpful.

This feels like it might be an issue with the way data is modelled.

**Comment by marionschleifer** [comment]
@barlock were you able to solve the issue? If yes, could you please close it? 🙂

**Comment by barlock** [comment]
I worked around it the way I described but I still think it's probably a bug. I forgot about making a minimal example 😅. Thanks for the bump.

**Comment by barlock** [comment]
Example Mutation (This fails)
```graphql
mutation Insert {
  insert_messages(objects: {root: {data: {root: {data: {ts: "1521120859.000584", conversation_id: "C0D3QELVA"}}}}, conversation_id: "C0D3QELVA", ts: "1521120859.000583"}) {
    affected_rows
  }
}
```

What I'm eventually trying to query
```
query Messages(
    $limit: Int, 
    $offset: Int, 
    $where: slack_message_bool_exp = {}
) {
    message(
        where: $where, 
        limit: $limit, 
        offset: $offset,
        order_by: {ts: desc}
    ) {
        ts
        conversation_id
    	replies(order_by: {ts: asc}) {
          ts
        }
    }
}
```

<details>
<summary>up.sql</summary>

```sql
CREATE TABLE public.messages (
    ts text NOT NULL,
    thread_ts text,
    conversation_id text NOT NULL
);
ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (ts, conversation_id);
ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_conversation_id_thread_ts_fkey FOREIGN KEY (conversation_id, thread_ts) REFERENCES public.messages(conversation_id, ts) ON UPDATE RESTRICT ON DELETE RESTRICT;
```

</details>


<details>
<summary>up.yaml</summary>

```
- args:
    allowlist: []
    functions: []
    query_collections: []
    remote_schemas: []
    tables:
    - array_relationships:
      - comment: null
        name: replies
        using:
          manual_configuration:
            column_mapping:
              conversation_id: conversation_id
              ts: thread_ts
            remote_table: messages
      configuration:
        custom_column_names: {}
        custom_root_fields:
          delete: null
          insert: null
          select: null
          select_aggregate: null
          select_by_pk: null
          update: null
      delete_permissions: []
      event_triggers: []
      insert_permissions: []
      is_enum: false
      object_relationships:
      - comment: null
        name: root
        using:
          manual_configuration:
            column_mapping:
              conversation_id: conversation_id
              thread_ts: ts
            remote_table: messages
      select_permissions: []
      table: messages
      update_permissions: []
  type: replace_metadata
```

</details>
