### ISSUE TITLE
CURL and WGET missing from current container

### ISSUE THREAD

**Issue by dvasdekis** [hasura/graphql-engine#3371]
Hey folks. It looks like both `curl` and `wget` are missing from the current container? Neither are in `/bin` , and additionally I get:
```
docker exec -it local_env_ib-gateway9_1 wget
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"wget\": executable file not found in $PATH": unknown
docker exec -it local_env_ib-gateway9_1 curl
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"curl\": executable file not found in $PATH": unknown
```
Any idea where they've gone? They're a prerequisite for the [health checks described here](https://github.com/hasura/graphql-engine/issues/1532).

**Comment by shahidhk** [comment]
@dvasdekis Health checks are typically done from outside the container. We do not package curl or wget in the interest of keeping the image size lean.

Can you give more hints on your use case?

**Comment by lexi-lambda** [comment]
My guess is that @dvasdekis is interested in using the Docker built-in [`HEALTHCHECK` feature](https://docs.docker.com/engine/reference/builder/#healthcheck), which unfortunately only supports running commands inside the container.

That said, I’m not actually that familiar with `HEALTHCHECK`, since in all deployments of Docker I’ve used, the load balancer had some external mechanism for checking health, as you allude to. I don’t know what systems actually consume the built-in `HEALTHCHECK` information (maybe Docker Swarm…?), so I’d also like to know more details about the use case.

**Comment by dvasdekis** [comment]
Correct @lexi-lambda - I'm personally using Docker-Compose, and in order to bring the containers up in the right order and ensure maintainability, the container has to be able to run a command that reports its health. In my case, I want this healthcheck to only be successful after the migrations have finished running. A command might be `curl -H "content-type: application/json" -X POST --data 'query { tbl_myschema_version { version_id } }' http://localhost:8080/v1/graphql || exit 1`, where tbl_myschema_version is written to as the last step in the migrations process.

**Comment by shahidhk** [comment]
Looks like docker-compose recommends running a command inside the container to do health checks [[ref](https://docs.docker.com/compose/compose-file/#healthcheck)].

@dvasdekis I just checked the latest image and `wget` seems to be present at `/bin/wget`.

What version are you on?

**Comment by dvasdekis** [comment]
I see it too now. I must have been on an old version. I'm so sorry, not sure why it didn't appear when I looked in the container I was running!
Thank you!!

**Comment by dvasdekis** [comment]
For those looking to use `wget` to perform GraphQL requests, the syntax is:
`wget --header 'content-type: application/json' --post-data='{ "query": "{ tbl_myschema_version  { version_id } }" }'`.

**Comment by Toub** [comment]
For those interested, you can also use hasura `/healthz` api as docker healthcheck:

```yml
    healthcheck:
      test:  wget --no-verbose --tries=1 --spider http://0.0.0.0:8080/healthz || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
```

Related links:
- https://hasura.io/docs/1.0/graphql/core/api-reference/health.html
- https://stackoverflow.com/a/47722899/1097926

**Comment by psrcek** [comment]
curl and wget also seem to be missing in `v2.0.0-alpha.2`
![image](https://user-images.githubusercontent.com/13370323/109792496-dd107c00-7c13-11eb-8aaf-e1b22a0f8b2e.png)

Is there another way of doing health checks in docker compose? Relying on containers having curl available seems kind of dumb...

**Comment by psrcek** [comment]
If anyone is still wanting to do hasura healthchecks with docker-compose, I've found an alternate solution using bash and commands that are available pretty much anywhere:

```yaml
healthcheck:
  test: ["CMD", "bash", "-c", "exec 5<>/dev/tcp/127.0.0.1/8080 && echo -e 'GET /healthz HTTP/1.1\n\n' >&5 && cat <&5 | head -n 1 | grep 200"]
  interval: 5s
  timeout: 5s
  retries: 3
```

**Comment by martin-hasura** [comment]
Slightly more intensive, but I've seen this done as well.
Pretty much adding curl during the first healthcheck without having to use a custom dockerfile. Going to have a slight amount of overhead on each check though.

```
healthcheck:
  test: ["CMD-SHELL", "apt-get update -y && apt-get install -y curl && curl --fail http://localhost:8080/healthz || exit 1"]
  interval: 5s
  timeout: 3s
  retries: 5
```

**Comment by m-rgba** [comment]
Slightly more intensive, but I've seen this done as well.
Pretty much adding curl during the first healthcheck without having to use a custom dockerfile. Going to have a slight amount of overhead on each check though.

```
healthcheck:
  test: ["CMD-SHELL", "apt-get update -y && apt-get install -y curl && curl --fail http://localhost:8080/healthz || exit 1"]
  interval: 5s
  timeout: 3s
  retries: 5
```
