### ISSUE TITLE
Feature Request: Allow custom scalar types to be configured for jsonb fields

### ISSUE THREAD

**Issue by ahrnee** [hasura/graphql-engine#3451]
**Desired Outcome/Functionality**
When using jsonb fields to store json data, it would be great to be able to describe the expected json contents with a custom type. This way, the consuming client can have access to the type information for this field.

**Context**
I am using graphql-code-generator to create TypeScript types from the Hasura schema. I am looking for a way to create string typing for the contents of jsonb fields

**What Else Has Been Tried**
I have looked for a simple way to rewriting/overriding the field type for the client schema on the client side, prior to the codegen step. However, I have yet found a straight forward mechanism to achieve this

**Anything Else?**
I created a couple of graphql-code-generator plugins to suppor hasura development (https://github.com/ahrnee/graphql-codegen-hasura), and am looking to find a solution to use with this project

**Comment by tsnobip** [comment]
would love to have this too, using JSONB for different explicit types would make it so much safer and easy to use with type-safe graphQL clients.

**Comment by ferm10n** [comment]
For future surfers, here's my attempt at using graphql-codegen custom schema loader to implement this:

I have a table `app_devices_lnk` with a `config` column of `jsonb` type. My goal was to make the types for it more narrow.

```codegen.yaml
schema:
  - http://localhost:8080/v1/graphql: # adjust as needed
      headers:
        x-hasura-admin-secret: adminpassword # adjust as needed
      loader: ./schema-loader.js
```

```schema-loader.js
const { loadSchema } = require('@graphql-tools/load');
const { mergeTypeDefs } = require('@graphql-tools/merge');
const { gql } = require('graphql-tag');
/**
 * merges custom definitions into the schema defined by hasura, overwriting the generic jsonb types
 */
module.exports = async (schemaString, config) => {
    const hasuraSchema = await loadSchema(schemaString, config);

    return mergeTypeDefs([
        // overrides must come first!
        gql` # put your overrides here
            type app_devices_lnk_config_dhl {
                nodeId: String!
                version: String!
                group: String!
                deviceId: String!
            }

            type app_devices_lnk_config_mqtt {
                url: String!
                username: String!
                password: String!
            }
        
            type app_devices_lnk_config {
                dhl: app_devices_lnk_config_dhl
                mqtt: app_devices_lnk_config_mqtt
            }

            type app_devices_lnk {
                config: app_devices_lnk_config!
            }
        `,
        hasuraSchema,
    ], {
        ignoreFieldConflicts: true,
    });
};
```

@jamshally 

My only gripes with this method are:
- if I ever modify the table or column, this will become an orphan type.
- I don't like having to specify a new type with a global name for every nested object in every jsonb type... maybe I'm too much of a noob with GQL though and don't know a better way to do this. (if anyone does, please end my suffering and show me the way!)

**Comment by Brian-Azizi** [comment]
Are there any plans to support this natively within Hasura? It would add a lot of safety and improve the dev experience massively when using JSONB types

**Comment by zwily** [comment]
> For future surfers, here's my attempt at using graphql-codegen custom schema loader to implement this:
> 
> I have a table `app_devices_lnk` with a `config` column of `jsonb` type. My goal was to make the types for it more narrow.

I tried this and it worked great for injecting the type, however now it complains in my query about not selecting the subfields for the jsonb type. But if I add those subfield selectors in the query, of course Hasura ends up rejecting it with "[GraphQL] unexpected subselection set for non-object field". How did you get past this?

**Comment by ferm10n** [comment]
@zwily It's been a while since I posted that and my memory is a bit foggy but I feel like I abandoned that approach because of the issue you're describing :/

HOWEVER! I've learned a bit more about codegen since then so I took another swing at the problem. If you're just trying to get better intellisense in your typescript, I think this will work for ya:

Start with defining schema overrides in a graphql file

```graphql
# schema-overrides.graphql
scalar mes_app_devices_lnk_config # define a custom scalar type

type mes_app_devices_lnk {
  config: mes_app_devices_lnk_config!
}

type mes_app_devices_lnk_insert_input {
  config: mes_app_devices_lnk_config!
}
```

Now the codegen.yml. We don't need a schema-loader.js, because specifying multiple schemas automerges if you specify `ignoreFieldConflicts: true`

```yaml
# codegen.yml
schema: # no need for schema loader. specifying multiple schemas automagically merge
  - schema-overrides.graphql
  - http://localhost:8080/v1/graphql: # adjust as needed
      headers:
        x-hasura-admin-secret: adminpassword # adjust as needed
config:
  ignoreFieldConflicts: true # required for merge-and-override of schemas
generates:
  ./db-types.ts: # or wherever you want your types
    plugins:
      - add: # inject an import to where the REAL type is
        content: |
          import { AppDevicesLnkCfg } './override-types.ts';
      - typescript:
          scalars: # associate your TS types with your custom scalar types that overrode the json type
            app_devices_lnk_config: AppDevicesLnkCfg
```

Then, you can make your `override-types.ts` whatever you want

```typescript
// override-types.ts
export type AppDevicesLnkCfg = {
  dhl?: {
    nodeId: string;
    version: string;
    group: string;
    deviceId: string;
  };
  mqtt?: {
    url: string;
    username: string;
    password: string;
  }
}
```

This way when you query, you won't anger hasura by specifying subfields... this only affects your typescript types.
