### ISSUE TITLE
Docker compose persistant db_data doesn't work

### ISSUE THREAD

**Issue by RichieMerchant** [hasura/graphql-engine#3468]
I would like to persist database data when running Hasura Graphql Engine for local development. But the console fails to run with the docker-compose file below. 

`- db_data:/var/lib/postgresql/data` to `- ./db_data:/var/lib/postgresql/data`

```
version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - ./db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.10.cli-migrations  
    ports:
    - "${PORT}:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
volumes:
  db_data:
```

Logs 

```
postgres_1        | 2019-12-03 17:53:53.543 UTC [1] LOG:  starting PostgreSQL 12.0 (Debian 12.0-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres_1        | 2019-12-03 17:53:53.544 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1        | 2019-12-03 17:53:53.544 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1        | 2019-12-03 17:53:53.556 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1        | 2019-12-03 17:53:53.812 UTC [24] LOG:  database system was shut down at 2019-12-03 17:40:31 UTC
postgres_1        | 2019-12-03 17:53:53.919 UTC [1] LOG:  database system is ready to accept connections
graphql-engine_1  | {"timestamp":"2019-12-03T17:53:44.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"port env var is not set, defaulting to 8080"}}
graphql-engine_1  | {"timestamp":"2019-12-03T17:53:44.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"server timeout is not set defaulting to 30 seconds"}}
graphql-engine_1  | {"timestamp":"2019-12-03T17:53:44.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"starting graphql engine temporarily on port 8080"}}
graphql-engine_1  | {"timestamp":"2019-12-03T17:53:44.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"waiting 30 for 8080 to be ready"}}
graphql-engine_1  | {"timestamp":"2019-12-03T17:53:45.457+0000","level":"info","type":"startup","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":true,"port":8080}}}
graphql-engine_1  | {"timestamp":"2019-12-03T17:53:45.457+0000","level":"info","type":"startup","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:@postgres:5432/postgres"}}}
graphql-engine_1  | {"internal":"could not connect to server: Connection refused\n\tIs the server running on host \"postgres\" (172.26.0.2) and accepting\n\tTCP/IP connections on port 5432?\n","path":"$","error":"connection error","code":"postgres-error"}
```

I couldn't find anything in your docs to say why this may not work. Any help with this would be great.

Thanks
