### ISSUE TITLE
Console Error Message needed for invalid ENUM

### ISSUE THREAD

**Issue by corepay** [hasura/graphql-engine#3487]
Setup Enum table according to `https://docs.hasura.io/1.0/graphql/manual/schema/enums.html` which works as advertised if using console Insert Record and a valid `enum.value` is provided in the fk-related table.  If a value provided in the console is not in the `enum.value` the console does not return a error message - just does not do anything when clicking SUBMIT.

> NOTE:  I am using 2 different schemes - public and system

```
CREATE TABLE public."Users" (
    id character varying DEFAULT ('user-'::text || encode(public.gen_random_bytes(16), 'hex'::text)) NOT NULL,
    two_factor_delivery_method text DEFAULT 'NONE'::text NOT NULL,
);
ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "Users_two_factor_delivery_method_fkey" FOREIGN KEY (two_factor_delivery_method) REFERENCES system.user_two_factor_delivery_method(value) ON UPDATE RESTRICT ON DELETE RESTRICT;
```

```
CREATE SCHEMA system;
CREATE TABLE system.user_two_factor_delivery_method (
    value text NOT NULL,
    comment text NOT NULL
);
ALTER TABLE ONLY system.user_two_factor_delivery_method
    ADD CONSTRAINT user_two_factor_delivery_method_pkey PRIMARY KEY (value);
```

```
- args:
    allowlist: []
    functions: []
    query_collections: []
    remote_schemas: []
    tables:
    - array_relationships: []
      computed_fields: []
      configuration:
        custom_column_names:
        custom_root_fields:
          delete: null
          insert: null
          select: null
          select_aggregate: null
          select_by_pk: null
          update: null
      delete_permissions: []
      event_triggers: []
      insert_permissions: []
      is_enum: false
      object_relationships:
      - comment: null
        name: user_two_factor_delivery_method
        using:
          foreign_key_constraint_on: two_factor_delivery_method
      select_permissions: []
      table: Users
      update_permissions: []
    - array_relationships:
      - comment: null
        name: Users
        using:
          foreign_key_constraint_on:
            column: two_factor_delivery_method
            table: Users
      computed_fields: []
      configuration:
        custom_column_names: {}
        custom_root_fields:
          delete: null
          insert: null
          select: null
          select_aggregate: null
          select_by_pk: null
          update: null
      delete_permissions: []
      event_triggers: []
      insert_permissions: []
      is_enum: true
      object_relationships: []
      select_permissions: []
      table:
        name: user_two_factor_delivery_method
        schema: system
      update_permissions: []
    version: 2
  type: replace_metadata
```
