### ISSUE TITLE
Anyone manage to get Hasura to work in a CI/CD pipeline, e.g. with GitHub Actions?

### ISSUE THREAD

**Issue by joshuarobs** [hasura/graphql-engine#3649]
This is my original issue (https://github.com/hasura/graphql-engine/issues/3638) that I have closed so that I can put it here, in this more centralised issue.

I've spent the last 2 days trying to get Hasura to work with GitHub Actions, so that I can run tests in the cloud after pushing commits. This is so that I can have a proper DevOps workflow, with proper CI/CD.

I've had no luck in being able to get this work. For now I'm giving up, and just going to have to skip cloud testing and pray that my local tests are adequate enough. If someone else wants to take over, good luck.

I have two repos I've tried to make Hasura work in a CI/CD environment:
1. **Attempt 1** - https://github.com/joshuarobs/making-hasura-work-with-github-actions
2. **Attempt 2** - https://github.com/joshuarobs/test-ci

**Attempt 1**
This one uses instructions for setup from here: https://docs.hasura.io/1.0/graphql/manual/getting-started/docker-simple.html

This is by running a `docker-compose`, instead of running `docker-run.sh`.

**Attempt 2**
This one uses instructions for setup from here: https://docs.hasura.io/1.0/graphql/manual/deployment/docker/index.html

This is by running a `docker-run.sh` file, instead of running `docker-compose`.

If someone has managed to make this work with GitHub Actions, please share how you managed to make it work. Or if you managed to make it work with another build server/service, what did you use and what script are you using?

Also with attempt 1 repo, I found a slight clue as to what might be going wrong here: https://github.com/hasura/graphql-engine/issues/3648 But I don't know what to do with this clue

**Comment by shahidhk** [comment]
@joshuarobs What is the error/issue that you're hitting with this configuration?

**Comment by joshuarobs** [comment]
@shahidhk 
For my first repo attempt (full details here: https://github.com/joshuarobs/making-hasura-work-with-github-actions/commit/359867222135dd31e749b9e81327ad1c610d7843/checks?check_suite_id=391660183)

This is the error: `time="2020-01-09T09:21:05Z" level=fatal msg="version check: failed to get version from server: failed making version api call: Get http://localhost:8080/v1/version: EOF"`

If you see the link, you can see that calling pg_dump returns no SQL statements. I find it weird, because if I run the same `pg_dump` on my machine, it returns a lot of SQL stuff.

On my second repo (full details here: https://github.com/joshuarobs/test-ci/commit/07c627eef3d2627ee3d610b4e6efeba3ca3f2fc2/checks?check_suite_id=387692198)

I get this error: ```
time="2020-01-07T09:40:31Z" level=fatal msg="version check: failed to get version from server: failed making version api call: Get http://localhost:8080/v1/version: dial tcp 127.0.0.1:8080: connect: connection refused"
28
##[error]Process completed with exit code 1.
```

Sometimes running a similar workflow gives different errors. But usually they fail to get the version of Hasura

**Comment by joshuarobs** [comment]
I managed to solve this, finally.

This is the GitHub Actions yaml file I use:

```
name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      hasura:
        image: hasura/graphql-engine:latest
        env:
          HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
        ports:
          - 8080:8080

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Install Hasura cli
      run: curl -L https://github.com/hasura/graphql-engine/raw/master/cli/get.sh | bash
    - name: Start up the Docker containers and migrate to the latest version of the database
      run: |
        docker ps
        cd docker
        hasura migrate status --skip-update-check --endpoint http://localhost:8080
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        node index.js
      env:
        CI: true
```

Note this only worked with it running a `js` file that says Hello World. I'm not sure if you can actually make a request to `localhost:8080` and make a GraphQL query. Also, you'd have to migrate some stuff first, from the repo. But knowing that you can get a Hasura server working with Postgres on GitHub Actions is good, knowing that you can do devops with it.
