### ISSUE TITLE
Docker compose up results in all containers being in "restarting" state

### ISSUE THREAD

**Issue by israelidanny** [hasura/graphql-engine#3893]
I tried to follow these instructions:
https://docs.hasura.io/1.0/graphql/manual/getting-started/docker-simple.html

Each time I run docker-compose up -d from this docker-compose.yaml
```
version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```

The containers appear as always restarting and the ports aren't mapped:
```
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                          PORTS               NAMES
1d2a1d7838c0        hasura/graphql-engine:v1.0.0   "graphql-engine serve"   7 minutes ago       Restarting (1) 20 seconds ago                       ecommin-api_graphql-engine_1
42508c6126c4        postgres                       "docker-entrypoint.s…"   7 minutes ago       Restarting (1) 34 seconds ago                       ecommin-api_postgres_1
```

Here are the logs:
```
{"type":"startup","timestamp":"2020-02-15T22:07:53.521+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":null},"enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":false,"port":8080}}}
{"type":"startup","timestamp":"2020-02-15T22:07:53.521+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:@postgres:5432/postgres"}}}
{"internal":"could not translate host name \"postgres\" to address: Name or service not known\n","path":"$","error":"connection error","code":"postgres-error"}
```
```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD for the superuser. Use
       "-e POSTGRES_PASSWORD=password" to set it in "docker run".

       You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
       without a password. This is *not* recommended. See PostgreSQL
       documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

The quick start guide doesn't mention anything about setting a password, and the docker compose doesn't mention it either.
