### ISSUE TITLE
JWT authentication cannot be setup in Hasura running in Kubernetes

### ISSUE THREAD

**Issue by kktam** [hasura/graphql-engine#3915]
By following Hasura documentation in setting up authentication for JWT in a Kubernetes cluster

[https://docs.hasura.io/1.0/graphql/manual/auth/authentication/jwt.html](https://docs.hasura.io/1.0/graphql/manual/auth/authentication/jwt.html)

--jwt-secret flag cannot be used, and the  HASURA_GRAPHQL_JWT_SECRET environment variable need to be programmed in a yaml file. However, the yaml file does not support Base64 enocded JWT json string, as the documentation suggested.

Therefore, Hasura pod inside a Kubernetes cluster cannot be properly configured to enable with JWT authentication from any provider, like Auth0

**Comment by shahidhk** [comment]
@kktam You can add the JWT secret as a JSON string into a `Secret` object and then use in the deployment as a `secretKeyRef`.

```yaml
kind: Secret
metadata:
  name: hasura-secrets
data:
  HASURA_GRAPHQL_JWT_SECRET: '{"key":"" ...}'
```

```yaml
kind: Deployment
...

  env:
    name: HASURA_GRAPHQL_JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: hasura-secrets
        key: HASURA_GRAPHQL_JWT_SECRET
```

(yaml might not be as per spec, use it as a guidance only)
