### ISSUE TITLE
Adding Column presets also adds an empty key/value to migration file

### ISSUE THREAD

**Issue by dijam** [hasura/graphql-engine#3976]
When adding Column presets in permissions, you automatically add a new preset row which is nice in the console.
But as saving and check migration files, there is an empty key-value also added.
```
      localPresets:
      - key: user_id
        value: x-hasura-User-Id
      - key: ""
        value: ""
```

Not a huge deal as it does not do anything to the system.
