### ISSUE TITLE
bug for hasura metadata apply 

### ISSUE THREAD

**Issue by caoer** [hasura/graphql-engine#3988]
version: v1.2.0-beta.1
```
actions:
  kind: synchronous
  handler_webhook_baseurl: http://host.docker.internal:3002
```
with above config, in the metadata directory, actions.yaml

```
actions:
- name: actionPing
  definition:
    kind: synchronous
    handler: '{{HASURA_GRAPHQL_ACTION_NODE_HOST}}/action'
  permissions:
```

then run `hasura metadata apply`
and then `hasura metadata export`

the above action metadata becomes:

```
actions:
- name: actionPing
  definition:
    kind: synchronous
    handler: http://host.docker.internal:3002/actionPing
```

looks like we are having a bug in the migration tool. 

however, with exporting to JSON in the web console, and then importing it. everything works fine.
