### ISSUE TITLE
cli: init --verson 1 creates an inconsistent config.yaml file

### ISSUE THREAD

**Issue by shahidhk** [hasura/graphql-engine#4036]
`hasura init my-project --version 1` creates the following `config.yaml`:
```yaml
version: 0
endpoint: http://localhost:8080
metadata_directory: ""
actions:
  kind: ""
  handler_webhook_baseurl: ""
```
instead of just
```yaml
version: 1
endpoint: http://localhost:8080
```

This is causing issues with migrate api etc.
CLI version: `v1.2.0-beta.2`
