### ISSUE TITLE
Migration with same name as column mapping fails

### ISSUE THREAD

**Issue by gerwim** [hasura/graphql-engine#4168]
I've created the relation called "permissionLevel", for a field "permissionLevel" which maps to "PermissionLevel". This works fine, however the migration created can not run, with the error:

```
apply failed: failed parsing json: json: cannot unmarshal array into Go struct field HasuraError.internal of type hasuradb.SQLInternalError; response from API: {"internal":[{"definition":{"using":{"manual_configuration":{"remote_table":{"schema":"public","name":"AccountPermissionLevel"},"column_mapping":{"permissionLevel":"PermissionLevel"}}},"name":"permissionLevel","comment":null,"table":{"schema":"public","name":"UserAccount"}},"reason":"field definition conflicts with postgres column","type":"object_relation"}],"path":"$.args[6].args","error":"field definition conflicts with postgres column","code":"constraint-violation"}
```

Migration in question:
```
- args:
    name: permissionLevel
    table:
      name: UserAccount
      schema: public
    using:
      manual_configuration:
        column_mapping:
          permissionLevel: PermissionLevel
        remote_table:
          name: AccountPermissionLevel
          schema: public
  type: create_object_relationship
```

Renaming the `name` to e.g. `permissionLevelTest` works and the migration continues:
```
- args:
    name: permissionLevelTest
    table:
      name: UserAccount
      schema: public
    using:
      manual_configuration:
        column_mapping:
          permissionLevel: PermissionLevel
        remote_table:
          name: AccountPermissionLevel
          schema: public
  type: create_object_relationship
```

Version info:
Hasura engine version: 1.2.0-beta.2
Postgres 12.2
