### ISSUE TITLE
Migrations: create_insert_permission always include empty string key value for localPresents

### ISSUE THREAD

**Issue by tobiastornros** [hasura/graphql-engine#4194]
Hasura version: 1.1.0

create_insert_permission type migrations up.yaml always include following key value in the localPrests list. 

```
   localPresets:
      - key: ""
        value: ""
```

Example of migration when creating permission for user on table: 

```
- args:
    role: user
    table:
      name: example_table
      schema: public
  type: drop_insert_permission
- args:
    permission:
      check:
        user_table:
          user_id:
            _eq: X-Hasura-User-Id
      columns:
      - id
      - user_id
      localPresets:
      - key: ""
        value: ""
      set: {}
    role: user
    table:
      name: example_table
      schema: public
  type: create_insert_permission
```

And if I add the x-hasura-user-id localPresets it will look like this: 

```
....
 localPresets:
      - key: user_id
        value: x-hasura-User-Id
      - key: ""
        value: ""
....
```

Is the empty key value really necessary?
