### ISSUE TITLE
Hasura gql engine does not access to postgres instance in docker-compose env

### ISSUE THREAD

**Issue by b3j0f** [hasura/graphql-engine#4229]
Hello.

After working few weeks with hasura, I just met a problem which seems to be between postgres (latest version) and hasura docker containers (same in versions 1.1.0 and 1.1.1).

Hasura success in initializing postgres tables such as hdb_table, hdb_version, etc. (checked from pgadmin where the "clustore" user is superuser)

Then, when I check http://localhost:8001/healtz in a browser (same with console, and hasura-cli migrate, etc.), I have this json response :

```json
{
"path": "$",
"error": "resource does not exist",
"code": "not-found"
}
```

Here is my docker-compose config :

```yaml
services:
  clustore:
    build:
      context: /Users/b3j0f/Developments/go/src/clustore
      dockerfile: ./build/Dockerfile
    container_name: clustore
    depends_on:
    - clustore-db
    - clustore-hasura
    environment:
      CONFIGOR_ENV: production
    image: clustore
    restart: always
    volumes:
    - /Users/b3j0f/Developments/go/src/clustore/configs:/app/clustore/configs:rw
  clustore-db:
    container_name: clustore-db
    environment:
      POSTGRES_DB: clustore
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: clustore
    image: postgres
    ports:
    - published: 8021
      target: 5432
    restart: always
  clustore-hasura:
    container_name: clustore-hasura
    depends_on:
    - clustore-db
    environment:
      CLUSTORE_EVENT_TRIGGER: http://clustore:8011/event-trigger
      CLUSTORE_SECRET: clustore
      HASURA_GRAPHQL_ADMIN_SECRET: clustore
      HASURA_GRAPHQL_AUTH_HOOK: http://clustore:8011/auth
      HASURA_GRAPHQL_DATABASE_URL: postgres://clustore:changeme@clustore-db:5432/clustore
      HASURA_GRAPHQL_ENABLED_APIS: graphql
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log,
        query-log
      HASURA_GRAPHQL_ENABLE_ALLOWLIST: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_PG_CONNECTIONS: '500'
      HASURA_GRAPHQL_PG_TIMEOUT: '180'
    image: hasura/graphql-engine:v1.1.0
    ports:
    - published: 8001
      target: 8080
    restart: always
version: '3.7'
```

Here are postgres logs which does not react.

```
,
PostgreSQL Database directory appears to contain a database; Skipping initialization,
,
2020-03-29 13:41:19.659 UTC [1] LOG:  starting PostgreSQL 12.1 (Debian 12.1-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit,
2020-03-29 13:41:19.660 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432,
2020-03-29 13:41:19.660 UTC [1] LOG:  listening on IPv6 address "::", port 5432,
2020-03-29 13:41:19.663 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432",
2020-03-29 13:41:19.686 UTC [26] LOG:  database system was interrupted; last known up at 2020-03-29 13:39:57 UTC,
2020-03-29 13:41:19.948 UTC [26] LOG:  database system was not properly shut down; automatic recovery in progress,
2020-03-29 13:41:19.950 UTC [26] LOG:  redo starts at 0/1645C78,
2020-03-29 13:41:19.950 UTC [26] LOG:  invalid record length at 0/1645CB0: wanted 24, got 0,
2020-03-29 13:41:19.950 UTC [26] LOG:  redo done at 0/1645C78,
2020-03-29 13:41:19.963 UTC [1] LOG:  database system is ready to accept connections,
```

Here are hasura logs

```json
{"type":"startup","timestamp":"2020-03-29T13:41:20.330+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":null},"enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":true,"log_level":"info","auth_hook_mode":"GET","use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["graphql"],"enable_telemetry":true,"enable_console":true,"auth_hook":"http://clustore:8011/auth","jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":true,"port":8080}}},
{"type":"startup","timestamp":"2020-03-29T13:41:20.330+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://clustore:...@clustore-db:5432/clustore"}}},
{"type":"startup","timestamp":"2020-03-29T13:41:20.330+0000","level":"info","detail":{"kind":"db_migrate","info":"Successfully initialized the catalog (at version 31)."}},
{"type":"startup","timestamp":"2020-03-29T13:41:20.330+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 22","instance_id":"06a0278b-1f42-4418-a314-72d770c07fc2","message":"listener thread started"}}},
{"type":"startup","timestamp":"2020-03-29T13:41:20.330+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 23","instance_id":"06a0278b-1f42-4418-a314-72d770c07fc2","message":"processor thread started"}}},
{"type":"startup","timestamp":"2020-03-29T13:41:20.330+0000","level":"info","detail":{"kind":"event_triggers","info":"preparing data"}},
{"type":"startup","timestamp":"2020-03-29T13:41:20.330+0000","level":"info","detail":{"kind":"event_triggers","info":"starting workers"}},
{"type":"startup","timestamp":"2020-03-29T13:41:20.330+0000","level":"info","detail":{"kind":"telemetry","info":"Help us improve Hasura! The graphql-engine server collects anonymized usage stats which allows us to keep improving Hasura at warp speed. To read more or opt-out, visit https://docs.hasura.io/1.0/graphql/manual/guides/telemetry.html"}},
{"type":"startup","timestamp":"2020-03-29T13:41:20.330+0000","level":"info","detail":{"kind":"server","info":{"time_taken":0.9779846,"message":"starting API server"}}},
{"type":"http-log","timestamp":"2020-03-29T13:41:51.221+0000","level":"error","detail":{"operation":{"error":{"path":"$","error":"resource does not exist","code":"not-found"},"request_id":"c1dec869-a1ec-412a-a92b-ae92b30f2080","response_size":65,"raw_query":"{\"args\":{\"columns\":[\"hasura_uuid\",\"cli_state\"],\"table\":{\"name\":\"hdb_version\",\"schema\":\"hdb_catalog\"}},\"type\":\"select\"}"},"http_info":{"status":404,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.26.0.1","method":"POST","content_encoding":null}}},
{"type":"http-log","timestamp":"2020-03-29T13:41:51.221+0000","level":"error","detail":{"operation":{"error":{"path":"$","error":"resource does not exist","code":"not-found"},"request_id":"9395faeb-bb86-4fd0-93da-91b0d53c6390","response_size":65,"raw_query":"{\"args\":{\"sql\":\"SELECT COUNT(1) FROM information_schema.tables WHERE table_name = 'schema_migrations' AND table_schema = 'hdb_catalog' LIMIT 1\"},\"type\":\"run_sql\"}"},"http_info":{"status":404,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.26.0.1","method":"POST","content_encoding":null}}},
```

Both last logs come from call to `hasura migrate apply` on existing migrations with this config :

```yaml
admin_secret: clustore
endpoint: http://localhost:8001
```

And I tested  the query "SELECT COUNT(1) FROM information_schema.tables WHERE table_name = 'schema_migrations' AND table_schema = 'hdb_catalog' LIMIT 1" from pdagmin, and the result is 1

Do you have any Idea ?
