### ISSUE TITLE
Can't connect Hasura server to existing docker container running Postgres

### ISSUE THREAD

**Issue by dan-rxr** [hasura/graphql-engine#4248]
I'm not sure why, but I'm running into an issue connecting to my Postgres instance that's also running in Docker at this local address: jdbc:postgresql://postgres:@localhost:5432/postgres
(yes - the db user is postgres and there is no password on it currently).

Editing the tutorial database url doesn't seem to be working for me... here's my docker-compose.yaml:

```
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.1.1
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: jdbc:postgresql://postgres:@localhost:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```
Here's the error I'm getting: `{"internal":"could not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n","path":"$","error":"connection error","code":"postgres-error"}`

I know that my DB is up since I can connect to it at that address on DBeaver. Is there some sort of additional configuration I need to do in order to get these two containers to talk to each other?
