### ISSUE TITLE
change default value for num of retries for pg connect

### ISSUE THREAD

**Issue by nunopato** [hasura/graphql-engine#4259]
# Environment/Context

Postgres 12.0
graphql-engine 1.1.0.cli-migrations (same for 1.1.1)
provider docker

# Problem

Graphql-engine doesn't seem to retry connecting to Postgres when it fails on startup.

For reference here is the `docker-compose.yaml` used to start both services
```
version: '3.6'
services:
  postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0.cli-migrations
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_SERVER_PORT: 8080
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_ADMIN_SECRET: 3e940300226fa8e69891abb7329f18e3
    command:
      - graphql-engine
      - serve
    volumes:
      - './migrations:/hasura-migrations'
```

## To demonstrate the problem statement, here are 2 different runs of the 2 services

1) When starting the 2 services separately (postgres first followed by graphql-engine) with roughly 2 seconds (enough for postgres to be up & running) in between, there are no issues. I am omitting the logs here for brevity but I can update the issue if necessary.

2) When starting both services "at the same time" with `docker-compose up` the logs are the following

```
graphql-engine_1  | {"timestamp":"2020-03-31T20:08:32.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"database url for migrations is set by HASURA_GRAPHQL_DATABASE_URL"}}
graphql-engine_1  | {"timestamp":"2020-03-31T20:08:32.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"migrations server port env var is not set, defaulting to 9691"}}
graphql-engine_1  | {"timestamp":"2020-03-31T20:08:32.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"server timeout is not set, defaulting to 30 seconds"}}
graphql-engine_1  | {"timestamp":"2020-03-31T20:08:32.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"starting graphql engine temporarily on port 9691"}}
graphql-engine_1  | {"timestamp":"2020-03-31T20:08:32.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"waiting 30 for 9691 to be ready"}}
graphql-engine_1  | {"type":"startup","timestamp":"2020-03-31T20:08:33.059+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":null},"enabled_log_types":["http-log","websocket-log","startup","webhook-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata"],"enable_telemetry":true,"enable_console":false,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":false,"port":9691}}}
graphql-engine_1  | {"type":"startup","timestamp":"2020-03-31T20:08:33.059+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:...@postgres:5432/postgres"}}}
graphql-engine_1  | {"internal":"could not connect to server: Connection refused\n\tIs the server running on host \"postgres\" (172.18.0.2) and accepting\n\tTCP/IP connections on port 5432?\n","path":"$","error":"connection error","code":"postgres-error"}
postgres_1        |
postgres_1        | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1        |
postgres_1        | 2020-03-31 20:08:33.250 UTC [1] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres_1        | 2020-03-31 20:08:33.251 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1        | 2020-03-31 20:08:33.251 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1        | 2020-03-31 20:08:33.255 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1        | 2020-03-31 20:08:33.326 UTC [27] LOG:  database system was shut down at 2020-03-31 20:07:25 UTC
postgres_1        | 2020-03-31 20:08:33.358 UTC [1] LOG:  database system is ready to accept connections

graphql-engine_1  | {"timestamp":"2020-03-31T20:09:02.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"failed waiting for 9691"}}
graphql-engine_1  | {"type":"startup","timestamp":"2020-03-31T20:09:03.777+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_o
ptions":{"plan_cache_size":null},"enabled_log_types":["http-log","websocket-log","startup","webhook-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":
false,"enabled_apis":["metadata"],"enable_telemetry":true,"enable_console":false,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":false,"port":9691}}}
graphql-engine_1  | {"type":"startup","timestamp":"2020-03-31T20:09:03.777+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:...@postgres:5432/postgres"}}}
graphql-engine_1  | {"type":"startup","timestamp":"2020-03-31T20:09:03.777+0000","level":"info","detail":{"kind":"db_migrate","info":"Already at the latest catalog version (31); nothing to do."}}
graphql-engine_1  | {"timestamp":"2020-03-31T20:09:05.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"port 9691 is ready"}}
graphql-engine_1  | {"timestamp":"2020-03-31T20:09:05.000+0000","level":"info","type":"startup","detail":{"kind":"migration-apply","info":"checking for migrations directory"}}
```

Notice the ~30 seconds between `{"kind":"migration-apply","info":"waiting 30 for 9691 to be ready"}` and `{"kind":"migration-apply","info":"failed waiting for 9691"}` even though Postgres became available ~2 seconds after the first try.

After digging a bit through the source code, starting here https://github.com/hasura/graphql-engine/blob/v1.1.0/scripts/cli-migrations/docker-entrypoint.sh, what is happening becomes clear: after the default timeout of 30 seconds, the container for graphql-engine gets restarted and this time it successfully starts given that Postgres is already available. No matter what that timeout is, `wait_for_port()` will always fail, because the issue lies somewhere else down the road, when `pg-client-hs` hangs trying to connect to the Postgres instance, consequently leaving the engine hanging as well.  

My knowledge of Haskell is very limited but I think that the issue lies somewhere here within `pgRetrying `
https://github.com/hasura/pg-client-hs/blob/master/src/Database/PG/Query/Connection.hs#L123
