### ISSUE TITLE
show command to upgrade project to v2 when actions cmd is invoked on a v1 project

### ISSUE THREAD

**Issue by cesarve77** [hasura/graphql-engine#4343]
running:
```
$hasura actions create xxxx
```
I get: 
actions commands can be executed only when config version is greater than 1

versions:
```
INFO hasura cli                                    version=v1.2.0-beta.3
INFO hasura graphql engine                         endpoint="https://eazzyapp.herokuapp.com/v1/graphql" version=
```

endpoint version seem empty 

But in my console I can see

v1.2.0-beta.3

**Comment by cesarve77** [comment]
I fixed creating the config.yaml

now any cli command throw 
```
FATA[0004] cannot create migrate instance: Data Error: {"path":"$","error":"resource does not exist","code":"not-found"} 
```

my config.yml

```

version: 2
endpoint: https://eazzyapp.herokuapp.com/v1/graphql
admin-secret: myverysecretwords
metadata_directory: metadata
actions:
  kind: asynchronous
  handler_webhook_baseurl: http://host.docker.internal:3000


```
