### ISSUE TITLE
Importing hasura_metadata.json with Hasura Action query

### ISSUE THREAD

**Issue by crosseyedalien** [hasura/graphql-engine#4516]
I think this is a simple one. I noticed that the release notes for version 1.2.0-beta.4 said Hasura Actions could now be defined with a Query so I tried it out. After creating it, I exported the metadata and then re-imported it and received the error message:
```
Failed importing metadata
key "arguments" not present
```

Of course a query does not technically need arguments, but it appears whatever metadata validation goes on is still looking for one. Maybe Hasura Action Queries are being validated against the same rules as Hasura Action Mutations?

Action Definition Used:

```
type Query {
  actionName : SampleOutput
}

type SampleOutput {
  accessToken : String!
}
```

Thanks

**Comment by jchonde** [comment]
Same issue here with v1.2.0-beta4. Once created the action appear to have no arguments in the metadata - which is fine for actions with no arguments - but once the metadata migration runs it crashes for not finding arguments.

In metadata when created:
```
- name: awesome_action
  definition:
    handler: '{{MY_HANDLER_URL}}'
    output_type: MyOutputType
    type: mutation
    kind: synchronous
```

Expected when migration is ran:
```
- name: awesome_action
  definition:
    handler: '{{MY_HANDLER_URL}}'
    output_type: MyOutputType
    arguments: []  
    type: mutation
    kind: synchronous
```
