### ISSUE TITLE
v1.2.0.cli-migrations image is pointing to beta.5?

### ISSUE THREAD

**Issue by KCErb** [hasura/graphql-engine#4610]
```
image: hasura/graphql-engine:v1.2.0.cli-migrations
```

A container built from ^that image gives a UI console that says "v1.2.0-beta.5" in the top-left corner and I get the footer popup recommending I upgrade to v1.2.0. This is on a brand new example with no customization, just `docker-compose up -d`. I expect the following config to reproduce (though I could give you my full config if you're having trouble.

```
version: '3.6'
services:
  hasura:
    image: hasura/graphql-engine:v1.2.0.cli-migrations
```
