### ISSUE TITLE
Not getting any headers in POST request body in auth hook

### ISSUE THREAD

**Issue by kaniak274** [hasura/graphql-engine#4691]
Hello everyone,
I've tried to configure auth hook using POST method but I'm not getting any headers in the request body and I have no idea what I have done wrong.

My docker-compose.yml config:
```
graphql-engine:
        image: hasura/graphql-engine:latest
        ports:
            - "8080:8080"
        depends_on:
            - "db"
        restart: always
        networks:
            - my-network
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://user:secret@db:5432/db_name
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup
            HASURA_GRAPHQL_ADMIN_SECRET: secret
        command:
            - graphql-engine
            - serve
            - --auth-hook=http://backend/admin/auth/verify-session/
            - --auth-hook-mode=POST
```

EDIT:
Query looks like this:
```
fetch('http://localhost:8080/v1/graphql', {
    method: "POST",
    headers: {
        'X-CSRFToken': Cookies.get('csrftoken'),
        'Content-Type': 'application/json',
     },
     body: `query {
         user {
             id,
             first_name,
             last_name
         }
     }`
 }).then(response => response.json()).then(data => console.log(data));
```
