### ISSUE TITLE
v1.2.1 Running with Docker and Connecting to Postgresql Deployes using Docker on Another Server Just Keeps Restarting

### ISSUE THREAD

**Issue by taribowo** [hasura/graphql-engine#4740]
Hello, I tried to upgrade to the latest hasura graphql engine version, which is v1.2.1 today and it just won't start. Quick look at docker container list just list the container status as restarting. Occasionally it would change to Up but only for a second or less before restarting again.

A look at docker logs <container-name> returns these
```json
{
    "type": "startup",
    "timestamp": "2020-05-12T06:05:55.076+0000",
    "level": "info",
    "detail": {
        "kind": "postgres_connection",
        "info": {
            "retries": 1,
            "database_url": "postgres://<postgres-username>:...@<server-ip>:<postgres-port>/<db-name>"
        }
    }
}

{
    "type":"startup",
    "timestamp":"2020-05-12T06:05:58.429+0000",
    "level":"info",
    "detail":{
        "kind":"server_configuration",
        "info":{
            "live_query_options":{
                "batch_size":100,
                "refetch_delay":1
            },
            "transaction_isolation":"ISOLATION LEVEL READ COMMITTED",
            "plan_cache_options":{
                "plan_cache_size":null
            },
            "enabled_log_types":[
                "http-log",
                "websocket-log",
                "startup",
                "webhook-log"
            ],
            "server_host":"HostAny",
            "enable_allowlist":false,
            "log_level":"info",
            "auth_hook_mode":null,
            "use_prepared_statements":true,
            "unauth_role":null,
            "stringify_numeric_types":false,
            "enabled_apis":[
                "metadata",
                "graphql",
                "config",
                "pgdump"
            ],
            "enable_telemetry":true,
            "enable_console":true,
            "auth_hook":null,
            "jwt_secret":{
                "audience":null,
                "claims_format":null,
                "claims_namespace":"<namespace>",
                "key":"<JWK REDACTED>",
                "type":"<TYPE REDACTED>",
                "issuer":null
            },
            "cors_config":{
                "allowed_origins":"*",
                "disabled":false,
                "ws_read_cookie":null
            },
            "console_assets_dir":null,
            "admin_secret_set":true,
            "port":8080
        }
    }
}
```

my docker-compose.yml file look like this
```yaml
version: '3.6'
services:
  hasura-engine:
    image: hasura/graphql-engine:v1.2.1
    container_name: hasura-engine
    networks:
        static-network:
            ipv4_address: 172.20.1.2
    ports:
    - "<port>:8080"
    expose:
    - "8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: <db-url>
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: "<secret>"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"<type>", "key":"<key>", "claims_namespace":"<namespace>"}'
networks:
    static-network:
        ipam:
            config:
                - subnet: 172.20.1.0/16
```

I've take a look at #1048, #3893, and #3895, but all 3 of those are running a postgres service from the same docker-compose file whereas i'm connecting to a running postgres service.

Any help so i can upgrade to the latest version of hasura graphql engine is much appreciated.

Thank you
