### ISSUE TITLE
Error adding JWT secret to docker compose

### ISSUE THREAD

**Issue by rhlsthrm** [hasura/graphql-engine#4792]
I added the JWT secret I generated on https://hasura.io/jwt-config/ to my docker-compose yaml as follows:

```yaml
version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
  graphql-engine:
    image: hasura/graphql-engine:v1.2.1
    ports:
      - "8081:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "key": "-----BEGIN CERTIFICATE-----...<CERT_DATA>-----END CERTIFICATE-----"}'
      HASURA_GRAPHQL_ADMIN_SECRET: youradminsecret
volumes:
  db_data:
```

When I run `docker-compose up` I'm getting an error:

```
Fatal Error:- Environment variable HASURA_GRAPHQL_JWT_SECRET: Error in $: Failed reading: Cannot decode input: Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
```

Any idea how to fix? I made sure I followed the directions to put into single quotes.
