### ISSUE TITLE
Why not working with existing DB of PostgreSQL 9.6.17?

### ISSUE THREAD

**Issue by sotnikov-link** [hasura/graphql-engine#4833]
I run for existing DB of PostgreSQL 9.6.17

```sh
docker run -it -p 8080:8080 \
  -e HASURA_GRAPHQL_DATABASE_URL=postgres://username:password@host:5432/db-name \
  -e HASURA_GRAPHQL_ENABLE_CONSOLE=true \
  hasura/graphql-engine:v1.2.1
```

After, I get output and exit from container

```
{"type":"startup","timestamp":"2020-05-20T19:33:15.610+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":null},"enabled_log_types":["http-log","websocket-log","startup","webhook-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":false,"port":8080}}}
{"type":"startup","timestamp":"2020-05-20T19:33:15.610+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://username:...@host:5432/db-name"}}}
```

**Comment by sotnikov-link** [comment]
Working docker-compose.yml

```yml
version: '3.6'
services:
  postgres:
    image: postgres:9.6.17
    restart: always
    volumes:
      - ./volumes/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.2.1
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
```

But when I paste own HASURA_GRAPHQL_DATABASE_URL, it don't work.

Connect works over psql inner container of postgres.
