### ISSUE TITLE
Squash migration error when create and update an event trigger

### ISSUE THREAD

**Issue by tibotiber** [hasura/graphql-engine#4883]
Hi,

Just a heads up on a squashed migration error. I've fixed the file manually but thought it would be worth reporting.

Repro:
1. create an event trigger resulting in migration below
```yaml
- args:
    enable_manual: false
    headers:
    - name: Authorization
      value_from_env: SMPLRTOKEN
    name: update_user_status_on_publish
    retry_conf:
      interval_sec: 10
      num_retries: 3
      timeout_sec: 60
    table:
      name: spaces
      schema: public
    update:
      columns:
      - status
    webhook_from_env: UPDATE_USER_STATUS_WEBHOOK
  type: create_event_trigger
```

2. update that migration (because you forgot to tick "delete" 😬) resulting in migration below
```yaml
- args:
    delete:
      columns: '*'
    enable_manual: false
    headers:
    - name: Authorization
      value_from_env: SMPLRTOKEN
    name: update_user_status_on_publish
    replace: true
    retry_conf:
      interval_sec: 10
      num_retries: 3
      timeout_sec: 60
    table:
      name: spaces
      schema: public
    update:
      columns:
      - status
    webhook_from_env: UPDATE_USER_STATUS_WEBHOOK
  type: create_event_trigger
```

3. squash migrate resulting in migration below
```yaml
- args:
    delete:
      columns: '*'
    headers:
    - name: Authorization
      value_from_env: SMPLRTOKEN
    name: update_user_status_on_publish
    replace: true
    retry_conf:
      interval_sec: 10
      num_retries: 3
      timeout_sec: 60
    table:
      name: spaces
      schema: public
    update:
      columns:
      - status
    webhook_from_env: UPDATE_USER_STATUS_WEBHOOK
  type: create_event_trigger
```

and it's not gonna work because of `replace: true`, also we've lost `enable_manual: false`.

One more thing, after squashing there is no more `delete_event_trigger` in the down migration.

Hope this helps.
