### ISSUE TITLE
Applying metadata via the CLI fails in a GitHub action

### ISSUE THREAD

**Issue by RapidOwl** [hasura/graphql-engine#4889]
I'm using a GitHub action to apply Hasura migrations and metadata to a Hasura instance hosted on Heroku.

Migrations work fine, but applying metadata results in the following error: `msg="failed to apply metadata: cannot apply metadata on the database: cannot build actions from metadata: error in converting sdl to metadata: fork/exec /github/home/.hasura/plugins/bin/hasura-cli_ext: no such file or directory: "`

Here's the CLI output:
```
Executing 'hasura metadata apply --endpoint *** --admin-secret ***' from 'Hasura'
{"level":"info","msg":"Applying metadata...","time":"2020-05-26T13:21:53Z"}
{"level":"info","msg":"Installing plugin cli-ext...","time":"2020-05-26T13:21:54Z"}
{"level":"info","msg":"plugin installed","name":"cli-ext","time":"2020-05-26T13:21:55Z"}
time="2020-05-26T13:21:55Z" level=fatal msg="failed to apply metadata: cannot apply metadata on the database: cannot build actions from metadata: error in converting sdl to metadata: fork/exec /github/home/.hasura/plugins/bin/hasura-cli_ext: no such file or directory: "
```

The log shows that the metadata plugin is being installed successfully, but then it's like the CLI can't find it. I tried to find out if GitHub actions run as root and the internet suggests that they do, but I'm not certain.

For reference, here's the yaml for my GitHub action:
```
name: Release

on:
  push:
    branches:
    - release/*

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Apply Hasura migrations
      uses: tibotiber/hasura-action@master
      with:
        args: migrate apply
      env:
        HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
        HASURA_ADMIN_SECRET: ${{ secrets.HASURA_SECRET }}
        HASURA_WORKDIR: Hasura
    - name: Apply Hasura metadata
      uses: tibotiber/hasura-action@master
      with:
        args: metadata apply
      env:
        HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
        HASURA_ADMIN_SECRET: ${{ secrets.HASURA_SECRET }}
        HASURA_WORKDIR: Hasura
```

Here's the link to the source for the action I'm using to run the Hasura CLI: https://github.com/tibotiber/hasura-action.
