### ISSUE TITLE
Configurable Async Action Timeout

### ISSUE THREAD

**Issue by jaymth** [hasura/graphql-engine#4966]
Are async action timeouts configurable? From what I can tell, async actions have a default timeout of 30s. This limits their use case IMO, since their purpose is to perform some time-consuming action. As this 30 second timeout does not fit my application's needs, I would love to be able to configure this, if possible.

**Comment by arys** [comment]
How to exactly configure timeouts for actions?
I've added `timeout` argument to my action like this:
`migrations/metadata.yaml`:
```
- name: exportTemplate
  definition:
    handler: http://express:3000/actions/exportTemplate
    timeout: 3600
```
and reloaded metadata, but nothing changed

**Comment by RodolfoSilva** [comment]
@arys have you tried with the latest version?

**Comment by arys** [comment]
@RodolfoSilva, sorry I didn't notice milestone v1.3.3 😅, I updated to latest version and it works now!

**Comment by RodolfoSilva** [comment]
With me, the command: 

```bash
hasura metadata export
```

This isn't working as expected, the command doesn't export the timeout.

**Comment by codingkarthik** [comment]
@RodolfoSilva While adding the action, did you add a timeout with it? If you did, was the timeout 30 seconds? I ask this because currently we don't export the timeout when the timeout value is the default value (30 seconds).

**Comment by RodolfoSilva** [comment]
@codingkarthik I've changed the action file putting `timeout: 60`, like @arys example, and executing the command: ```hasura metadata apply``` and later running ```hasura metadata export```

**Comment by RodolfoSilva** [comment]
actions.yaml
```yml
- name: my_awesome_action
  definition:
    kind: synchronous
    handler: '{{ACTIONS_BASE_URL}}/my_awesome_action'
    forward_client_headers: true
    timeout: 120
```

I've tried modify directly in the database but this does't work.

```bash
$ hasura version
INFO hasura cli                                    version=v1.3.3
INFO hasura graphql engine                         endpoint="http://localhost:8080" version=v1.3.3
```
