### ISSUE TITLE
Renaming tables results in an error when having 2 Hasura projects open at the same time in Docker locally

### ISSUE THREAD

**Issue by joshuarobs** [hasura/graphql-engine#5097]
Occurs on v1.2.2 and beta 1.3

For now, I can manage to have 2 different Hasura databases running locally on my machine in Docker simultaneously, and you can make queries in each of them properly.

However, I have a similar table in each of the 2 databases:

````
db-a:
- versions

db-b:
-versions_cms
````

They serve the same function, containing the current version of all the data and schema in the database, however they are named differently for remote schema compatability purposes.

If I want to rename `versions` in `db-a` to `versions_users`, it's simple to do under the `Data` tab of the console. Under normal situations it would work normally. 

However, when I try to do it, I get an error message, saying that the `versions` table doesn't exist. Clearly that's not the case since I can see it in the console, and clearly I can add rows inside the table and they work fine.

My understanding of this bug was because of this error message that I got:

````
ERRO error listening on port 9693                  error="listen tcp 127.0.0.1:9693: bind: address already in use"
INFO console running at: http://localhost:9695/   
````

Note that even with this error, things still run normally. I have 2 consoles running, one on port 9695 and the other on port 9696.

I think its because one of the Hasura consoles is looking at the schema or data from another server. Of course if you try to rename `versions`, looking in the other database/console that only has `versions_users`, then yes, it doesn't exist. But if it looked in its own database/console, it would know that it exists. 

### Reproducing the error

This is how I get the error:
1. Run `hasura console --console-port 9696 --endpoint http://localhost:8090` on the first repo

This is the result of 1:
`INFO console running at: http://localhost:9696/   `

Basically everything is fine as it should be, since we are only running one repo.

Now let's run the other console.
2. In the other repo, run `hasura console`

This is the result of step 2:
````
ERRO error listening on port 9693                  error="listen tcp 127.0.0.1:9693: bind: address already in use"
INFO console running at: http://localhost:9695/   
````

### Reproducing the error
In one of the two different hasura consoles, try to rename a table, and it will say that it doesn't exist, even though it should, since you are able to click on the table and click on the `Modify` tab.

Not sure if this occurs on the first or the second database, but I know it occurs in one of them.

### My understanding of the root cause of the error
I think it essentially comes from this message when starting the second console:
`error="listen tcp 127.0.0.1:9693: bind: address already in use"`

Clearly 2 repos are attempting to use a resource that's meant to be hosted on port `9693`. It works fine for the first repo, but the moment you add another, you get conflicting problems.

When you try to rename a table with 2 simultaneous Hasura consoles, it seems as though for one of the consoles, it's looking in the other Hasura server's database. Trying to rename a table only results in an error saying that the table doesn't exist. It does exist in the current console/database, but yes, it doesn't exist in the other console/database. It's looking in the other console/database when it shouldn't.

### A potential solution to solve this issue
As far as I'm concerned, I'm not actually sure what goes on in port `9693`. There has to be some sort of cli flag or config variable that a user can set that can allow this port to be changed manually.

A use case of mine would be to have repo A "listen" on port `9693` and repo B "listen" on port `9692`

I think this is obviously different from the endpoint where the console would start normally, i.e. on port `9695`, so this other port should also be allowed to be customised.

### Additional materials

**docker-compose.yaml (repo A)**
````
version: '3.6'
services:
  postgres:
    image: postgres:12.3
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - "5442:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  graphql-engine:
    image: hasura/graphql-engine:v1.2.2
    ports:
    - "8090:8090"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_SERVER_PORT: 8090
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console so we can do migrations
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # Not needed for development since this will just slow us down
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:

````

**docker-compose.yaml (repo B)**
````
version: '3.6'
services:
  postgres:
    image: postgres:12.1
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.3.0-beta.1
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

volumes:
  db_data:

````
