### ISSUE TITLE
Rollback of untracked table doesn't return the original permissions

### ISSUE THREAD

**Issue by romcok** [hasura/graphql-engine#5192]
When I run the `hasura console` and add a migration that untracks the table, the original migration will not save the original rights and the rollback will not work properly.

_up.yaml_
```yaml
- args:
    table:
      name: posts
      schema: public
  type: untrack_table
```

_down.yaml_
```yaml
- args:
    name: posts
    schema: public
  type: add_existing_table_or_view
# here should be original permissions to return the scheme to its original state
```
