### ISSUE TITLE
Can't connect from a hasura instance to another hasrura instance (504 Gateway timeout when adding remote schema)

### ISSUE THREAD

**Issue by phoenix1796** [hasura/graphql-engine#5229]
I'm using hasura version v1.2.2 and am trying to connect a hasura instance running with another instance I had running ,
When I try to add a remote schema I get a 504 in the API call and get a (Gateway timeout error)

Is this a known issue, am I using the wrong URLs ?

I have tried this out by setting up the servers from scratch, but it's still giving me the same error :
![image](https://user-images.githubusercontent.com/9111802/85928809-7e00a780-b8cd-11ea-93d2-1e6aca4146be.png)

**Comment by praveenweb** [comment]
@phoenix1796 - The URL specified above (auth.achopra.io/v1/graphql) doesn't seem to be up and running. Where is graphql-engine hosted?

**Comment by phoenix1796** [comment]
@praveenweb the gaphql-engine was hosted here, though I had to take it down because we weren't able to use it properly (the timeout was due to packets being dropped due to internal networking issues)

But once that was resolved ,even then the API was not returning proper data, will create another issue with proper details for that

**Comment by ChakshuGautam** [comment]
I am facing same issue. I have two servers on the same IP. Trying to connect from either is not happening. I am using a single docker-compose to set up both of them. 

http://165.22.214.127:5005/v1/graphql
http://165.22.214.127:5005/v1/graphql

```yaml
  graphql-engine-identity:
    image: hasura/graphql-engine:v1.1.1
    ports:
      - "5005:8080"
    depends_on:
      - "identity-db"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://a:b@identity-db:5432/c
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: blabla1
      HASURA_GRAPHQL_ENABLE_ALLOWLIST: "true"
      HASURA_GRAPHQL_ENABLED_APIS: graphql, metadata
      HASURA_GRAPHQL_DEV_MODE: "false"
  graphql-engine-profile:
    image: hasura/graphql-engine:v1.1.1
    ports:
      - "5006:8080"
    depends_on:
      - "profile-db"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://d:e@profile-db:5432/f
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: blabla1
      HASURA_GRAPHQL_ENABLE_ALLOWLIST: "true"
      HASURA_GRAPHQL_ENABLED_APIS: graphql, metadata
      HASURA_GRAPHQL_DEV_MODE: "false"
```

The servers are live working fine.
