### ISSUE TITLE
hasura migrations (config v2) are generated as yaml instead of sql

### ISSUE THREAD

**Issue by dvekeman** [hasura/graphql-engine#5240]
```
hasura version
INFO hasura cli                                    version=v1.2.2
```

I migrated a config v1 to a config v2 project so the migrations are in sql. 

However when I make a change in the browser (localhost:9695), the generated migrations are still in the yaml syntax.
As a result, when I run the `migrate apply` command they seem to be ignored.

Am I right that these should be in sql instead of yaml?

Did I forget to apply a setting somewhere?

Thanks!

---

config.yaml
```
version: 2
endpoint: http://127.0.0.1:80
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
```

I start the console using:
```
  hasura console --endpoint ... --admin-secret ...
```
