### ISSUE TITLE
Error connecting to multiple Hasura Remote schema.

### ISSUE THREAD

**Issue by ChakshuGautam** [hasura/graphql-engine#5305]
I have two servers on the same IP. Trying to connect from either is not happening. I am using a single docker-compose to set up both of them. 

http://165.22.214.127:5005/v1/graphql
http://165.22.214.127:5005/v1/graphql

```yaml
  graphql-engine-identity:
    image: hasura/graphql-engine:v1.1.1
    ports:
      - "5005:8080"
    depends_on:
      - "identity-db"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://a:b@identity-db:5432/c
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: blabla1
      HASURA_GRAPHQL_ENABLE_ALLOWLIST: "true"
      HASURA_GRAPHQL_ENABLED_APIS: graphql, metadata
      HASURA_GRAPHQL_DEV_MODE: "false"
  graphql-engine-profile:
    image: hasura/graphql-engine:v1.1.1
    ports:
      - "5006:8080"
    depends_on:
      - "profile-db"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://d:e@profile-db:5432/f
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: blabla1
      HASURA_GRAPHQL_ENABLE_ALLOWLIST: "true"
      HASURA_GRAPHQL_ENABLED_APIS: graphql, metadata
      HASURA_GRAPHQL_DEV_MODE: "false"
```

The servers are live working fine.
