### ISSUE TITLE
Applying v2 metadata with `custom_column_names` results in no-op

### ISSUE THREAD

**Issue by xomaczar** [hasura/graphql-engine#5384]
Using  docker container `hasura/graphql-engine:v1.3.0-beta.4.cli-migrations-v2` with v2 config directories (metadata/migrations). 
When adding a custom column name to a table via 
```
// ...snip...
- table:
    schema: public
    name: post
  configuration:
    custom_root_fields: {}
    custom_column_names:
      authorname: authorName
```
results in no-op. Hasura seems to ignore that metadata change (both in graphiql/hasura console/metadata export).
