### ISSUE TITLE
Running add_remote_schema migration on multiple environments

### ISSUE THREAD

**Issue by mdzimbeg** [hasura/graphql-engine#5424]
Hi, 

we have Hasura set up to run in a docker container, and now trying to add Remote Schema to it. All is working well, and the Remote Schema is successfully added. However, once it is added it creates a new migration, as follows:

```
- args:  
    definition:  
      forward_client_headers: false  
      headers: []  
      timeout_seconds: 60  
      url: http://host.docker.internal:4000/  
    name: TestAPI  
  type: add_remote_schema  
```

The problem is that the URL to the remote schema is part of the migration, and the API that we want to add is environment dependent, meaning that it needs to have different URL depending on where the migration runs (local, staging, production...). Is it possible to somehow pass this URL dynamically, or maybe some other way to get the migration run with different URL depending on the environment?

Thanks!
