### ISSUE TITLE
hasura metadata export fails in NixOS

### ISSUE THREAD

**Issue by mrkkrp** [hasura/graphql-engine#5449]
I have followed [this guide][docker-simple] and after downloading the `docker-compose.yml` file and changing `HASURA_GRAPHQL_ENABLE_CONSOLE` from `"true"` to `"false"` I am able to run various commands such as `hasura console` and `hasura migrate create ...`. However, `hasura metadata export` fails:

```
> hasura metadata export
FATA[0001] failed to export metadata: cannot export metadata from server: cannot export actions from metadata: error in converting metadata to sdl: fork/exec /home/mark/.hasura/plugins/bin/hasura-cli_ext: no such file or directory: 
```

Note how it says `no such file or directory:` and apparently in place of the actual directory in question the empty string is printed. This is strange. I am unable to explain this behavior, it looks like a bug.

[docker-simple]: https://hasura.io/docs/1.0/graphql/manual/getting-started/docker-simple.html

Here is the `docker-compose.yml` file that I use:

```yaml
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```

`hasura-cli` version that I use locally is 1.3.0.
