### ISSUE TITLE
'postgres connection failed' always when deploy with k8s

### ISSUE THREAD

**Issue by phamquyhai** [hasura/graphql-engine#5468]
I deployed Hasura (1.2.x or 1.3.0) with k8s and Digitalocean PostgreSQL Database Clusters (using Connection Pool with Session mode)

Hasura sometime not healthy. my pod restart many times :(

i see ~5 minutes api /healthz not return 500

```
graphql-engine-cr7wd-deployment-554c77fdd7-842tr   2/2     Running   2          10m
graphql-engine-cr7wd-deployment-554c77fdd7-842tr   2/2     Running   3          16m
graphql-engine-cr7wd-deployment-554c77fdd7-842tr   2/2     Running   4          21m
graphql-engine-cr7wd-deployment-554c77fdd7-842tr   2/2     Running   5          26m
```

Logs

```
{"type":"pg-client","timestamp":"2020-07-28T01:58:00.418+0000","level":"warn","detail":{"message":"postgres connection failed, retrying(0)."}}
```

k8s manifest

```
....
containers:
        - image: hasura
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /healthz
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 30
            failureThreshold: 3
          envFrom:
            - secretRef:
                name: hasura-secret
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - name: h2c
              containerPort: 8080
              protocol: TCP
```

Plz help me !
