### ISSUE TITLE
Hasura CLI generates wrong enum metadata and migrations

### ISSUE THREAD

**Issue by vnovick** [hasura/graphql-engine#5478]
In version `1.3.0`, When running Hasura console through CLI and changing a table to enum,
metadata that is generated is as following:

```
- table:
    schema: public
    name: interestType
  is_enum: true
```
This is wrong yaml indentation, so as a result `metadata apply` will fail. The correct way of setting table as `is_enum` is as following.

```
- table:
    schema: public
    name: interestType
    is_enum: true
```

Apart from that since table is enum table and will be expected to have predefined values, I would expect to have insert migration generated when you convert table to enum from the console. Otherwise if let's say I am running migrations in CI, I will need to go to production db and manually add enum values to the table.
