### ISSUE TITLE
Very long bulk query execution time

### ISSUE THREAD

**Issue by Difrex** [hasura/graphql-engine#5536]
Hi,

We have a Hasura installation in the private k8s(bare metal). For permission management, we are using a custom service that sends bulk queries with a `create_permission/delete_permission` requests.

The our limits in the k8s ns is:
```yaml
    Limits:
      cpu:                          1250m
      ephemeral-storage:  100Mi
      memory:                    2Gi
    Requests:
      cpu:                           800m
      ephemeral-storage:  1Mi
      memory:                   1Gi
```

The queries took a lot of time from 2mins up to 20mins to apply. Also, bulk queries cause high memory usage.

* [database schema](https://github.com/hasura/graphql-engine/files/5028834/schema_only_ready.sql.gz)
* [bulk query](https://github.com/hasura/graphql-engine/files/5028836/bulk_query.json.gz)

Memory usage at the bulk query execution time.
![hasura_high_memory_usage](https://user-images.githubusercontent.com/3982213/89422027-74c0f100-d73d-11ea-935a-e512e215472e.png)
