### ISSUE TITLE
YAML parsing issue if the column is named "no"

### ISSUE THREAD

**Issue by abdullah2993** [hasura/graphql-engine#5537]
If you have a column named `no` and you add premissions for it from hasura console and then apply metadata it fails. As `no` is interpreted as a boolean `false` (yaml treats `yes` as true and `no` as false)
Example of generated config:
```
insert_permissions:
  - role: somerole
    permission:
      check: {}
      columns:
      - id
      - no
      - somecol
```
The manual workaround is to quote the colums `"no"`
like so:
```
insert_permissions:
  - role: somerole
    permission:
      check: {}
      columns:
      - id
      - "no"
      - somecol
```
