### ISSUE TITLE
Hasura migration does not work and generates empty files

### ISSUE THREAD

**Issue by whollacsek** [hasura/graphql-engine#5656]
I followed the documentation and have a setup where I run the provided docker-compose.yaml in WSL2, but I'm having 2 blocking issues.

1. When I run `npx hasura console` the page that is automatically opened is unreachable. Since I can not use the console I decided to create the migration manually but...
2. Running `npx hasura migration create` yields a new migration folder that contains up.sql and down.sql that are both empty. Running `npx hasura migration status` does not show this new migration in the list.

The docker-compose.yaml
```yml
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.0.cli-migrations-v2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    volumes:
    - ./hasura/migrations:/hasura-migrations
    - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:

```

The config.yaml
```yml
version: 2
endpoint: http://localhost:8080
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
```
