### ISSUE TITLE
CLI doesn't respect `HASURA_GRAPHQL_ADMIN_SECRET` environment variable

### ISSUE THREAD

**Issue by samuela** [hasura/graphql-engine#5690]
I just ran `hasura init` to get an initial project layout. I have an existing Hasura endpoint set up already. My config.yaml looks like
```yaml
version: 2
endpoint: https://my-hasura.herokuapp.com/
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
```
and I have an environment variable `HASURA_GRAPHQL_ADMIN_SECRET` set appropriately according to https://hasura.io/docs/1.0/graphql/core/hasura-cli/config-reference.html#environment-variables. However I still get errors:
```
❯ hasura console
FATA[0007] error creating migrate instance: cannot create migrate instance: Data Error: {"path":"$.args","error":"restricted access : admin only","code":"access-denied"}
```
OTOH it works with  the `--admin-secret` flag:
```
❯ hasura migrate create init-schema --from-server --admin-secret $HASURA_GRAPHQL_ADMIN_SECRET
INFO Migrations files created                      name=init-schema version=1598767824038
```
