### ISSUE TITLE
[CLI] Custom environment variables don't work in metadata files

### ISSUE THREAD

**Issue by samuela** [hasura/graphql-engine#5691]
I have a `remote_schemas.yaml` file:
```yaml
- name: api
  definition:
    url: "{{ API_GRAPHQL_ENDPOINT }}"
    timeout_seconds: 60
```
based on the docs here: https://hasura.io/blog/moving-from-local-development-staging-production-with-hasura/. I have the `` environment variable set, but the hasura CLI is still not happy:
```
❯ API_GRAPHQL_ENDPOINT=https://7asdf8.ngrok.io/graphql hasura metadata apply --admin-secret $HASURA_GRAPHQL_ADMIN_SECRET
FATA[0005] failed to apply metadata: cannot apply metadata on the database: [parse-failed] not a valid URI ($[1].remote_schemas[0].definition.url) 
```
And dropping the quotes
```
    url: {{ API_GRAPHQL_ENDPOINT }}
```
doesn't work either:
```
❯ API_GRAPHQL_ENDPOINT=https://7asdf8.ngrok.io/graphql hasura metadata apply --admin-secret $HASURA_GRAPHQL_ADMIN_SECRET
FATA[0004] failed to apply metadata: cannot apply metadata on the database: yaml: invalid map key: map[interface {}]interface {}{"API_GRAPHQL_ENDPOINT":interface {}(nil)} 
```

**Comment by samuela** [comment]
Also doesn't work:
```
url: ${API_GRAPHQL_ENDPOINT}
```

**Comment by arjunyel** [comment]
Should be

```
- name: api
  definition:
    url_from_env: API_GRAPHQL_ENDPOINT
```

**Comment by tirumaraiselvan** [comment]
For remote schemas, the metadata doesn't support `{{ }}`` style env templating yet. Pls see this issue for that feature: https://github.com/hasura/graphql-engine/issues/2483

**Comment by John0x** [comment]
> For remote schemas, the metadata doesn't support `{{ }}`` style env templating yet. Pls see this issue for that feature: #2483

For that the env var has to exist on the server (where hasura is running). Is there a way to only have it defined for the cli (using .env file for example) and then be replaced during the metadata apply? Like templating?

**Comment by henningko** [comment]
To elaborate on @John0x' comment—we  keep prod/dev/test migrations separate from the infrastructure that sets up Hasura on AWS Fargate. We also have separate remote schema URLs for prod/dev/test. We need to be able to set those URLs in the metadata without redeploying/modifying the infrastructure repository.
The ideal way would be to run `hasura metadata apply` from the migration repository with the URLs set as environment variables on the machine running the hasura cli. Any thoughts on how we could achieve this?

**Comment by lughino** [comment]
This is a very important feature for us as well.
Any ETA for enabling it?

**Comment by samuela** [comment]
> Should be
> 
> ```
> - name: api
>   definition:
>     url_from_env: API_GRAPHQL_ENDPOINT
> ```

It's not immediately clear to me if this means that the `API_GRAPHQL_ENDPOINT` variable will be read and set at the time of `hasura metadata apply` or if hasura will look up the `API_GRAPHQL_ENDPOINT` variable at runtime. Can you clarify or is it discussed in the docs somewhere?

**Comment by OllyDS** [comment]
I've run into this issue - is there a solution?

In the `databases.yaml` file I need to have a dynamic url so would like to use the following:

```
database_url:
    from_env: HASURA_GRAPHQL_DATABASE_URL
```

But I get the following error `Inconsistent object: environment variable 'HASURA_GRAPHQL_DATABASE_URL' not set`. It's unclear how this should be set.

**Comment by DomVinyard** [comment]
Any progress on this?

**Comment by arjunyel** [comment]
Hi friend, you should be able to set the environment variable in the Hasura docker container, what's not working for you?

**Comment by johndevs** [comment]
We have a schema that is named differently in our staging environment than in production and would need to replace the schema mapping depending on environment. For this we would like the add a env-variable as the schema. 

We implemented this using @henningko's approach, but it has bad developer UX, as any change to the metadata requires us to ensure the metadata variables are not replaced.

**Comment by Maksat-luci** [comment]
> I've run into this issue - is there a solution?
> 
> In the `databases.yaml` file I need to have a dynamic url so would like to use the following:
> 
> ```
> database_url:
>     from_env: HASURA_GRAPHQL_DATABASE_URL
> ```
> 
> But I get the following error `Inconsistent object: environment variable 'HASURA_GRAPHQL_DATABASE_URL' not set`. It's unclear how this should be set.

hello, can you fix this problem? 
" Inconsistent object:            
 environment variable            
 'HASURA_GRAPHQL_DATABASE_URL'   
 not set
"

**Comment by SamirTalwar** [comment]
@Maksat-luci and others, have you set the environment variable for the Hasura GraphQL Engine server container? (Remember that the server needs to know the environment variable, not the CLI.)

Can you share how you are starting the HGE server, please?

**Comment by Maksat-luci** [comment]
> @Maksat-luci and others, have you set the environment variable for the Hasura GraphQL Engine server container? (Remember that the server needs to know the environment variable, not the CLI.)
> 
> Can you share how you are starting the HGE server, please?

do you mean docker compos container?
```
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.18.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ACTION_BASE_URL: "http://localhost:3000"
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      #HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
 ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
     ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:

```
