### ISSUE TITLE
JWTIssuedAtFuture because Docker Image uses UTC

### ISSUE THREAD

**Issue by ecumene** [hasura/graphql-engine#5734]
Hello!

I get these errors when attempting to use `graphql-engine` at my timezone (NDT)
```
graphql-engine_1  | {"type":"websocket-log","timestamp":"2020-09-07T01:54:34.129+0000","level":"error","detail":{"event":{"type":"operation","detail":{"request_id":null,"operation_id":"2","query":null,"operation_type":{"type":"proto_err","detail":"cannot start as connection_init failed with : Malformed Authorization header"},"operation_name":null}},"connection_info":{"websocket_id":"7cabb022-3ee3-46d8-9e91-7555bb9f4c10","token_expiry":null,"msg":null},"user_vars":null}}
```

When I switch my system timezone to UTC I get this:
```
graphql-engine_1  | {"type":"websocket-log","timestamp":"2020-09-07T01:54:34.129+0000","level":"info","detail":{"event":{"type":"accepted"},"connection_info":{"websocket_id":"96327924-1c26-404a-84e0-093e2f245f63","token_expiry":null,"msg":null},"user_vars":null}}
```

Then my data loads fine. I'm _assuming_ this is because it's in a docker container.

Here's my `graphql-engine` in `docker-compose.yml`:
```
graphql-engine:
  image: hasura/graphql-engine:v1.3.1
  ports:
  - "8080:8080"
  depends_on:
  - "postgres"
  restart: always
  env_file:
    - ./.env
```

EDIT: For reproducing, this happens between 11PM-12AM (NDT) in my experience. It's fine during the day
