### ISSUE TITLE
Failing to connect graphql_engine to my mySQL container

### ISSUE THREAD

**Issue by thomasfaller** [hasura/graphql-engine#5782]
Hey folks,
I have the following Docker container running :

```
version: "3.7"
services:
    db:
        image: mysql:8.0.14
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - "./data:/var/lib/mysql:rw"
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 9090:80
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=3000000000

```

Using the example from the docs I'm trying to launch a graphql_engine container to connect to my mySQL container so I have the following :

```
version: "3.6"
services:
    postgres:
        image: postgres:12
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgrespassword
    graphql-engine:
        image: hasura/graphql-engine:pull5655-633f084f
        ports:
            - "8080:8080"
        depends_on:
            - "postgres"
        command:
            - graphql-engine
            - --mysql-host
            - "127.0.0.1"
            - --mysql-user
            - "admin"
            - --mysql-port
            - "3306"
            - --mysql-dbname
            - "db_test"
            - --mysql-password
            - "admin"
            - serve
        restart: always
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
            ## enable the console served by server
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
            ## enable debugging mode. It is recommended to disable this in production
            HASURA_GRAPHQL_DEV_MODE: "true"
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
            ## uncomment next line to set an admin secret
            # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
    db_data:

```

I assume I'm not using the expected `--mysql-host` value here since I only get errors about the container not being able to connect to mysql.

If I use `'127.0.0.1'` or `localhost` I get a `Can't connect to local MySQL server through socket` error

My mySQL container is available on my host-machine localhost:3306 though via a SQL client.

Any pointers would be greatly appreciated 😄 Thanks!

**Comment by thomasfaller** [comment]
Alright so I found the trick which is to add
```
    network_mode: "host"
```
in the docker-compose for the graphql_engine service so the logs tell me that it's connected to mysql but now - I guess because of the newly added network_mode it's not connecting to the postgres service 😢  so I get

```json
{"internal":"could not translate host name \"postgres\" to address: Name or service not known\n","path":"$","error":"connection error","code":"postgres-error"}
```

**Comment by thomasfaller** [comment]
Nervermind, sorted it, thanks

**Comment by Miyou** [comment]
@thomasfaller Mind sharing how you solved it? I'm getting the same error "could not translate host name postgres" when using the cli-migrations-v2 docker image, but not when using the regular one. Would be nice if you could share how you solved the problem!

**Comment by benmarte** [comment]
I'm also running into this issue what's interesting is the different error messages based on which host I use.

If I use 127.0.0.1 or my actual plan id 192.168.2.191 I get this error:

```
graphql-engine_1  | {"type":"startup","timestamp":"2021-02-16T14:18:13.714+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":4000},"enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump","developer"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":false,"port":8080}}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-02-16T14:18:13.714+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:...@postgres:5432/postgres"}}}
graphql-engine_1  | {"type":"pg-client","timestamp":"2021-02-16T14:18:19.116+0000","level":"warn","detail":{"message":"postgres connection failed, retrying(0)."}}
graphql-engine_1  | {"type":"pg-client","timestamp":"2021-02-16T14:18:24.562+0000","level":"warn","detail":{"message":"postgres connection failed, retrying(1)."}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-02-16T14:18:24.562+0000","level":"error","detail":{"kind":"catalog_migrate","info":{"internal":"could not translate host name \"postgres\" to address: Name or service not known\n","path":"$","error":"connection error","code":"postgres-error"}}}graphql-engine_1  | Connected to MySQL!
graphql-engine_1  | {"internal":"could not translate host name \"postgres\" to address: Name or service not known\n","path":"$","error":"connection error","code":"postgres-error"}
```

If I use localhost I get this one:

```
graphql-engine_1  | graphql-engine: ConnectionError {errFunction = "connect", errNumber = 2002, errMessage = "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"}
```

**Comment by AvivShuker** [comment]
Did anyone manage to solve this? i'm also getting this error :(

**Comment by nerdvibe** [comment]
Solved by adding `network_mode: host` in both postgres and graphql-engine service. **Then** you need to change the HASURA_GRAPHQL_DATABASE_URL connection string in the same file.

Therefore it becomes:
`HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@127.0.0.1:5432/postgres`

**Comment by khan297** [comment]
B

**Comment by benmarte** [comment]
> Solved by adding `network_mode: host` in both postgres and graphql-engine service. **Then** you need to change the HASURA_GRAPHQL_DATABASE_URL connection string in the same file.
> 
> Therefore it becomes:
> `HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@127.0.0.1:5432/postgres`

Awesome will confirm if this solves the issue when I test later this week.

Thanks.

**Comment by khan297** [comment]
ت

**Comment by benmarte** [comment]
> Solved by adding `network_mode: host` in both postgres and graphql-engine service. **Then** you need to change the HASURA_GRAPHQL_DATABASE_URL connection string in the same file.
> 
> Therefore it becomes:
> `HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@127.0.0.1:5432/postgres`

Can you post your whole docker-compose file? I added network_mode:host to both the postgres and graphql-engine and now I get this error:

```
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
```

Here is what my docker-compose file looks like:

```
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    network_mode: host
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:pull5655-633f084f
    ports:
    - "8080:8080"
    network_mode: host
    depends_on:
    - "postgres"
    command:
    - graphql-engine
    - --mysql-host 
    - <mysql-host>
    - --mysql-user 
    - <mysql-user>
    - --mysql-port 
    - <mysql-port>
    - --mysql-dbname 
    - <mysql-dbname>
    - --mysql-password 
    - <mysql-password>
    - serve 
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@127.0.0.1:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```

Thanks.
