### ISSUE TITLE
Cron schedule attribute containing environment variable

### ISSUE THREAD

**Issue by RuBAN-GT** [hasura/graphql-engine#5793]
Hello everyone! 

I'm trying to configure cron triggers with dynamic schedule taking from environment variables like that:

```yml
- name: remove_old_data
  webhook: '{{EVENTS_HANDLER_URL}}/removeOldData'
  schedule: '{{REMOVE_OLD_DATA_SCHEDULE}}'
  include_in_metadata: true
  payload: {}
```

But Graphql Engine doesn't accept/handle variables from schedule attribute.

Could you please advice how I can fill this parameter dynamically?

Thank you!
