### ISSUE TITLE
Remote Joins for Remote Schema Response

### ISSUE THREAD

**Issue by John0x** [hasura/graphql-engine#5801]
Hey, I expected the remote joins to support responses as well and not just arguments of an query. Will this be supported in the future?

One of my remote schemas responses contains the userId, which I would like to join with the "user" table, so that on the response someone could also query the user object.

**Comment by esseswann** [comment]
This might cause a circular reference. It's explained here https://github.com/hasura/graphql-engine/issues/2494#issuecomment-675498002

**Comment by tirumaraiselvan** [comment]
This is remote schema to db join which is part of the roadmap and will be possible soon (Action relationships are kind of similar btw).

**Comment by John0x** [comment]
Great, thank you :)
Is there a rough a ETA on when that feature will arrive?

**Comment by seanaye** [comment]
Just want to clarify that this is a sort of 'right join' where a remote schema can return a key then hasura will look up that key and return the data? The opposite of current remote join where hasura sends key and remote schema resolves, this would allow remote schema to pass key back to hasura and hasura would resolve? Beacuse that would be amazing

**Comment by karibertils** [comment]
Looking forward to this feature

**Comment by JCMais** [comment]
I was trying to do exactly that but found out it's not supported yet. This is an important feature for anyone using remote schemas, especially so if using apollo client in the frontend.

Use case:

- Remote schema has an `UpdateUser` mutation that returns the `updated_user_id: String` field.
- In Hasura, add remote join, extending this mutation with a new field, `updatedUser: User`, which joins `UpdateUser.updated_user_id` to the `user.id` record. Just like it's possible with Actions.
- This would allow GraphQL clients, like the Apollo Client, to automatically update the record locally, without having to refetch the data.


Is there any update related to when this feature is going to become available? Or if it's planned at all.

**Comment by tirumaraiselvan** [comment]
> Is there any update related to when this feature is going to become available? Or if it's planned at all.

This is definitely planned and high up in our priority.

**Comment by WonderPanda** [comment]
> I was trying to do exactly that but found out it's not supported yet. This is an important feature for anyone using remote schemas, especially so if using apollo client in the frontend.
> 
> Use case:
> 
> * Remote schema has an `UpdateUser` mutation that returns the `updated_user_id: String` field.
> * In Hasura, add a remote join extending this mutation with a new field, `updatedUser: User`, which joins `UpdateUser.updated_user_id` to the `user.id` record. Just like it's possible with Actions.
> * This would allow GraphQL clients, like the Apollo Client, to automatically update the record locally, without having to refetch the data.
> 
> Is there any update related to when this feature is going to become available? Or if it's planned at all.
> Anything the community can do to help with the development of this?

This is the exact use case that I've run into when using remote schemas and as its supported through Hasura Actions I really hope that it drops soon! This is basically the last missing piece for incredibly deep integration with Remote Schemas that could make things ready for primetime

**Comment by Ant59** [comment]
Will we likely see this merged soon?

**Comment by ahobsonsayers** [comment]
This is finally implemented in Hasura v.2.5.0 🎉🎉🎉 Thanks to all those who were involved in getting this out, it works great!

You can see some notes on how to make remote schema relationships via the API in the v2.5.0 release changelog [here](https://github.com/hasura/graphql-engine/releases/tag/v2.5.0) but for anyone else that likes to manage metadata via yaml files and use the Hasura CLI, here is what i did to get remote schema to database relationships working.

In your `remote_schemas.yaml`
```yaml
- name: my_remote_schema
  definition:
    url_from_env: MY_GRAPHQL_ENDPOINT
    forward_client_headers: true
    timeout_seconds: 60

  remote_relationships:
    - type_name: MyType
      relationships:
        - name: user
          definition:
            to_source:
              relationship_type: object
              source: my_db
              table:
                schema: public
                name: my_table
              field_mapping:
                remote_field: table_column
```
