### ISSUE TITLE
support pg_dump for Postgres 13

### ISSUE THREAD

**Issue by phamquyhai** [hasura/graphql-engine#5836]
I'm using Hasura ver 1.3.2. When I call `hasura migrate ...`, I got an error.
```
cannot fetch schema dump: [unexpected] error while executing pg_dump: pg_dump: error: server version: 13rc1; pg_dump version: 12.2 (Debian 12.2-2.pgdg90+1)
```

I think Hasura currently only supports pg ver 12 & below.

**Comment by GavinRay97** [comment]
Hey, unfortunately I am not able to reproduce this:

![image](https://user-images.githubusercontent.com/26604994/94297306-4d62f500-ff32-11ea-86ec-bd22b160edd0.png)

```yaml
version: "3.6"
services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    ports:
      - "8090:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

volumes:
  db_data:
```

Can you link a repo here with a reproduction?

**Comment by phamquyhai** [comment]
@GavinRay97 
I used posgress from postgis image. cli and version hasura same you.
i got errors when I call hasura migrate
```
version: '3.6'
services:
  postgres:
    image: postgis/postgis:13-3.0-alpine
    restart: always
```
