### ISSUE TITLE
Hasura console is not able to reach your Hasura GraphQL engine instance. Please ensure that your instance is running and the endpoint is configured correctly.

### ISSUE THREAD

**Issue by tavakoli-ali** [hasura/graphql-engine#5905]
I hade up and run docker image but last week, all of the sudden, it had been down.
I got this error for 1 week and try all things and didn't work, I removed the docker file and image, container and install fresh but also didn't work, and got this message: DB schema loading failed
Failed to fetch.
docker : 

`version: '3.7'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DATABASE: postgres
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
                  #HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@host.docker.internal:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
volumes:
  db_data:
`

_Originally posted by @tavakoli-ali in https://github.com/hasura/graphql-engine/issues/2378#issuecomment-703175933_

**Comment by rolivegab** [comment]
Hi!
I've a configuration that works for me:

```
version: '3.7'
services:
  hasura:
    image: docker.io/hasura/graphql-engine:v1.3.2
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
    ports:
      - 8080:8080
  
  postgres:
    image: docker.io/postgres:alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
```

maybe its because, accordingly to postgres image docker hub docs ([https://hub.docker.com/_/postgres](https://hub.docker.com/_/postgres)), database variable name must be `POSTGRES_DB`.

**Comment by tirumaraiselvan** [comment]
Can you post the container logs please?

**Comment by sdil** [comment]
I have the same problem. This is my docker-compose.yml file:

```
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: xxx
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    - "hasura-firebase-auth-webhook"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:xxx@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_CORS_DOMAIN: "http://localhost:3000, http://localhost:8080"
      ## Set a secure admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: xxx
      HASURA_GRAPHQL_AUTH_HOOK: http://hasura-firebase-auth-webhook:8081/auth
```

I am able to see the console at `localhost:8080/console/login`

But when I run `hasura console --endpoint http://localhost:8080 --admin-secret xxx`, it opens `localhost:9695` and show the following error

![image](https://user-images.githubusercontent.com/461537/96565585-24e2d680-12f7-11eb-8dfb-2a09e83584ed.png)

Any idea why it happened and how to fix this?
