### ISSUE TITLE
Metadata import fails with parsing error

### ISSUE THREAD

**Issue by dewaldabrie** [hasura/graphql-engine#5968]
I'm trying to track a particular table, export the metadata, then have it apply automatically on startup of the cli image. 
Below is my docker-compose file and sql startup script, as well as the metadata file. I get the following error:

```
hasura_1    | {"timestamp":"2020-10-08T09:33:28.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-apply","info":"applying metadata from /hasura-metadata"}}
...
hasura_1    | time="2020-10-08T09:33:30Z" level=fatal msg="failed to apply metadata: cannot apply metadata on the database: [parse-failed] key \"tables\" not found ($[1])"
```

docker-compose.yml
```
version: '3.7'

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  hasura:
#    image: hasura/graphql-engine:v1.3.2
    image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
    volumes:
      - ./hasura_server/metadata:/hasura-metadata
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/test
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: letmein
```

init.sql
```
create table sometable(id int);
```

metadata.json
```
{
  "version": 2,
  "tables": [
    {
      "table": {
        "schema": "public",
        "name": "sometable"
      }
    }
  ]
}
```

folder structure
![image](https://user-images.githubusercontent.com/272353/95532950-9edcab00-0a2d-11eb-9cbd-80078be94224.png)

**Comment by tirumaraiselvan** [comment]
I am not sure but I tried your docker-compose and it succeeds:

```
{"timestamp":"2020-10-13T14:20:35.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-apply","info":"applying metadata from /hasura-metadata"}}
{"level":"info","msg":"Applying metadata...","time":"2020-10-13T14:20:35Z"}
{"type":"http-log","timestamp":"2020-10-13T14:20:34.960+0000","level":"info","detail":{"operation":{"query_execution_time":2.21859e-3,"user_vars":{"x-hasura-role":"admin"},"request_id":"69936c2b-7013-48b4-8438-37debee07590","response_size":68,"request_read_time":4.815e-6},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/query","ip":"127.0.0.1","method":"POST","content_encoding":"gzip"}}}
```

**Comment by dewaldabrie** [comment]
@scriptonist Please note on the first log line that I posted it says `applying metadata from /hasura-metadata` which seems to indicate that it could find the file in the dir structure?

Could you please give me some indication of what the directory structure should look like? That way I can tunnel into the image and see if it's set up that way.

I added `command: ["hasura", "init", "."]` do my docker-compose manifest with no effect. 

docker-compose.yaml:
```
version: '3.7'

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  hasura:
#    image: hasura/graphql-engine:v1.3.2
    image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
    volumes:
      - ./hasura_server/metadata:/hasura-metadata
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    restart: always
    command: ["hasura", "init", "."]
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/test
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: letmein
```
