### ISSUE TITLE
migration file for updated event trigger missing delete_event_trigger

### ISSUE THREAD

**Issue by tibotiber** [hasura/graphql-engine#5999]
Hello,

I've updated the configuration for an existing event trigger and the migration that was generated only had a `create_event_trigger`, no `delete_event_trigger`. This resulted in failing migrations due to unique name constraint. 

I've fixed it here and do not require further help but wanted to share this in case that's a bug you've not been notified of yet. I've tried searching the issues but could not find a report. Hope I searched well enough ;).

Note: i'm on v1.3.2.

Cheers and ❤️ hasura!

**Comment by tirumaraiselvan** [comment]
@tibotiber I am not able to reproduce this. I am guessing you are in config v1 (version: 1 in `config.yaml`)

Could you try this again or on a fresh project?

**Comment by tibotiber** [comment]
I have no specified version in `config.yaml` so I guess that'd be v1(?)

I've tried again on my project and I consistently get a migration missing the delete. Example below:

```yaml
- args:
    delete: null
    enable_manual: true
    headers:
    - name: Authorization
      value_from_env: SMPLRTOKEN
    - name: update-phone-endpoint
      value_from_env: UPDATE_PHONE_WEBHOOK
    insert:
      columns: '*'
    name: create_bare_account
    replace: true
    retry_conf:
      interval_sec: 10
      num_retries: 2
      timeout_sec: 60
    table:
      name: users
      schema: public
    update: null
    webhook: null
    webhook_from_env: CREATE_BARE_ACCOUNT_WEBHOOK
  type: create_event_trigger
```

Anything else i can provide that may help?
