### ISSUE TITLE
Events stuck in locked state, never attempted.

### ISSUE THREAD

**Issue by njaremko** [hasura/graphql-engine#6025]
Hello,

I've been seeing this for a little while and ignoring it, but I figured I should bring it up. I have an event trigger that gets ~22,000 invocations a day on a single hasura instance. Of those, ~15-50 of these events end up as being locked, with no delivery, nor error. In my use case, this isn't a huge deal, since the next time the event is triggered, it will contain the relevant information from the previous unsent event, but I think hasura promises at least once delivery, so I figured you might be interested. Let me know if there's anything specific you'd like to know to help debug.

Something similar seems to have happened before, but it was assumed that it was happening due to a non-graceful shutdown with multiple hasura instances. In this case, there's only one hasura instance, and it was not shutdown at any point.

https://github.com/hasura/graphql-engine/issues/2896
https://github.com/hasura/graphql-engine/issues/3548

Event trigger metadata:
```
event_triggers:
  - name: companies
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns:
        - company_status_id
        - id
        - display_name
        - internal_name
        - synced_at
    retry_conf:
      num_retries: 1
      interval_sec: 10
      timeout_sec: 60
    webhook_from_env: SERVERLESS_WEBHOOK_ENDPOINT
    headers:
    - name: X-HASURA-ACTION-SECRET
      value_from_env: HASURA_ACTION_SECRET
```
