### ISSUE TITLE
Console UI: Allow creating Computed Field for Views, add to Docs

### ISSUE THREAD

**Issue by GavinRay97** [hasura/graphql-engine#6168]
Currently, the only way to add a Computed Field is through Metadata API or manually editing `tables.yaml` and re-running `metadata apply` with the CLI.

Also, the docs page is not very clear about whether it's a possibility to add Computed Fields to a View or not.

**Current Example workflow:**

```sql
CREATE VIEW artists_view AS
  SELECT * FROM artists;
```

```sql
CREATE FUNCTION filter_artist_view_albums(artist_view_row artists_view, search text)
RETURNS SETOF albums AS $$
  SELECT *
  FROM albums
  WHERE artist_id = artist_view_row.id
    AND title ilike ('%' || search || '%')
$$ LANGUAGE sql STABLE;
```

```http
POST http://localhost:8080/v1/query HTTP/1.1
Content-Type: application/json
X-Hasura-Role: admin

{
  "type": "add_computed_field",
  "args": {
    "table": {
      "schema": "public",
      "name": "artists_view"
    },
    "name": "filtered_albums",
    "definition": {
      "function": {
        "schema": "public",
        "name": "filter_artist_view_albums"
      },
      "table_argument": "artist_view_row"
    }
  }
}
```

(Or)

```yaml
 - table:
     schema: public
     name: artists_view
   computed_fields:
   - name: filter_albums
     definition:
       function:
         schema: public
         name: filter_artist_view_albums
       table_argument: artist_view_row
     comment: ""
```
