### ISSUE TITLE
Auto applying migration tables are untracked

### ISSUE THREAD

**Issue by siddisking** [hasura/graphql-engine#6246]
Hi,

I am trying to auto-apply the migration using `hasura/graphql-engine:v1.3.3.cli-migrations-v2`.

I am creating migrations and metadata using these commands 
`hasura migrate create \"init\" --from-server`
`hasura metadata export`

my docker-compose looks like this:
```
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3.cli-migrations-v2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    volumes:
      - ./migrations:/migrations
      - ./metadata:/metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_MIGRATIONS_DIR: "./migrations"
      HASURA_GRAPHQL_METADATA_DIR: "./metadata"
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:

```

**the migrations and metadata folders are in the same folder as the docker-compose.yml file**

whenever I deploy the docker it shows the table that I migrated under **untracked**

I believe it should be tracked and should be exposed to graphql queries but they are not

<img width="1280" alt="Screen Shot 2020-11-24 at 2 19 35 PM" src="https://user-images.githubusercontent.com/4956864/100070564-180a5300-2e60-11eb-825b-7a98d4adf2a4.png">

my config.yaml

```
version: 2
endpoint: http://localhost:8080
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
```
