### ISSUE TITLE
Opt out of pre-release notifications failed

### ISSUE THREAD

**Issue by samuela** [hasura/graphql-engine#6268]
Just got this error with a fresh hasura instance:
```
Opt out of pre-release notifications failed
Internal error: missing hasura_uuid
```
![Screen Shot 2020-11-28 at 5 25 51 PM](https://user-images.githubusercontent.com/226872/100529705-18c42180-319f-11eb-815d-585b2ed80c1e.png)

After launching this docker compose setup:
```yaml
# Development config for postgres/hasura.

# TODO: set up metadata stuff...

version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.1
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: hasurasecret
volumes:
  db_data:
```

I don't see anything exciting in the logs however.
