### ISSUE TITLE
Support for Mac M1

### ISSUE THREAD

**Issue by theswerd** [hasura/graphql-engine#6337]
# Add Hasura Support for Mac M1

The Hasura Docker container does not work on the Mac M1 Docker preview.

When running it I get the following error:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
Is it possible to add a built for the **linux/arm64/v8** platform?

**Comment by andoks** [comment]
Related to #1266

**Comment by cuonghuynh** [comment]
I had another error on Mac M1 also:
`graphql-engine_1 | qemu: uncaught target signal 4 (Illegal instruction) - core dumped`
Does anyone has the solution for it?

**Comment by cakemountain** [comment]
Bump, also experiencing this on Mac M1 with the hasura/graphql-engine:v1.3.1: `graphql-engine_1 | qemu: uncaught target signal 4 (Illegal instruction) - core dumped` - Hasura hangs and doesn't serve requests.

**Comment by cakemountain** [comment]
@cuonghuynh did you end up finding a solution?

**Comment by mwarger** [comment]
@cuonghuynh @cakemountain I'm also seeing the `core dumped` error, but I'm not seeing it all the time.  Apparently only for certain queries in my application.. I haven't narrowed down which ones, though.

**Comment by pie6k** [comment]
I'm getting similar, but a bit different error:

```
hasura_1    | {"timestamp":"2021-03-01T14:14:23.000+0000","level":"info","type":"startup","detail":{"kind":"installing cli-ext plugin","info":""}}
hasura_1    | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

**Comment by cakemountain** [comment]
@mwarger @pie6k @cuonghuynh I ended up finding a forked version that supports ARM - https://hub.docker.com/r/fedormelexin/graphql-engine-arm64/tags. I just popped that into my `graphql-engine`'s `image:` in docker-compose.yml and it worked like a charm, no more issues.

**Comment by mwarger** [comment]
> ... I ended up finding a forked version that supports ARM - https://hub.docker.com/r/fedormelexin/graphql-engine-arm64/tags. I just popped that into my `graphql-engine`'s `image:` in docker-compose.yml and it worked like a charm, no more issues.

@cakemountain 
If I try that, I get an error: 

`
ERROR: for graphql-engine  Cannot start service graphql-engine: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "graphql-engine": executable file not found in $PATH: unknown
`

**Comment by cakemountain** [comment]
@mwarger not familiar with that error but it seems potentially unrelated to the issue here. Have you seen [this](https://stackoverflow.com/questions/27158840/docker-executable-file-not-found-in-path)?

**Comment by pie6k** [comment]
I've used `fedormelexin/graphql-engine-arm64` and it worked, but there are other issues eg. console not loading with bunch of errors:
<img width="939" alt="Screenshot 2021-03-02 at 13 08 25" src="https://user-images.githubusercontent.com/7311462/109646357-61052e00-7b58-11eb-8ac1-a416fdc4446d.png">

IT seems to be related to `cdnAssets` being always set to false on this arm64 image.

**Comment by cuonghuynh** [comment]
```  
graphql-engine:
    image: fedormelexin/graphql-engine-arm64
```

It worked for me.

**Comment by mwarger** [comment]
@cakemountain @pie6k I was able to get this working... https://github.com/melehin/graphql-engine-arm64/issues/3

**Comment by kiily** [comment]
Thanks for these suggestions. I can confirm the console issue with the image above but it does the job for the server. Although, you are blocked as soon as you want to interact with the hasura UI

**Comment by joshuarobs** [comment]
Docker was recently updated to work for the new M1 Macs. Does this have any effect on Hasura working too with M1 Macs?

**Comment by Owpac** [comment]
Any news on this issue? 

I was waiting for a stable Docker version for M1 to give some feedbacks. Sadly, official docker images of Hasura don't work on M1 yet. I tried this image https://hub.docker.com/r/fedormelexin/graphql-engine-arm64/ which starts Hasura properly without errors. Is this possible to make official images work too, thanks to his work? 

To be honest, I don't really know how hard is this task, but it would be amazing to be able to use official Hasura with Docker on my M1.

**Comment by formvoltron** [comment]
still open??  aren't the hasura team using mac M1s?  you should be!

**Comment by watadarkstar** [comment]
I'm also having this error show up:

```
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
```

**Comment by watadarkstar** [comment]
> I've used `fedormelexin/graphql-engine-arm64` and it worked, but there are other issues eg. console not loading with bunch of errors:
> <img alt="Screenshot 2021-03-02 at 13 08 25" width="939" src="https://user-images.githubusercontent.com/7311462/109646357-61052e00-7b58-11eb-8ac1-a416fdc4446d.png">
> 
> IT seems to be related to `cdnAssets` being always set to false on this arm64 image.

@pie6k Did you ever figure this out? I ran into the same issue.

**Comment by kiily** [comment]
@watadarkstar only solution I have found is to enable the console in docker compose and then access via the docker endpoint. The `hasura console` command (which is the recommended way of running it) just does seem to work ... Luckily, I have a hosted instance I can run my migrations on but would be great to get support from the hasura team for sure 🙏

**Comment by watadarkstar** [comment]
> > Thanks for these suggestions. I can confirm the console issue with the image above but it does the job for the server. Although, you are blocked as soon as you want to interact with the hasura UI
> > UPDATE:
> > Running the latest version [here](https://hub.docker.com/r/fedormelexin/graphql-engine-arm64/tags?page=1&ordering=last_updated) the problem persists. However, you can get around it by setting `HASURA_GRAPHQL_ENABLE_CONSOLE=true` in your environment. You can then access the console on your localhost `http://localhost:<port>/console`. Not ideal, but works for the time being.
> 
> @watadarkstar only solution I have found is to enable the console in docker compose and then access via the docker endpoint. The `hasura console` command (which is the recommended way of running it) just does seem to work ... Luckily, I have a hosted instance I can run my migrations on but would be great to get support from the hasura team for sure 🙏

Thanks @kiily I figured it out here: https://github.com/melehin/graphql-engine-arm64/issues/6#issuecomment-827633587

**Comment by punkratz312** [comment]
still not working without m1 fix image:

![image](https://user-images.githubusercontent.com/8830888/116389618-711a5080-a81d-11eb-9016-43bd082d0cda.png)


![image](https://user-images.githubusercontent.com/8830888/116389666-7d061280-a81d-11eb-88ec-4a88b3993e02.png)


workaround image:

![image](https://user-images.githubusercontent.com/8830888/116389770-a1fa8580-a81d-11eb-804c-abd967ca3be6.png)

harusa works fine:

![image](https://user-images.githubusercontent.com/8830888/116389828-b2126500-a81d-11eb-8661-455b90d4488e.png)

**Comment by TheMrZZ** [comment]
Still no update on this one? Our local dev environments are only failing to launch Hasura, whereas all services (Docker, K8s, Go) are now compatible.

Could we at least have an ETA or an expected release date?

**Comment by rsaphala** [comment]
Having the same issue here

**Comment by omarduarte** [comment]
Having same issue

**Comment by elitan** [comment]
I will hopefully have the same issue soon! 😬

**Comment by jmarbutt** [comment]
Same issue. We all will celebrate when this gets fixed

**Comment by coloradocolby** [comment]
Genuinely hope we can get a fix out for this soon!

In the meantime, I can share what I've done to bypass the issue. For those who have a spare computer lying around, I clone my project on that computer, installed the hasura-cli, and ran the failing commands with the `--endpoint` flag pointed at the troubled computers private ip. Good luck!

**Comment by ianschmitz** [comment]
I've been running the v2 alpha on my M1 Macbook Pro for a week or so now. Here's what i used to run:

```sh
docker run --platform linux/amd64 --name=hasura -d -p 8080:8080 \
       -e HASURA_GRAPHQL_ADMIN_SECRET=secret \
       -e HASURA_GRAPHQL_DATABASE_URL=postgres://user:pass@host.docker.internal:5432/db_name \
       -e HASURA_GRAPHQL_DEV_MODE=true \
       -e HASURA_GRAPHQL_ENABLE_CONSOLE=true \
       hasura/graphql-engine:v2.0.0-alpha.11
```

**Comment by zwily** [comment]
I've been successfully running the official Docker image (the 2.0 alpha series) on an M1 for several weeks now. The trick for me was giving Docker 8GB of RAM in the D4M config. Without that, it would core dump.

Native arm64 images would be incredible though.

**Comment by KATT** [comment]
Thanks @zwily, seem to have been the missing piece for me. Still doesn't seem to work with `~1.3` which I'm running in prod but I got it running with `v2.0.0-alpha.11`.

Here's my full workaround:

<details><summary>1. Crank up the memory in Docker app</summary>

## Go to settings in Docker app
<img width="1362" alt="Screenshot_2021-05-30_at_18_54_31" src="https://user-images.githubusercontent.com/459267/120113070-199f3580-c179-11eb-976b-f716389d1326.png">

## Crank memory up

<img width="1362" alt="Screenshot_2021-05-30_at_18_54_42" src="https://user-images.githubusercontent.com/459267/120113073-1c018f80-c179-11eb-912b-809a8caf8e37.png">

</details>
<details><summary>2. Update docker-compose.yaml</summary>

## `docker-compose.yaml`:
```yaml
version: '3.6'
services:
  postgres:
    image: postgres:12
    ports:
    # expose pg as port 5442 to not collide with other pg
    - "5442:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.11
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    platform: linux/amd64 # <-- magic sauce for m1
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: ${HASURA_GRAPHQL_ENABLED_LOG_TYPES}
      HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_REFETCH_INTERVAL: ${HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_REFETCH_INTERVAL}
volumes:
  db_data:
```

**Comment by tyhopp** [comment]
Updated to `v2.0.0-beta.1` today but it fails with `qemu: uncaught target signal 11 (Segmentation fault) - core dumped`. Reverting back to `v2.0.0-alpha.10`

**Comment by preetjdp** [comment]
@tyhopp Try this image out

It works well for me locally

https://hub.docker.com/layers/fedormelexin/graphql-engine-arm64/2.0.0-beta.1/images/sha256-b6e71320180fe222d62740f4e187032ac925046b534f5492a8cdb6eeed9ad7be?context=explore

**Comment by emdagon** [comment]
**FYI**: I started getting `qemu: uncaught target signal 11 (Segmentation fault) - core dumped` on my M1 when I tried to upgrade from `hasura/graphql-engine:v2.0.0-alpha.10` (which was working fine) to `hasura/graphql-engine:v2.0.0-beta.2`.

The upgrade works fine on my linux server.

**Comment by m3hari** [comment]
`v2.0.0-alpha` works for me the latest doesn't. of course, install rosetta and update memory like @KATT  explaind

**Comment by johnparn** [comment]
I also had problem with using v.1.3.3 so I was hoping for `hasura/graphql-engine:v2.0.1 ` but was faced with `qemu: uncaught target signal 11 (Segmentation fault) - core dumped` on my M1. 

However, after some tinkering it started to work with `hasura/graphql-engine:v1.3.3`. 

* Using Docker Desktop version 3.5.1 (3.5.1.7)
* In Docker I started with assigning D4M _8GB_ RAM. If lowering the RAM to 4GB it fails to start, but _6GB_ also works.
* Under _Experimental Feaures_ the option _Use the new Virtualization framework_ is unchecked. 
* Added `--platform linux/amd64` to the start command.

My working start command:

```sh
docker run -p 8080:8080 --platform linux/amd64 \
-e HASURA_GRAPHQL_DATABASE_URL=postgres://dbuser:dbpwd@host.docker.internal:5432/dbname \
-e HASURA_GRAPHQL_ENABLE_CONSOLE=true \
-e HASURA_GRAPHQL_JWT_SECRET='{"jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com","audience": "firebase-project","issuer": "https://securetoken.google.com/firebase-project"}' \
-e HASURA_GRAPHQL_ADMIN_SECRET=password  \
hasura/graphql-engine:v1.3.3
```

So far I haven't had any failing queries.

**Comment by dbj** [comment]
I am still having this issue. Would love to see a native aarch64 docker image.

**Comment by zwily** [comment]
From the lack of movement on this issue, I’m guessing Hasura hadn’t given out any M1s to their developers yet. 😀

**Comment by kuwjr** [comment]
Will there be any solution for this issue?

**Comment by m3hari** [comment]
This image works for me `fedormelexin/graphql-engine-arm64:v2.0.0.cli-migrations-v2`

Here is the full compose file https://github.com/m3hari/vue-graphql-starter/blob/master/api/docker-compose.yaml

**Comment by kuwjr** [comment]
> https://github.com/m3hari/vue-graphql-starter/blob/master/api/docker-compose.yaml

@m3hari It doesn't seem to work for me, any help?
<img width="1440" alt="Screenshot 2021-07-10 at 12 24 43" src="https://user-images.githubusercontent.com/53249257/125154872-e1c4de00-e179-11eb-85a9-21a4d6da1cdc.png">

**Comment by m3hari** [comment]
@kuwjr same docker-compose works fine, the DB start time is quite long which Hasura depends on, you need to wait if frob about a minute.

![image](https://user-images.githubusercontent.com/9920926/125212470-9846d100-e2e8-11eb-8e4b-9155f9e70d79.png)

**Comment by antholeole** [comment]
I cannot get the [`fedormelexin` ](https://hub.docker.com/r/fedormelexin/graphql-engine-arm64) container to work.... docker-compose hangs with:
```
graphql-engine_1  | {"type":"unstructured","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":"Thread checkForUpdates (re)started"}
graphql-engine_1  | {"type":"unstructured","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":"Thread SchemeUpdate.processor (re)started"}
graphql-engine_1  | {"type":"unstructured","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":"Thread asyncActionsProcessor (re)started"}
graphql-engine_1  | {"type":"schema-sync-thread","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":{"thread_type":"processor","info":{"message":"Schema Version changed with no notifications"}}}
```

and then never says anything ever again. When I try to hit `localhost:8080/console`, I end up with no HTML or anything - just a blank page with the following logged to console: 

```
GEThttp://localhost:8080/
[HTTP/1.1 404 Not Found 3ms]

The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.
```

<details>
  <summary>full logs for `docker-compose up`</summary>
  
```
graphql-engine_1  | {"type":"startup","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":4000},"enable_maintenance_mode":false,"enabled_log_types":["http-log","websocket-log","startup","webhook-log"],"server_host":"HostAny","enable_allowlist":false,"remote_schema_permissions":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"v1-boolean-null-collapse":false,"graceful_shutdown_timeout":60,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"infer_function_permissions":true,"experimental_features":[],"events_fetch_batch_size":100,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"websocket_compression_options":"NoCompression","console_assets_dir":null,"admin_secret_set":false,"port":8080,"websocket_keep_alive":"KeepAliveDelay {unKeepAliveDelay = Seconds {seconds = 5s}}"}}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:...@postgres:5432/postgres"}}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":{"kind":"catalog_migrate","info":"Already at the latest catalog version (46); nothing to do."}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":{"kind":"schema-sync","info":"Schema sync enabled. Polling at Milliseconds {milliseconds = 1s}"}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 21","instance_id":"9671eb7b-c9e6-4b6b-b34a-02f27d9f4e6c","message":"listener thread started"}}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 23","instance_id":"9671eb7b-c9e6-4b6b-b34a-02f27d9f4e6c","message":"processor thread started"}}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":{"kind":"event_triggers","info":"starting workers"}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":{"kind":"scheduled_triggers","info":"preparing data"}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":{"kind":"telemetry","info":"Help us improve Hasura! The graphql-engine server collects anonymized usage stats which allows us to keep improving Hasura at warp speed. To read more or opt-out, visit https://hasura.io/docs/latest/graphql/core/guides/telemetry.html"}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":{"kind":"server","info":{"time_taken":0.110043375,"message":"starting API server"}}}
graphql-engine_1  | {"type":"unstructured","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":"Thread SchemeUpdate.listener (re)started"}
graphql-engine_1  | {"type":"unstructured","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":"Thread asyncActionSubscriptionsProcessor (re)started"}
graphql-engine_1  | {"type":"unstructured","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":"Thread processScheduledTriggers (re)started"}
graphql-engine_1  | {"type":"unstructured","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":"Thread runTelemetry (re)started"}
graphql-engine_1  | {"type":"unstructured","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":"Thread ourIdleGC (re)started"}
graphql-engine_1  | {"type":"unstructured","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":"Thread processEventQueue (re)started"}
graphql-engine_1  | {"type":"unstructured","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":"Thread runCronEventsGenerator (re)started"}
graphql-engine_1  | {"type":"unstructured","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":"Thread checkForUpdates (re)started"}
graphql-engine_1  | {"type":"unstructured","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":"Thread SchemeUpdate.processor (re)started"}
graphql-engine_1  | {"type":"unstructured","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":"Thread asyncActionsProcessor (re)started"}
graphql-engine_1  | {"type":"schema-sync-thread","timestamp":"2021-07-29T16:05:52.518+0000","level":"info","detail":{"thread_type":"processor","info":{"message":"Schema Version changed with no notifications"}}}
```  

</details>

**Comment by jasonprado** [comment]
I saw Hasura CLI now supports ARM64 natively, that's progress. I'm working on an open source project that is built around Hasura and the resource-hungriness of Docker/qemu's x86_64 emulation makes onboarding contributors with M1 MacBooks difficult. I also don't want to send people to a community image just in case of issues with it.

Are you interested in contributions around this? I could spend 5-10 hours on it and maybe work through part of the problem.

**Comment by bamne123** [comment]
Got it working.

```
version: '3.6'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    volumes:
    - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    container_name: hasura
    image: fedormelexin/graphql-engine-arm64
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```
