### ISSUE TITLE
wait for full initializing of postgres with hasura/graphql-engine image

### ISSUE THREAD

**Issue by karpov-denys** [hasura/graphql-engine#6395]
Dear community,
I need some help. I stuck here. 
I use docker-compose for starting my services. Before work with DB I need add prod database dump to it. It is not quick operation. For that period DB is not available. For avoid errors from hasura/graphql-engine I have added ` restart: always`. It is help to connect both container, but that had not been very informative for other developer. 
Is it possible to use parten [wait-for](https://github.com/Eficode/wait-for) from [docs.docker.com](https://docs.docker.com/compose/startup-order/)? 
I try to add it, but `graphql-steady` service is not initialized in correct way now. I do not now which command I should add to `command:` for proper start of hasura services inside `graphql-steady`.
```
...
  graphql-steady:
    image: hasura/graphql-engine:v1.3.1
    restart: always
    volumes:
      - ./GraphQLSteady/hasura/migrations:/hasura-migrations
      - ./GraphQLSteady/hasura/metadata:/hasura-metadata
      - ./MonolitDB/wait-for.sh:/wait-for.sh
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${DB_SUPERUSERNAME}:${DB_PASS}@monolit-postgres:5432/${DB_NAME}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" 
      HASURA_GRAPHQL_DEV_MODE: ${HASURA_GRAPHQL_DEV_MODE}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
    depends_on:
       - monolit-postgres
    ports:
      - 8090:8080
    command: sh -c "./wait-for monolit-postgres:5432 -- echo 'DB is ready'"

  monolit-postgres: 
    # has some delay before it is available. reason is importing database dump .
    build:
      context: ./MonolitDB
    ports:
      - 5441:5432
    volumes:
      - ./MonolitDB/dumps/${DB_DUMP}:/docker-entrypoint-initdb.d/1-dump.sql
      - ./GraphQLSteady/hasura_permissions.sql:/docker-entrypoint-initdb.d/2-hasura_permissions.sql
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${DB_SUPERUSERNAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

...
```
