### ISSUE TITLE
Problems deploying and accessing Hasura on v1.3.2. /v1/graphql/: "You need to enable JavaScript to run this app." 

### ISSUE THREAD

**Issue by tkim90** [hasura/graphql-engine#6424]
## Problem

I deployed my hasura instance on a k8s cluster, but all POST requests (to `/v1/graphql/`, `/v1/request/`, for ex) returns `You need to enable JavaScript to run this app.`. I'm using image `hasura/graphql-engine:v1.3.2`

1. Can't access the console. Accessing `mysite.com/console/` shows the "Loading..." text but nothing happens. Inspecting the network tab, I see it makes 3 POST requests to `/v1/query`. All 3 of them get the response `You need to enable JavaScript to run this app.`

2. Can't post queries. A POST to `mysite.com/v1/graphql` returns:

`You need to enable JavaScript to run this app.`

I've tried this in the browser (firefox, chrome, safari) and via curl.

---

## What I checked

- I'm running hasura on dev mode (HASURA_GRAPHQL_DEV_MODE), but dont' see any hasura logs when I call POST `/v1/graphql`. This makes me think it's a network issue where the request can't reach the container.
- k8s deployment passes health check and runs the hasura pod.
- I'm using a load balancer. I made sure that all requests to `/v1/graphql/*` get fwded to the hasura container.

---

## Ingress file:

```
// ingress.yaml

spec:
  rules:
  - host: my-site.com
    http:
      paths:
      - path: /v1/graphql/*
        backend:
          serviceName: my-graphql-service
          servicePort: 8080
      - path: /v1/query/*
        backend:
          serviceName: my-graphql-service
          servicePort: 8080
      - path: /console/*
        backend:
          serviceName: my-graphql-service
          servicePort: 8080
      - path: /healthz/*
        backend:
          serviceName: my-graphql-service
          servicePort: 8080
```

**Comment by tirumaraiselvan** [comment]
I guess the issue is that console is served in `/console` and there is no GET support on `/v1/graphql`. Although I am not sure why POSTing a valid request to `/v1/graphql` throws an error.

**Comment by tkim90** [comment]
Regarding Problem #1
- You're right, GET `/v1/graphql/` is not a valid endpoint (tested this locally). I'll edit the question.

Regarding Problem #2
- I made some progress - I added `/console/*`, `/v1/query` as extra ingress paths, both pointing to the hasura container. When I access `my-site.com/console/`, now I get the hasura "Loading..." screen! But...it's stuck there. Inspecting network tab shows it's making a POST request to `/v1/query/`, but returns the same `You need to enable JavaScript to run this app.`. Seems related to the same issue with POST `/v1/graphql/.

**Comment by tkim90** [comment]
OK, so I solved this.

The issue was with my `ingress.yaml` declaration. Because I'm using a load balancer, it expects me to write all the hasura endpoints by hand so it knows which paths to forward to which container ([api docs](https://hasura.io/docs/1.0/graphql/core/api-reference/index.html)).

@tirumaraiselvan I wonder, is there a way to customize my hasura instance api endpoints? I was thinking of prefixing it with a `/hasura` so I only declare my hasura related endpoints _once_ in the ingress file (see below). Basically the ability to change  `/v1/graphql/` to `/hasura/v1/graphql`, etc.

Also, TIL that responses like "You need javascript to run this app." could mean "I don't know what this path is".

---

## Final `ingress.yaml`

```
// ingress.yaml

spec:
  rules:
  - host: my-site.com
    http:
      paths:
      - path: /v1/graphql
        backend:
          serviceName: my-graphql-service
          servicePort: 8080
      - path: /v1/query
        backend:
          serviceName: my-graphql-service
          servicePort: 8080
      - path: /v1beta1/relay
        backend:
          serviceName: my-graphql-service
          servicePort: 8080
      - path: /v1alpha1/graphql
        backend:
          serviceName: my-graphql-service
          servicePort: 8080
      - path: /v1alpha1/pg_dump
        backend:
          serviceName: my-graphql-service
          servicePort: 8080
      - path: /v1alpha1/config
        backend:
          serviceName: my-graphql-service
          servicePort: 8080
      - path: /v1/graphql/explain
        backend:
          serviceName: my-graphql-service
          servicePort: 8080
      - path: /v1/version
        backend:
          serviceName: my-graphql-service
          servicePort: 8080
      - path: /healthz
        backend:
          serviceName: my-graphql-service
          servicePort: 8080
      - path: /console
        backend:
          serviceName: my-graphql-service
          servicePort: 8080
```
