### ISSUE TITLE
Firebase auth - Error fetching JWK: ConnectionTimeout

### ISSUE THREAD

**Issue by SpirosMakris** [hasura/graphql-engine#6488]
Hi,

I'm trying to use Firebase Auth with Hasura. 
I've setup the Firebase project and used the tool at `https://hasura.io/jwt-config/` to create the content of HASURA_GRAPHQL_JWT_SECRET in my docker-compose file (including my firebase project id)
When I restart my containers and the process gets to this point: 
```
{"type":"jwk-refresh-log","timestamp":"2021-01-26T19:47:12.982+0000","level":"info","detail":{"error":null,"message":"refreshing JWK from endpoint: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"}}
```
it pauses for a 10-20 seconds and then I get:
```
serv_gql        | Error fetching JWK: ConnectionTimeout

serv_gql        | {"type":"jwk-refresh-log","timestamp":"2021-01-26T19:47:43.745+0000","level":"critical","detail":{"error":{"http_exception":{"type":"http_exception","message":"ConnectionTimeout"}},"message":null}}
```
and shuts down.
My understanding from reading the docs is that graph-ql engine fails to get a response from the JWK endpoint and it shuts down.
I've 'exec'-ed into the graphql-engine container and used nslookup to get the IP of googleapis.com successfully so it doesn't seem to be a DNS issue.

Could this be a problem at the JWK server's side? 
I've also tried the JWK endpoint in the browser  and I do get a response.

The service section in docker-compose
```
graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    container_name: serv_gql
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    dns:
      - 1.1.1.1
    environment:
      HASURA_GRAPHQL_DATABASE_URL: <DB connection string>
      ## @NOTE: Disabled, so we use the CLI and migration system
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: <admin_secret_here>
      # HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256","jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com", "audience": "<firebase_project_id>", "issuer": "https://securetoken.google.com/<firebase_project_id>"}'
      # HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'anonymous'
```

Thanks in advance
