### ISSUE TITLE
Issues connecting to mysql 

### ISSUE THREAD

**Issue by benmarte** [hasura/graphql-engine#6614]
I'm trying to use the beta for MySQL and running into issues when trying to connect to the database.

I tried doing the things outlined [here](https://github.com/hasura/graphql-engine/issues/5782) but have had no success.

What is interesting is the different error messages based on which host I use.

If I use 127.0.0.1 or my actual IP address 192.168.2.191 I get this error:

```
graphql-engine_1  | {"type":"startup","timestamp":"2021-02-16T14:18:13.714+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":4000},"enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump","developer"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":false,"port":8080}}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-02-16T14:18:13.714+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:...@postgres:5432/postgres"}}}
graphql-engine_1  | {"type":"pg-client","timestamp":"2021-02-16T14:18:19.116+0000","level":"warn","detail":{"message":"postgres connection failed, retrying(0)."}}
graphql-engine_1  | {"type":"pg-client","timestamp":"2021-02-16T14:18:24.562+0000","level":"warn","detail":{"message":"postgres connection failed, retrying(1)."}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-02-16T14:18:24.562+0000","level":"error","detail":{"kind":"catalog_migrate","info":{"internal":"could not translate host name \"postgres\" to address: Name or service not known\n","path":"$","error":"connection error","code":"postgres-error"}}}graphql-engine_1  | Connected to MySQL!
graphql-engine_1  | {"internal":"could not translate host name \"postgres\" to address: Name or service not known\n","path":"$","error":"connection error","code":"postgres-error"}
```

If I use localhost I get this one:

```
graphql-engine_1  | graphql-engine: ConnectionError {errFunction = "connect", errNumber = 2002, errMessage = "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"}
```

**Comment by nerdvibe** [comment]
Solved by adding `network_mode: host` in both postgres and graphql-engine service. **Then** you need to change the HASURA_GRAPHQL_DATABASE_URL connection string in the same file.

Therefore it becomes:
`HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@127.0.0.1:5432/postgres`

**Comment by benmarte** [comment]
> Solved by adding `network_mode: host` in both postgres and graphql-engine service. **Then** you need to change the HASURA_GRAPHQL_DATABASE_URL connection string in the same file.
> 
> Therefore it becomes:
> `HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@127.0.0.1:5432/postgres`

Can you post your whole docker-compose file? I added network_mode:host to both the postgres and graphql-engine and now I get this error:

```
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
```

Here is what my docker-compose file looks like:

```
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    network_mode: host
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:pull5655-633f084f
    ports:
    - "8080:8080"
    network_mode: host
    depends_on:
    - "postgres"
    command:
    - graphql-engine
    - --mysql-host 
    - <mysql-host>
    - --mysql-user 
    - <mysql-user>
    - --mysql-port 
    - <mysql-port>
    - --mysql-dbname 
    - <mysql-dbname>
    - --mysql-password 
    - <mysql-password>
    - serve 
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@127.0.0.1:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```

If I comment out the ports entry it works but nothing happens when I go to `http://localhost:8080/console` I'm on windows BTW.

Here is what shows up in terminal from the `docker-compose up`

```
postgres_1        |
postgres_1        | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1        |
postgres_1        | 2021-04-09 23:47:26.465 UTC [1] LOG:  starting PostgreSQL 12.6 (Debian 12.6-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres_1        | 2021-04-09 23:47:26.466 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1        | 2021-04-09 23:47:26.466 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1        | 2021-04-09 23:47:26.468 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1        | 2021-04-09 23:47:26.477 UTC [26] LOG:  database system was shut down at 2021-04-09 23:47:24 UTC
postgres_1        | 2021-04-09 23:47:26.480 UTC [1] LOG:  database system is ready to accept connections
graphql-engine_1  | {"type":"startup","timestamp":"2021-04-09T23:47:26.743+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":4000},"enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump","developer"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":false,"port":8080}}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-04-09T23:47:26.743+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:...@127.0.0.1:5432/postgres"}}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-04-09T23:47:29.815+0000","level":"info","detail":{"kind":"catalog_migrate","info":"Successfully initialized the catalog (at version 37)."}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-04-09T23:47:29.815+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 41","instance_id":"801c5d51-a3a0-459a-bb06-34aa3bec175f","message":"listener thread started"}}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-04-09T23:47:29.815+0000","level":"info","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 42","instance_id":"801c5d51-a3a0-459a-bb06-34aa3bec175f","message":"processor thread started"}}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-04-09T23:47:29.815+0000","level":"info","detail":{"kind":"event_triggers","info":"preparing data"}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-04-09T23:47:29.815+0000","level":"info","detail":{"kind":"event_triggers","info":"starting workers"}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-04-09T23:47:29.815+0000","level":"info","detail":{"kind":"scheduled_triggers","info":"preparing data"}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-04-09T23:47:29.815+0000","level":"info","detail":{"kind":"telemetry","info":"Help us improve Hasura! The graphql-engine server collects anonymized usage stats which allows us to keep improving Hasura at warp speed. To read more or opt-out, visit https://hasura.io/docs/1.0/graphql/manual/guides/telemetry.html"}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-04-09T23:47:29.815+0000","level":"info","detail":{"kind":"server","info":{"time_taken":3.086981,"message":"starting API server"}}}
```

It almost seems as if it's stuck trying to start the API server.

Thanks.

**Comment by nerdvibe** [comment]
>  I added network_mode:host to both the postgres and graphql-engine and now I get this error:
`docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings`

@benmarte if you use `host` as network mode, then you need to remove `ports: - "8080:8080"` from your docker-compose, since all the container ports will be exposed on the host.

**Comment by benmarte** [comment]
It does the same thing on my Mac so it's not a windows issue.

**Comment by sibitha-bijesh** [comment]
@nerdvibe I got same authentication error with the connection string above and network_more host. Can you please share your compose file to review 

````
postgres:
    image: postgres:12
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgres
    network_mode: "host"
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.7
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@127.0.0.1:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    network_mode: "host"
    ````
