### ISSUE TITLE
hasura-cli: Segmentation fault

### ISSUE THREAD

**Issue by go4cas** [hasura/graphql-engine#6678]
I get this error from the `v2.0.0-alpha.4.cli-migrations-v2` image:
```bash
{"timestamp":"2021-03-18T15:00:39.000+0000","level":"info","type":"startup","detail":{"kind":"installing cli-ext plugin","info":""}}

qemu: uncaught target signal 11 (Segmentation fault) - core dumped

Segmentation fault
```

I have already tried by adding the `HASURA_GRAPHQL_CLI_ENVIRONMENT=default` environment var, but still getting the same error.

I am running `hasura-cli` 1.3.3, with `cli-ext` v2.0.0-alpha.4.

**Comment by scriptonist** [comment]
@go4cas Just to clarify, are you encountering this error in  `v2.0.0-alpha.4.cli-migrations-v2` or when you use CLI directly?

**Comment by go4cas** [comment]
@scriptonist, when `docker-compose up` is executed. I have tried with other versions of the images as well, e.g. `v1.3.3.cli-migrations-v2`. I have also tried to upgrade the cli to `2.0.0-alpha.4`. Same error.

**Comment by scriptonist** [comment]
Got it @go4cas Thanks! 
while we investigate this, can you also try `2.0.0-alpha.5`? we have some changes in the latest release pertaining to this.

**Comment by go4cas** [comment]
@scriptonist, upgrading to `alpha.5` eliminates the cli error, but now it gets stuck with:
`{"timestamp":"2021-03-19T07:12:04.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"failed waiting for 9691, try increasing HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT (default: 30)"}}`
I have tried increasing the timeout, and also tried setting a different port number, but same error.

**Comment by scriptonist** [comment]
@go4cas that might be because the Postgres instance Hasura is trying to connect is not ready yet? maybe try setting [`HASURA_GRAPHQL_NO_OF_RETRIES`](https://hasura.io/docs/latest/graphql/core/deployment/graphql-engine-flags/reference.html#command-flags) ?

**Comment by go4cas** [comment]
@scriptonist, this is already in the env:
```json
HASURA_GRAPHQL_NO_OF_RETRIES: 20
```
The docker-compose file also includes `depends_on` for the Hasura instance on the Postgres container.

**Comment by scriptonist** [comment]
@go4cas Okay, that was my guess. Basically, 9691 is waiting for a temporary Hasura instance to become ready, Looking at the rest of the logs might give us some idea why it is not able to start.

**Comment by go4cas** [comment]
@scriptonist, these are all the docker logs for the asura container:
```bash
{"timestamp":"2021-03-19T10:02:18.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"database url for migrations is set by HASURA_GRAPHQL_DATABASE_URL"}}
{"timestamp":"2021-03-19T10:02:18.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"migrations server port env var is not set, defaulting to 9691"}}
{"timestamp":"2021-03-19T10:02:18.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"starting graphql engine temporarily on port 9691"}}
{"timestamp":"2021-03-19T10:02:18.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"waiting 30 for 9691 to be ready"}}
{"timestamp":"2021-03-19T10:02:55.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"failed waiting for 9691, try increasing HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT (default: 30)"}}
{"timestamp":"2021-03-19T10:03:00.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"database url for migrations is set by HASURA_GRAPHQL_DATABASE_URL"}}
{"timestamp":"2021-03-19T10:03:00.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"migrations server port env var is not set, defaulting to 9691"}}
{"timestamp":"2021-03-19T10:03:00.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"starting graphql engine temporarily on port 9691"}}
{"timestamp":"2021-03-19T10:03:00.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"waiting 30 for 9691 to be ready"}}
{"timestamp":"2021-03-19T10:03:39.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"failed waiting for 9691, try increasing HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT (default: 30)"}}
{"timestamp":"2021-03-19T10:03:42.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"database url for migrations is set by HASURA_GRAPHQL_DATABASE_URL"}}
{"timestamp":"2021-03-19T10:03:42.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"migrations server port env var is not set, defaulting to 9691"}}
{"timestamp":"2021-03-19T10:03:42.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"starting graphql engine temporarily on port 9691"}}
{"timestamp":"2021-03-19T10:03:42.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"waiting 30 for 9691 to be ready"}}
```

**Comment by go4cas** [comment]
This is the `docker-compose` I am using:
```yaml
version: '3.6'
services:
  nhost-postgres:
    container_name: nhost_postgres
    image: postgres:12
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
  nhost-graphql-engine:
    container_name: nhost_hasura
    image: hasura/graphql-engine:v2.0.0-alpha.5.cli-migrations-v2
    ports:
      - 8090:8090
    depends_on:
      - nhost-postgres
    restart: always
    environment:
      HASURA_GRAPHQL_SERVER_PORT: 8090
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@nhost-postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: 123456
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 30
      HASURA_GRAPHQL_NO_OF_RETRIES: 20
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      NHOST_HASURA_URL: http://nhost_hasura:8090/v1/graphql
      NHOST_WEBHOOK_SECRET: devnhostwebhooksecret
      NHOST_HBP_URL: http://nhost_hbp:9001
      NHOST_CUSTOM_API_URL: http://nhost_api:4000
    env_file:
      - ./.env.development
    command:
      - graphql-engine
      - serve
    volumes:
      - ./migrations:/hasura-migrations
```
