### ISSUE TITLE
Additional information for error when adding database

### ISSUE THREAD

**Issue by ealtuna** [hasura/graphql-engine#6684]
I am using docker-compose with the graphql-engine v2.0.0-alpha.5. When trying to add a data source through the UI using the `postgresql://USER:PASSWORD@IP:5432/DBNAME` I get an error in the UI:

```
[
    {
        "definition": "remote",
        "reason": "database query error",
        "type": "source"
 
```

Looking at the docker logs I only see:

```
{"type":"startup","timestamp":"2021-03-19T16:47:36.674+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":4000},"enable_maintenance_mode":false,"enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"remote_schema_permissions":false,"log_level":"debug","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":true,"enable_console":true,"auth_hook":null,"infer_function_permissions":true,"experimental_features":[],"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"websocket_compression_options":"NoCompression","console_assets_dir":null,"admin_secret_set":false,"port":8080,"websocket_keep_alive":"KeepAliveDelay {unKeepAliveDelay = Seconds {seconds = 5s}}"}}}
{"type":"http-log","timestamp":"2021-03-19T17:24:56.894+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":"remote","reason":"database query error","type":"source"}],"path":"$.args","error":"database query error","code":"constraint-violation"},"request_id":"7627bc80-dc0c-40b8-b07f-f5ec92d6872c","response_size":163,"query":{"resource_version":null,"args":{"name":"remote","configuration":{"connection_info":{"database_url":"MY_DB_URL","pool_settings":{}}}},"version":1,"type":"pg_add_source"}},"request_id":"7627bc80-dc0c-40b8-b07f-f5ec92d6872c","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/metadata","ip":"192.168.96.1","method":"POST","content_encoding":null}}}
```

This is my `hasura/graphql-engine` definition in the `docker.compose.yaml`:

```
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.5
    ports:
    - "8080:8080"
    depends_on:
    - "postgresmeta"
    - "postgresuser"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgresmeta:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_LOG_LEVEL: debug
``` 

Is there any way to get additional details about what is the specific error querying the source database?
