### ISSUE TITLE
cli: use os neutral filepaths in generated files

### ISSUE THREAD

**Issue by TheMrZZ** [hasura/graphql-engine#6813]
We have a 2.0.0-alpha.7 setup working perfectly fine. We'd like to update to 2.0.0-alpha.9, but the container systematically fails to apply metadata:
```
FATA[0000] failed to apply metadata:
{
  "path": "$.metadata",
  "error": "key \"sources\" not found",
  "code": "parse-failed"
}
```

There is no column, table or anything named "sources" in our metadata/database schema. I've no idea where this bug comes from, but it prevents us to update. It also happens when updating to 2.0.0-alpha.8.

**Comment by scriptonist** [comment]
@TheMrZZ Can you help me with the following info, 
- Config version you are using for the CLI project config V2 / V3 ? 
- Are you running the normal Hasura image or `cli-migrations` image

**Comment by TheMrZZ** [comment]
Hi @scriptonist,

I am using the CLI config V3. I'm using the `cli-migrations` image.

I wiped my development database, started a new docker container using the normal Hasura image, applied the migrations, and then ran `hasura metadata apply --log-level debug`. Here is the output:
```
DEBU global config file exisits, verifying contents
DEBU global config is pre-set to &cli.GlobalConfig{UUID:"39f716ae-d1db-4deb-9cf3-041b01f2c143", EnableTelemetry:true, ShowUpdateNotification:true, CLIEnvironment:"default"}
DEBU global config: uuid: 39f716ae-d1db-4deb-9cf3-041b01f2c143
DEBU global config: enableTelemetry: true
DEBU global config: showUpdateNotification: true
DEBU global config: cliEnvironment: default
DEBU cannot get config information from server, this might be because config API is not enabled: error fetching server config: [not-found] resource does not exist ($)
DEBU graphql engine endpoint: http://localhost:8080/
DEBU graphql engine admin_secret: password
DEBU versions: cli: [v2.0.0-alpha.9] server: [v2.0.0-alpha.9]
DEBU compatibility check: [true] older cli version might not be compatible with latest server apis, please update cli
DEBU server: uuid: ad052d6c-f970-4613-a344-aed880c322f0
DEBU output: {"success":true,"output_file_path":"C:\\Users\\Florian\\AppData\\Local\\Temp\\785224659.json"}  command="sdl from"
INFO Metadata applied
DEBU telemetry: beamed                             fields.time=151.4501ms isError=false
```
As you can see, and to my surprise, it actually works. The problem might then come from the cli-migrations image.

With this working instance, I tried to export the metadata, and then to restart the `cli-migrations` image. It still throws the same error.

**Comment by scriptonist** [comment]
@TheMrZZ Also just verifying, are you using `v2.0.0-alpha.9.cli-migrations-v3` ?

**Comment by TheMrZZ** [comment]
Correct:
![image](https://user-images.githubusercontent.com/30944236/115875120-2d060500-a445-11eb-9e51-8690c81b4d64.png)

**Comment by scriptonist** [comment]
@TheMrZZ Got it thanks. can you share the contents of your `metadata/databases/databases.yaml` file with sensitive info redacted?

**Comment by TheMrZZ** [comment]
Here is my exact `databases.yaml`, without anything redacted (since our `databases.yaml` is commited to our repo, we use environment variables):
```yaml
- name: default
  kind: postgres
  configuration:
    connection_info:
      database_url:
        from_env: HASURA_GRAPHQL_DATABASE_URL
      pool_settings:
        idle_timeout: 180
        max_connections: 2
        retries: 1
      use_prepared_statements: false
  tables: "!include default\\tables\\tables.yaml"
  functions: "!include default\\functions\\functions.yaml"
```
