### ISSUE TITLE
rfc: multi-column foreign key relationships

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#6842]
Currently relationships based on foreign key constraints would only work for single column constraints. Console works around this issue by creating `manual_configuration` in such cases. Ideally this isn't much work to support on the server and opens up possibilities for improved query generation (see https://github.com/hasura/graphql-engine/issues/5949). 

## Object relationships:

- Many-To-One:

  ```
  name: RelationshipName
  table: TableName
  using:
    foreign_key_constraint_on: ColumnName | [ColumnName]
    manual_configuration: <no-changes>
  ```

- One-To-One:
  ```
  name: RelationshipName
  table: TableName
  using:
    foreign_key_constraint_on:
      table: TableName
      # column will now be deprecated
      column: ColumnName
      # only one of column/columns should be present
      columns: ColumnName | [ColumnName]
    manual_configuration: <no-changes>
  ```

## Array Relationships:

```
name: RelationshipName
table: TableName
using:
  foreign_key_constraint_on:
    table: TableName
    # column will now be deprecated
    column: ColumnName
    # only one of column/columns should be present
    columns: ColumnName | [ColumnName]
  manual_configuration: <no-changes>
```

## Potential issues

`export_metadata` will now have single element column arrays:

- Previously

  ```
  table: article
  name: author
  using:
    foreign_key_constraint_on: author_id
  ```

- After this change

  ```
  table: article
  name: author
  using:
    foreign_key_constraint_on: [author_id]
  ```
