### ISSUE TITLE
Can't initialize v2 migrations

### ISSUE THREAD

**Issue by lilred** [hasura/graphql-engine#6850]
Here's a shell session:

```sh
lilred@work:~$ hasura version
INFO hasura cli                                    version=v1.3.3
lilred@work:~$ # https://hasura.io/docs/latest/graphql/core/getting-started/docker-simple.html
lilred@work:~$ wget -q https://raw.githubusercontent.com/hasura/graphql-engine/stable/install-manifests/docker-compose/docker-compose.yaml
lilred@work:~$ docker-compose up -d
Creating network "lilred_default" with the default driver
Creating volume "lilred_db_data" with default driver
Creating lilred_postgres_1 ... done
Creating lilred_graphql-engine_1 ... done
lilred@work:~$ hasura init my-project --endpoint http://localhost:8080
INFO directory created. execute the following commands to continue:

  cd my-project
  hasura console 
lilred@work:~$ # now I went to http://localhost:8080/console and created a tracked table
lilred@work:~$ cd my-project
lilred@work:~/my-project$ hasura console
FATA[0000] error creating migrate instance: cannot create migrate instance: Data Error: {"path":"$","error":"resource does not exist","code":"not-found"} 
lilred@work:~/my-project$ hasura migrate create "init" --from-server
FATA[0000] cannot create migrate instance: cannot create migrate instance: [not-found] resource does not exist ($) 
lilred@work:~/my-project$ cd ..
lilred@work:~$ wget -q https://raw.githubusercontent.com/hasura/graphql-engine/stable/install-manifests/docker-compose/docker-compose.yaml
```

This is on Ubuntu 20.10, Hasura CLI 1.3.3, Hasura server 1.3.3, docker client 20.10.6, docker engine 20.10.6, docker-compose 1.27.4. Let me know if you can reproduce on your side or if you need any other information.

**Comment by martin-hasura** [comment]
I wasn't able to reproduce on my side - would you be able to change any sensitive information in your docker-compose file and share here for review?

**Comment by lilred** [comment]
I'm using the docker-compose.yaml file published [here](https://raw.githubusercontent.com/hasura/graphql-engine/stable/install-manifests/docker-compose/docker-compose.yaml), reproduced below for future reference

```yaml
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```
