### ISSUE TITLE
cli: hasura-cloud assets being fetched from wrong url

### ISSUE THREAD

**Issue by abhi40308** [hasura/graphql-engine#6851]
`version=v2.0.0-alpha.9` 

While using CLI with Hasura-cloud endpoint, CDN assets are being fetched from URL: `https://graphql-engine-cdn.hasura.io/console/assets/channel/cloud/v2.0/vendor.js.gz` which serves old buggy code.

From wiki, it should be: `https://graphql-engine-cdn.hasura.io/cloud-console/assets/channel/versioned/<version>`. 

Config: 
```
version: 3
endpoint: https://test-something.hasura.app
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
```
