### ISSUE TITLE
server: support renaming a source

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#6881]
`v1/metadata` API will have to support a new operation `rename_source` as follows:
```yaml
type: rename_source
args:
  name: <current_source_name>
  new_name: <new_source_name>
```
