### ISSUE TITLE
console/bigquery: remove deprecated service account from file option

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#6899]
Currently, when you try to add a bigquery source, we see this UI:

![image](https://user-images.githubusercontent.com/6562944/117832826-73f05900-b293-11eb-934b-f04a384d0fa2.png)

The server expects the service account data as a json object under `service_account` key as follows:
```yaml
type: bigquery_add_source
args:
  name: london_cycles
  configuration:
    project_id: fifth-pact-307811
    datasets:
    - london_cycles
    service_account:
      client_email: ...
      project_id: ...
      private_key: ...
```

So the UI can just show a text box to paste the content of a service account file. This content then has to be parsed as a json object and added under `service_account` key. Adding a bigquery source from env variable already works, so nothing needs to be done on that front.
