### ISSUE TITLE
customising graphql typename generation per source

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#6974]
Currently a source's name is not used in the GraphQL types that we generate. So if two sources have same table names, they can't both be tracked because of type and field conflicts. One can work around this to some extent by customizing each of the table names that cause the conflict. However, it would be very convenient to have this configured per source. We add `customization` field to the `*_add_source` API with the following spec:
```yaml
customization:
  # if root_fields.namespace is absent, the fields
  # are merged into the query root directly
  root_fields:
    namespace: "something"
    prefix: some_prefix
    suffix: some_suffix
  type_names:
    prefix: some_prefix
    suffix: some_suffix
```
