### ISSUE TITLE
config v3 breaks metadata migration on deployed instances

### ISSUE THREAD

**Issue by whollacsek** [hasura/graphql-engine#7009]
When using the v3 config, running `hasura metadata apply` will apply whatever database that's now hardcoded in the v3 file hierarchy, which overrides the database connection details and produce `Metadata is inconsistent`.

**Comment by scriptonist** [comment]
@whollacsek are you saying that if you "hardcode" `database_url` things don't seem to work?

**Comment by whollacsek** [comment]
Hi @scriptonist let me explain the situation I'm facing.

I just started a new project using `hasura/graphql-engine:v2.0.0-beta.1.cli-migrations-v3` and generated a hasura folder with v3 config and file hierarchy. I run hasura locally with docker compose and generate migration files using hasura-cli. I have also setup the database migration using Github Action targeting my production and staging hasura instances.

The issue is regarding database migration.

By default it seems the databases.yaml contains the `database_url` from my docker-compose's `HASURA_GRAPHQL_DATABASE_URL` env var.

Locally when I restart hasura migrations are applied correctly but on Github Action it fails because it seems to override the database configuration.

**Comment by scriptonist** [comment]
@whollacsek Thanks for the detailed description, will try to reproduce this and get back to you.

**Comment by scriptonist** [comment]
@whollacsek just tried reproducing this scenario, but I didn't encounter the issue mentioned.

If you have started Hasura with `HASURA_GRAPHQL_DATABASE_URL` then `metadata/databases/databases.yaml` file should be something like this 
```
- name: default
  kind: postgres
  configuration:
    connection_info:
      database_url:
        from_env: HASURA_GRAPHQL_DATABASE_URL
      isolation_level: read-committed
      pool_settings:
        connection_lifetime: 600
        idle_timeout: 180
        max_connections: 50
        retries: 1
      use_prepared_statements: true
  tables: "!include default/tables/tables.yaml"
```
So, if you mount your project `metadata` and `migrations` directory on to you staging/production hasura container and make sure that `HASURA_GRAPHQL_DATABASE_URL` is set to the respective database (staging/prod) then, things should work as expected.
