### ISSUE TITLE
Support readonly databases

### ISSUE THREAD

**Issue by frol** [hasura/graphql-engine#7029]
Can Hasura support the database instances that cannot be controlled and only read-only access is available?

Currently, I get the following error when try to connect to the read replica:

![image](https://user-images.githubusercontent.com/304265/121400396-eb1a1b00-c92d-11eb-88c2-03e08ea3eb26.png)

```json
[
    {
        "definition": "indexer-mainnet",
        "reason": "Inconsistent object: postgres tx error",
        "name": "source indexer-mainnet",
        "type": "source",
        "message": {
            "statement": "BEGIN ISOLATION LEVEL READ COMMITTED READ WRITE",
            "prepared": true,
            "error": {
                "exec_status": "FatalError",
                "hint": null,
                "message": "cannot set transaction read-write mode during recovery",
                "status_code": "0A000",
                "description": null
            },
            "arguments": []
        }
    }
]
```

Here is the connection string: `postgres://public_readonly:nearprotocol@104.199.89.51/mainnet_explorer`

We want to recommend our users to use Hasura if they don't feel comfortable using SQL or want to have access to the database from their web apps: https://github.com/near/near-indexer-for-explorer/issues/123

**Comment by tirumaraiselvan** [comment]
Which version of Hasura are you running? Is the metadata db separated? 

If the metadata db is separated, then you should be able to add a read-only postgres source in Hasura.

**Comment by frol** [comment]
I was no aware that I can specify a separate DB for metadata. This is the config I used:

```yml
version: '3.6'
services:
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-beta.1
    ports:
    - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://public_readonly:nearprotocol@35.184.214.98/testnet_explorer
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
```

(based on https://github.com/hasura/graphql-engine/tree/master/install-manifests/docker-compose)

Can I run Hasura in the auto-introspection mode with zero configuration? That is, given I point to an already existing DB with all the tables in it and foreign keys configured, I want to get read-only access to all the data. (Assume the database access is read-only and I don't have control over the database and I want to have Hasura-enabled API server)

**Comment by tirumaraiselvan** [comment]
> If the above is not feasible, what do I need to configure metadata DB? (I assume it can be a small Postgres instance colocated with Hasura engine, right?)

You can give an env var `HASURA_GRAPHQL_METADATA_DATABASE_URL` with a writeable Postgres connection string. Yes, metadata db can be a small Postgres instance.

**Comment by frol** [comment]
I almost get there! Here is my docker-compose file now:

```yml
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    #volumes:
    #- db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-beta.1
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    #restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://public_readonly:nearprotocol@35.184.214.98/testnet_explorer
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
```

Yet, whenever I try to do anything (e.g. adding a schema or even running raw SQL) I get this error:

```json
{
    "statement": "BEGIN ISOLATION LEVEL READ COMMITTED READ WRITE",
    "prepared": true,
    "error": {
        "exec_status": "FatalError",
        "hint": null,
        "message": "cannot set transaction read-write mode during recovery",
        "status_code": "0A000",
        "description": null
    },
    "arguments": []
}
```

You should be able to reproduce it on your end since the connection string is public (it is a read-only replica running Postgres 11 on GCP)

Is there a way to avoid read-write transaction?
