### ISSUE TITLE
Remote schema permissions yaml formatting for better git diff

### ISSUE THREAD

**Issue by jgoux** [hasura/graphql-engine#7033]
Hello,

Currently when we save the remote schema permissions through the console UI, Hasura format the remote schema types as a minified json. This is a major pain for resolving conflicts when merging our branches as we can't really tell what exactly is conflicting.

A better strategy would be to format the remote schema types as non minified SDL, sorted predictably like : 
```yaml
  permissions:
  - role: public
    definition:
      schema: |-
          type InputValidationError {
            formErrors: [String]!
            fieldErrors: json!
          }

          type UserAlreadyExists {
            type: String!
            message: String!
          }
          
         # ...
```
