### ISSUE TITLE
SCRAM authentication requires libpq version 10 or above

### ISSUE THREAD

**Issue by jaschaschmidt** [hasura/graphql-engine#7107]
Postgres version: PostgreSQL 11.10
Hasura version: 2.0.0
K8s version: v1.20

error message:
{"type":"startup","timestamp":"2021-05-31T08:12:46.974+0000","level":"error","detail":{"kind":"catalog_migrate","info":{"internal":"SCRAM authentication requires libpq version 10 or above\n","path":"$","error":"connection error","code":"postgres-error"}}}

Please note that the latest stable build v1.3.3 works perfectly fine with Postgres version 11.10.
Changing from scram to md5 on the postgres server is not feasible workaround and does not solve the connection error.

Note:
This is still not fixed in the final version 2.0.0

**Comment by codingkarthik** [comment]
Hey @jaschaschmidt,

This exact issue had been reported earlier in https://github.com/hasura/graphql-engine/issues/6670 and since then it's been fixed via https://github.com/hasura/graphql-engine/commit/7d630e8147eb116d4a6aa7b6afdc7313e3ca968f. I've tried to repro this problem locally with the v2.0.0 (now deleted, the latest 2.0 version is v2.0.1) but was not able to repro it, I was able to repro this issue with `v2.0.0-beta.4` when it was originally reported. Can you do the following things so that we can debug this issue further:

1. Double check the graphql-engine version if it's `v2.0.1` now
2. Is it possible for you to share your k8s manifest?
3. I've used the following docker-compose file for SCRAM authentication 

```yaml
version: '3.6'
services:
  postgres:
    image: postgres:11
    restart: always
    ports:
      - "7432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
volumes:
  db_data:
```

This works at my local setup,can you also check with the above DB in your setup?
