### ISSUE TITLE
Unable to track new database in hasura 2.0.1

### ISSUE THREAD

**Issue by yoDon** [hasura/graphql-engine#7126]
I'm getting errors with a brand new hasura 2.0.1 console running in Chrome hosted in kubernetes and connected to a brand new heroku postgres database (free tier).

The console successfully creates and deletes schemas but returns an error message when creating or tracking tables. 

When I click in the console UI to create a table, the console creates the table in the database but reports an error and fails to track the newly created table:

```
{
    "path": "$[0]",
    "error": "When parsing Hasura.Server.API.Query.RQLQueryV1 expected an Object with a tag field where the value is one of [add_existing_table_or_view, track_table, untrack_table, set_table_is_enum, set_table_customization, track_function, untrack_function, create_object_relationship, create_array_relationship, drop_relationship, set_relationship_comment, rename_relationship, add_computed_field, drop_computed_field, create_remote_relationship, update_remote_relationship, delete_remote_relationship, create_insert_permission, create_select_permission, create_update_permission, create_delete_permission, drop_insert_permission, drop_select_permission, drop_update_permission, drop_delete_permission, set_permission_comment, get_inconsistent_metadata, drop_inconsistent_metadata, insert, select, update, delete, count, bulk, add_remote_schema, update_remote_schema, remove_remote_schema, reload_remote_schema, introspect_remote_schema, create_event_trigger, delete_event_trigger, redeliver_event, invoke_event_trigger, create_cron_trigger, delete_cron_trigger, create_scheduled_event, create_query_collection, drop_query_collection, add_query_to_collection, drop_query_from_collection, add_collection_to_allowlist, drop_collection_from_allowlist, run_sql, replace_metadata, export_metadata, clear_metadata, reload_metadata, create_action, drop_action, update_action, create_action_permission, drop_action_permission, create_rest_endpoint, drop_rest_endpoint, dump_internal_state, set_custom_types], but got pg_track_table.",
    "code": "parse-failed"
}
```

This console reports the same error when told to track tables.

The kubernetes yaml is built from the current stock [deployment.yaml](https://raw.githubusercontent.com/hasura/graphql-engine/stable/install-manifests/kubernetes/deployment.yaml) and [svc.yaml](https://raw.githubusercontent.com/hasura/graphql-engine/stable/install-manifests/kubernetes/svc.yaml) files tweaked slightly to use k8s secrets instead of hard-coded secrets
```
apiVersion: v1
kind: Secret
metadata:
  name: hasura-secrets
stringData:
  postgres-url: postgres://myUsernameHere:myPasswordHere@myHostHere.compute-1.amazonaws.com:5432/myTableHere
  admin-secret: mySecretHere
  
  
  ---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
    hasuraService: custom
  name: hasura
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasura
    spec:
      containers:
      - image: hasura/graphql-engine:v2.0.1
        imagePullPolicy: IfNotPresent
        name: hasura
        env:
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        - name: HASURA_GRAPHQL_DEV_MODE
          value: "true" # enable debugging mode. Disable in production
        - name: HASURA_GRAPHQL_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: hasura-secrets
              key: postgres-url
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              name: hasura-secrets
              key: admin-secret
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasura
  name: hasura
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: hasura
  type: LoadBalancer
```

The Console was installed via `curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash` and is run via 
```
hasura console \
    --admin-secret=`kubectl get secret hasura-secrets -o jsonpath='{.data.admin-secret}' | base64 -d` \
    --endpoint=http://`kubectl get services hasura -o jsonpath='{.status.loadBalancer.ingress[0].ip}'`
```

My `config.yaml` file is essentially empty as I'm passing the admin-secret and endpoint directly to the console
```
# Hasura config.yaml file
# (the hasura cli wont run without it, even though it can be empty like this)
```
