### ISSUE TITLE
How to accelerate startup times

### ISSUE THREAD

**Issue by gunar** [hasura/graphql-engine#7145]
I'm building a CD/CI pipeline. For the integration tests, I'm spinning up Hasura inside a docker container in order to run the tests. I was wondering. Are there any configs that would accelerate Hasura startup times?

- I know Hasura first waits for postgres to be ready. And keeps retrying until it is ready. Perhaps we can reduce this waiting time?
- Hasura also boots twice, right? If I understand correctly, the first time is just to apply migrations. Is there any way to speed up this cycle?

Look, this is not a big deal. The startup times are mostly fine really. It's just that for CD/CI pipelines every second counts. I'm asking because I've searched the internet and couldn't find anything, and thought that perhaps someone here might have a suggestion.

Thanks in advance!

**Comment by martin-hasura** [comment]
So there may be better people to answer this question - but here are a couple things that may be helpful.

So for your first question - you may be able to refactor some of this compose script for your pipeline.

It has a quick healthcheck on Postgres before starting the graphql-engine container (it can give you a bit more granularity in the intervals for checking database up).

```yaml
version: '3'
services:

  database:
    image: postgres:12
    restart: always
    ports:
      - "127.0.0.1:5432:5432" 
    environment:
      POSTGRES_PASSWORD: password
    ## Some SQL - before init
    # volumes:
    #   - ./some-sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  graphql-engine:
    image: hasura/graphql-engine:v2.0.1.cli-migrations-v3
    ports:
      - "127.0.0.1:8080:8080"
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: password
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@database:5432/postgres
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    ## Healthcheck for GraphQL Engine
    # healthcheck:
    #   test: ["CMD-SHELL", "wget -qO- http://localhost:8080/healthz || exit 1"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5
```

Now from the migration side in that process - if you're not testing the actual migrations using the graphql-engine, you could add your .sql files to the `docker-entrypoint-initdb.d` as commented out above in Postgres. These'll mount and run in the container on startup and shouuuld complete before it reports `pg_isready`.

You'd then remove the migrations from graphql-engine on start. You're losing the testing of migrations across gql > postgres but you're probably shaving a little time off depending on the size of your migrations.

Aside from that, I don't believe there's a ton of other things that can be done to speed up the server start process (there may be some things around the edges like disabling telemetry, or disabling some logging, but I don't think those will yield a discernible result -- you can find all the flags here: https://hasura.io/docs/latest/graphql/core/deployment/graphql-engine-flags/reference.html#server-flag-reference). 

The double start process you mentioned is actually just a double apply of metadata -- this happens at the start (so the server knows where the db sources are for migrations), then applies migrations, then re-applies metadata (to ensure consistency).

Hopefully this helps, lemme know if you have any questions at all.
