### ISSUE TITLE
Adding Database Doesn't Persist to Metadata

### ISSUE THREAD

**Issue by browniefed** [hasura/graphql-engine#7153]
I have spun up a fresh install, initializing and running Hasura 2.0.1 using hasura cli v2.0.1

<img width="609" alt="Screen Shot 2021-06-29 at 6 59 19 PM" src="https://user-images.githubusercontent.com/1714673/123890480-2051d180-d90c-11eb-86d9-b130a58c8150.png">

Upon adding a database no metadata for the `databases.yaml` is added.

Once I toggle the `Allow Postgres schema changes via console` (even though it starts enabled) off and then back on the `databases.yaml` is magically populated.

Video of the demonstration here.

https://user-images.githubusercontent.com/1714673/123890595-568f5100-d90c-11eb-913d-9be859ff0e7c.mp4

Freshly initialized project.

Manifest

```
version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.1
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: admin_secret
volumes:
  db_data:

```
