### ISSUE TITLE
Cookie JWT token expected even when unauthorised role set

### ISSUE THREAD

**Issue by bitscraps** [hasura/graphql-engine#7272]
I appear to be having an issue whilst using JWT tokens via cookies. For unauthenticated requests, I am not sending a cookie. From the documentation, I'm expecting these requests to use the role set in HASURA_GRAPHQL_UNAUTHORIZED_ROLE. However, instead, i get an error response:

```{
    "errors": [
        {
            "extensions": {
                "path": "$",
                "code": "invalid-headers"
            },
            "message": "Could not find access_token in Cookie header"
        }
    ]
}
```

Authenticated requests with a JWT token work fine. However, we need to make a request first to get an access token that is falling foul of this expectation that there should be a cookie header. The documentation for this UNAUTHORIZED_ROLE talks about authorization header's which we are not using. Is this option supported with JWT cookie authentication?

These are the options being passed to the Hasura docker image:

```
HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "my_key", "header": { "type": "Cookie", "name": "access_token" } }'
HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
```

Comments in the code suggest that it should be using the unauthorized role. https://github.com/hasura/graphql-engine/blob/2152911e240627add0a5b6b69b052efaa924c338/server/src-lib/Hasura/Server/Auth/JWT.hs#L351

If i switch to using the authorization header rather than a cookie, and i don't send a header it allows the request to continue, presumably using the UNAUTHORIZED ROLE

**Comment by bitscraps** [comment]
Some further testing shows that rather than it checking for a particular cookie to determine if it's an unauthenticated request it just checks if there is a cookie header. If any other cookies are sent it expects there to also be an access token. This causes issues as cookies are used for other things in some of our requests. Particuarly for a token refresh mechanism so a refresh token is sent via a cookie when no access token is present and should act as an unauthenticated request and not error that no token is present.

**Comment by rohitnick** [comment]
I am facing the same issue, I think the fix for this should be easy. Request the maintainers to please check out this issue.

**Comment by pranshi06** [comment]
@bitscraps Can you share the exact command used along with the HGE version? Thanks.

**Comment by bitscraps** [comment]
We were using V2.00-alpha.7

As for the exact command I am not sure what you mean. We are using hasura's docker image locally. with the following config:

```
hasura: &hasura
    image: hasura/graphql-engine:v2.0.9
        networks:
      internal_default:
    ports:
      - "3002:8080"
    depends_on:
      - postgres
      - nginx-proxy
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: redacted
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "inherited_roles"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "b2633548447...cae35", "header": { "type": "Cookie", "name": "access_token" } }'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "public"
      ACTION_BASE_URL: http://web:3000/hasura_actions
      GRAPHQL_RUBY_URL: http://web:3000/graphql
```
