### ISSUE TITLE
Remote schema permissions - Unable to display the feature tab

### ISSUE THREAD

**Issue by eapCJ** [hasura/graphql-engine#7273]
Hello,

My console is stuck on `Remote schema permissions are not enabled. To enable remote schema permissions, start the Hasura server with environment variable HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: "true"`.

I've tried to restart the container with the environment variable set to true or add the required flag. In both cases on the start-up log it's shows `"remote_schema_permissions":true`, but somehow when I try to access this feature on the console it's says that I need to activate it. I've also tried to reload the remote schema, nothing.

Any solutions?

**Comment by soorajshankar** [comment]
Hello @eapCJ, Thanks for reporting the issue.

I was trying to replicate this issue but unfortunately I couldn't replicate this. I tried with both v2.0.2 & v2.0.3.

May I know which version of Hasura are you trying with? 
Is it possible to share a similar `docker-compose` file where we could replicate this? 


<details>
<summary>If it helps, here is the `docker-compose.yaml` that I used to test</summary>
<p>

```yaml
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.3
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: "true"
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```
</p>
</details>
