### ISSUE TITLE
Anomal metadata for remote_schema.yaml

### ISSUE THREAD

**Issue by deathemperor** [hasura/graphql-engine#7282]
Metadata is generated normally like this

```yml
- name: DERIVED_REMOTE_SCHEMAS
  definition:
    url_from_env: BERRY_DERIVED_REMOTE_SCHEMAS
    timeout_seconds: 30
    headers:
    - name: x-admin-secret
      value_from_env: ADMIN_SECRET
    forward_client_headers: true
  comment: ""
  permissions:
  - role: MedicalProviderEmployee
    definition:
      schema: |-
        schema  { query: Query }
        type Query { search_certificates(search_by: search_by_enum! , policy_number: String , insured_person_name: String , insured_person_paper_id: String , insured_certificate_code: String , insured_person_phone: String ): search_certificates_output derived_insured_certificates_by_pk(insured_certificate_id: ID! ): derived_insured_certificates }
        type search_certificates_output { success: Boolean! message: String insured_certificates: [derived_insured_certificates] }
        type derived_insured_certificates { certificate_code: String created_at: String deleted_at: String dued_at: String email: String insured_certificate_id: String insured_person_id: String insured_person: derived_insured_persons is_voluntary: Boolean issued_at: String parent_insured_certificate_id: String plan_id: String policy_id: String policy: derived_policy salary: String updated_at: String }
        type derived_insured_persons { created_at: String deleted_at: String dob: String email: String gender: Int insured_certificates: [derived_insured_certificates] insured_number: String insured_person_id: String name: String notes: String paper_expired_at: String paper_id: String paper_issued_at: String paper_issued_place: String phone: String updated_at: String user_id: String }
        type derived_policy { broker_id: String corporate_id: String created_at: String deleted_at: String dued_at: String insured_certificates: [derived_insured_certificates] insured_person: derived_insured_persons insured_person_id: String insurer_id: String issued_at: String policy_id: String policy_number: String remark_copay: String tpa_id: String types: String updated_at: String }
        enum search_by_enum {policy_number_and_insured_person_name  insured_person_paper_id_and_insured_certificate_code  insured_person_paper_id_and_insured_person_phone  }
```

I have no ideas why but now it keeps generating this:

```yml
- name: DERIVED_REMOTE_SCHEMAS
  definition:
    url_from_env: BERRY_DERIVED_REMOTE_SCHEMAS
    timeout_seconds: 30
    headers:
    - name: x-admin-secret
      value_from_env: ADMIN_SECRET
    forward_client_headers: true
  comment: ""
  permissions:
  - role: MedicalProviderEmployee
    definition:
      schema: "schema  { query: Query }\n\ntype Query { derived_insured_certificates_by_pk(insured_certificate_id:
        ID!): derived_insured_certificates\n  search_certificates(search_by: search_by_enum!,
        policy_number: String, insured_person_name: String, insured_person_paper_id:
        String, insured_certificate_code: String, insured_person_phone: String): search_certificates_output\n}\n\ntype
        derived_insured_certificates { certificate_code: String\n  created_at: String\n
        \ deleted_at: String\n  dued_at: String\n  email: String\n  insured_certificate_id:
        String\n  insured_person: derived_insured_persons\n  insured_person_id: String\n
        \ is_voluntary: Boolean\n  issued_at: String\n  parent_insured_certificate_id:
        String\n  plan_id: String\n  policy: derived_policy\n  policy_id: String\n
        \ salary: String\n  updated_at: String\n}\n\ntype derived_insured_persons
        { created_at: String\n  deleted_at: String\n  dob: String\n  email: String\n
        \ gender: Int\n  insured_certificates: [derived_insured_certificates]\n  insured_number:
        String\n  insured_person_id: String\n  name: String\n  notes: String\n  paper_expired_at:
        String\n  paper_id: String\n  paper_issued_at: String\n  paper_issued_place:
        String\n  phone: String\n  updated_at: String\n  user_id: String\n}\n\ntype
        derived_policy { broker_id: String\n  corporate_id: String\n  created_at:
        String\n  deleted_at: String\n  dued_at: String\n  insured_certificates: [derived_insured_certificates]\n
        \ insured_person: derived_insured_persons\n  insured_person_id: String\n  insurer_id:
        String\n  issued_at: String\n  policy_id: String\n  policy_number: String\n
        \ remark_copay: String\n  tpa_id: String\n  types: String\n  updated_at: String\n}\n\ntype
        search_certificates_output { insured_certificates: [derived_insured_certificates]\n
        \ message: String\n  success: Boolean!\n}\n\nenum search_by_enum {insured_person_paper_id_and_insured_certificate_code
        \n  insured_person_paper_id_and_insured_person_phone \n  policy_number_and_insured_person_name
        \n}"
```

Also this weird format

```yml
permissions:
  - role: User
    definition:
      schema: |-
        schema  { query: Query mutation: Mutation }

        type Mutation { changePassword(oldPassword: String!, newPassword: String!): changePasswordOutput
        }

        type Query { _empty_id_: String
          verifyJwt: verifyJwtOutput
        }

        type User { companies: [companiesWithRole]
          email: String
          last_login_at: String
          name: String
          phone: String
          referred_by: String
          source: String
          user_id: String
        }

        type changePasswordOutput { data: dataOutput
          message: String
          success: Boolean!
          token: String
        }

        type companiesWithRole { company_id: String
          role: String
        }

        type dataOutput { access_token: String!
          expires_in: Int!
          token_type: String!
        }

        type verifyJwtOutput { message: String
          success: Boolean!
          user: User
        }
```
