### ISSUE TITLE
constraint name previously working in 1.3.3 no longer works in 2.0.4

### ISSUE THREAD

**Issue by hipitihop** [hasura/graphql-engine#7347]
A working system/schema on Postgres 11.6 + Hasura 1.3.3 is no longer accepted in 2.0.4

We have an existing table with a unique constraint named `unique ratecarduse`. _Note the space in the identifier_

The original metadata in 1.3.3 was as follows.

![image](https://user-images.githubusercontent.com/4626024/128129193-a1f13f72-d53a-41a5-b3dd-682dc4dc8bf9.png)

```yml
- table:
    schema: public
    name: rates_admin_ratecarduse
  object_relationships:
  - name: rates_admin_ratecard
    using:
      foreign_key_constraint_on: ratecard_id
  select_permissions:
  - role: user
    permission:
      columns:
      - id
      - ratecard_id
      - rateset_id
      - station_id
      - status
      - wc
      filter: {}
      allow_aggregations: true
```

However after upgrading to v2.0.4 and config v3, we can no longer add it as a tracked table as the constraint name is rejected as an invalid GraphQL identifier.

![image](https://user-images.githubusercontent.com/4626024/128129301-0142a484-984d-4be5-b840-2672629440d4.png)

If we modify the constraint name replacing the space with an underscore. We can then continue to use it with 2.0.3

It sounds like you may have tightened your validation but I may have missed it in the changelog upgrade notes. Also it is a little odd since Postgres clearly supports it.

Our current workaround is we have renamed the constraint excluding the space.
