### ISSUE TITLE
graphql-codegen with x-hasura-admin-secret

### ISSUE THREAD

**Issue by logemann** [hasura/graphql-engine#7356]
trying to get types generation working with hasura. See this config for graphql-codegen:

```
overwrite: true
schema:
  - https://xxxxxx-yyyy-15.hasura.app/v1/graphql:
      headers:
        x-hasura-admin-secret: MY_ADMIN_SECRET_NOT_DISCLOSED_HERE
generates:
  src/generated/graphql2.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
  graphql.schema2.json:
    plugins:
      - introspection
```

Running this results in:

  ✖ src/generated/graphql2.tsx
    Failed to load schema from https://xxxxxx-yyyy-15.hasura.app/v1/graphql:

    x-hasura-admin-secret/x-hasura-access-key required, but not found

Whats wrong there?
