### ISSUE TITLE
support customising function root field names

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#7405]
Currently we allow [customizing the names of the root fields](https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/custom-field-names.html#expose-table-root-fields-with-a-different-name-in-the-graphql-api) generated for tables. However, we don't have the same for functions. Functions already have a `configuration` section - we can add two top level fields called `custom_name` and `custom_root_fields` as follows:
```yaml
functions:
- function: function_name
  configuration:
    session_argument: ...
    exposed_as: ...
    custom_name: a custom graphql compliant name
    custom_root_fields:
      function: FunctionName
      function_aggregate: SomeOtherName
  permissions: ...
```

Console will require an equivalent of `set_table_customization`, maybe `set_function_configuration` to allow modifying this configuration after a function is tracked.
