### ISSUE TITLE
FATA[0001] version check: failed to get version from server: failed making version api call: Get "http://localhost:8181/v1/version": dial tcp [::1]:8181: connect: connection refused 

### ISSUE THREAD

**Issue by skanel** [hasura/graphql-engine#7463]
here is my docker-compose.yml, I was tried for a few days to find a solution to this, but I can not.

```
version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.7.cli-migrations-v3
    env_file:
      - ./hasura-server/.env
    volumes:
      - ./hasura-server/migrations:/hasura-migrations
      - ./hasura-server/metadata:/hasura-metadata
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: xxxxxx

      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS384", "key":"3EK6FD+o0+c7tzBNVfjpMkNDi2yARAAKzQlk8O2IKoxQu4nF7EdAh8s3TwpHwrdWT6R"}'
volumes:
  db_data:
```

when I run `docker-compose up -d ` it works fine. but when  run `cd hasura-server && hasura console` 
i got this error output

`FATA[0001] version check: failed to get version from server: failed making version api call: Get "http://localhost:8080/v1/version": EOF `

anyone please help?
