### ISSUE TITLE
Migrations and metadata tutorial provides incorrect information

### ISSUE THREAD

**Issue by Gozala** [hasura/graphql-engine#7539]
### Version Information

Server Version: v2.0.9
CLI Version (for CLI related issue): v2.0.8

### Environment

Running hasura in a docker container based as per documentation
https://hasura.io/docs/latest/graphql/core/getting-started/docker-simple.html#step-1-get-the-docker-compose-file

### What is the expected behaviour?

I expect that following steps in migration tutorial will provision a database with a desired schema and graphql-engine. 

### Keywords

- database default is not connected to hasura
- database not found
- 
### How to reproduce the issue?

1. Start hasura in docker container as per https://hasura.io/docs/latest/graphql/core/getting-started/docker-simple.html#step-1-get-the-docker-compose-file

2. Run following set of commands

```sh
hasura init hasura
cd hasura
hasura migrate create init --sql-from-file ../database_v2/artifacts/provision.sql --database-name default
#> WARN database default is not connected to hasura  
#> INFO Migrations files created                      name=init version=1631292489116
hasura migrate apply --database-name default
#> FATA[0001] database not found: error determining database kind for default, check if database exists on hasura 
```

### Any possible solutions?

Update documentation so all the steps are included and can be used to get started.

### Can you identify the location in the source code where the problem exists?

I do not know the code base to be able to tell. As far as I can tell problem is that image starts without any database source and all my attempts to identify a way to start image with connected database source have failed. Here is the related issue #7538

### If the bug is confirmed, would you be willing to submit a PR?

At the moment I do not know how to fix this, assuming I do understand how and have necessary skills I would.

**Comment by BenoitRanque** [comment]
This happens because you are trying to create a migration based on the current state of a database that is not yet connected to hasura, or perhaps you connected it under a diferent name? You could solve this by adding the database in the console, which is what the tutorial suggests.

Once the database is added, the connection will be recorded in the metadata. Bringing up the project would then require that this medata be applied before any operations involving the database (eg. migrations or seeds) be performed.

So typically, bringing up a project that is configured with metadata, migrations and seeds looks like this:
```bash
docker compose up -d
hasura metadata apply
hasura migrate apply --database-name default #or omit the flag, and pick from the list
hasura seeds apply --database-name default #or omit the flag, and pick from the list
hasura metadata reload # this is important because the as the metadata was applied before the migrations, metadata and database were inconsistent.
```

Alternatively, you could connect the database automatically as `default` using the environment variable `HASURA_GRAPHQL_DATABASE_URL` like so:
```
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.9
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```
This is legacy behavior from when hasura only supported one database, but is still perfectly fine.
