### ISSUE TITLE
incorrect sql generated for column comparison operators on functions

### ISSUE THREAD

**Issue by 0x777** [hasura/graphql-engine#7617]
Consider this schema:

```sql
create table message (
  id serial primary key,
  context text not null,
  channel_id integer not null,
  user_id integer not null,
  post_date timestamptz not null
);
create table channel_member (
  channel_id integer not null,
  user_id integer not null,
  join_date timestamptz not null
);
create function get_messages()
returns setof message as $$
    select *
    from message
$$ language sql stable;
```

with the following metadata:

```yaml
version: 3
sources:
- kind: postgres
  name: pg
  configuration:
    connection_info:
      database_url:
        from_env: DB_URL
  tables:
  - table:
      name: channel_member
      schema: public
  - table:
      name: message
      schema: public
    array_relationships:
    - name: members
      using:
        manual_configuration:
          column_mapping:
            channel_id: channel_id
          remote_table:
            name: channel_member
            schema: public
    select_permissions:
    - role: user
      permission:
        columns:
        - id
        - context
        - channel_id
        - user_id
        - post_date
        filter:
          members:
            _and:
            - user_id:
                _eq: X-Hasura-User-Id
            - join_date:
                _clt:
                - $
                - post_date
  functions:
  - function:
      name: get_messages
      schema: public
```

(note the `filter` in select permission: `"join_date": {_clt: ["$", "post_date"]}`

Now execute the following GraphQL query with `x-hasura-role: user` and `x-hasura-user-id: 1`:

```graphql
query MyQuery {
  get_messages {
    id
    post_date
  }
}
```

It would fail with the following error:

```
missing FROM-clause entry for table \"message\"
```

The generated SQL does not have the correct qualifier for `post_date` column when translating the expression `"join_date": {_clt: ["$", "post_date"]}`.
