### ISSUE TITLE
Can't add Postgres data source on fresh installation (Docker) - "datasource key not found in body"

### ISSUE THREAD

**Issue by ludwigbacklund** [hasura/graphql-engine#7635]
### Version Information

Server Version: 2.0.9

### Environment

macOS / Docker

### What is the expected behaviour?

It should add my Postgres database as a data source.

### Keywords

"datasource key not found in body"

### What is the current behaviour?

It silently fails to add my data source but checking outgoing network requests show a POST to http://localhost:9693/apis/migrate failing with a 500 status code. The error is:
```
code: "internal_error"
message: "datasource key not found in body"
```

### How to reproduce the issue?

1. `docker-compose up` the following docker-compose setup:
```
version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  graphql-engine:
    image: hasura/graphql-engine:v2.0.9
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
volumes:
  db_data:

```
2. `hasura console`
3. Try to add a Postgres datasource through any of the "via" methods, in this case I was using via environment variable.

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2021-10-02 at 17 51 58" src="https://user-images.githubusercontent.com/13007299/135723831-a76128ef-5357-4f95-8f7a-5812ba671f42.png">
