### ISSUE TITLE
[Hasura v2.0.10.cli-migrations-v3] - Failed to apply metadata: key "sources" not found 

### ISSUE THREAD

**Issue by vctqs1** [hasura/graphql-engine#7852]
I'm using config V3, with auto apply metadata and see this message, but I dont have any where it come

Message error
```
time="2021-11-25T16:06:30Z" level=fatal msg="error applying metadata \n{\n  \"path\": \"$.args.metadata\",\n  \"error\": \"key \\\"sources\\\" not found\",\n  \"code\": \"parse-failed\"\n}"

```

metadata/databases/databases.yaml

```
- name: draft
  kind: postgres
  configuration:
    connection_info:
      database_url:
        from_env: HASURA_GRAPHQL_DATABASE_URL
      isolation_level: read-committed
      pool_settings:
        connection_lifetime: 600
        idle_timeout: 180
        max_connections: 50
        retries: 1
      use_prepared_statements: true
  tables: "!include draft/tables/tables.yaml"

```

![image](https://user-images.githubusercontent.com/30227910/143474873-59703733-948b-4e29-bd5c-3b68757cc3f1.png)

Already take a look at https://github.com/hasura/graphql-engine/issues/6813, but it is different issue
