### ISSUE TITLE
hasura migrate create init --from-server fails on mac

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#7991]
### Version Information

Server Version: 2.1.1
CLI Version (for CLI related issue): 2.1.1

### Environment

OSS
Mac
Note: could not reproduce this issue on windows.

### What is the expected behavior?

Running the following command should be successful.
```
hasura migrate create init --from-server
```
### Keywords

hasura migrate create init from server

### What is the current behaviour?

An error is thrown:
```
FATA[0002] cannot fetch schema dump: [not-found] resource does not exist ($) 
```

### How to reproduce the issue?

1. On Mac OS, install hasura cli 2.1.1
2. init a hasura directory using `hasura init`, cd into the directory
3. Create the following docker-compose.yaml
```yaml
version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data
  hasura:
    depends_on:
      - postgres
    image: hasura/graphql-engine:v2.1.1
    restart: always
    ports:
      - 8080:8080
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://user:password@postgres:5432/data
      DATABASE_URL: postgres://user:password@postgres:5432/data
volumes:
  data:
```
4. Create the following `.env` file
```env
HASURA_GRAPHQL_ENDPOINT=http://localhost:8080
HASURA_GRAPHQL_ADMIN_SECRET=secret
```
5. Run `docker compose up -d`
6. Access the hasura console, and add a data source using the `DATABASE_URL` env var
7. Attempt to run `hasura migrate create init --from-server`
8. You will see an error message instead of creating a migration.

### Any possible solutions?

We were able to use the [pgdump api](https://hasura.io/docs/latest/graphql/core/api-reference/pgdump.html) to make a request and get the result we expected. This result could be used to populate a file. This also seems to suggest the issue lies with the cli.
