### ISSUE TITLE
Not able to access host.docker.internal for remote schema v2.1.1

### ISSUE THREAD

**Issue by AlgyTaylor** [hasura/graphql-engine#8000]
I've been trying to upgrade from Hasura v1.3.3 to v2.1.1, but have hit a problem.  Everything's gone across fine _except_ the remote schema.  If I copy over my (working) settings from v1.3.3:

```
- name: remote-apollo-schema
  definition:
    url_from_env: APOLLO_GRAPHQL_URL
    timeout_seconds: 60
    forward_client_headers: true
```
I get an error

```
Adding remote schema failed
Error in $: key "data" not found
```

I've also tried using a static URL (http://host.docker.internal:4003) and get the same error message when adding through the console.  Adding via a direct update to the metadata results in a metadata consistency error.  The server is running on that port, and if I downgrade to v1.3.3 it works fine.

Christo [KaW] (from Discord general chat) also has come across this same error in both 2.1.1 and 2.0.0-beta.2
