### ISSUE TITLE
Action Transform Issues (Docs/CLI Support/Metadata export)

### ISSUE THREAD

**Issue by ghardin1314** [hasura/graphql-engine#8001]
### Version Information

Server Version:
CLI Version (for CLI related issue): 2.0.4

Image: v2.1.0-beta.2.cli-migrations-v3

### Environment

Docker Container, self hosted

### What is the expected behaviour?

There is currently no documentation for [Action Transform](https://hasura.io/docs/latest/graphql/core/actions/transforms.html) support for CLI, even though it can currently be configured through `actions.yaml`.

Also, once an action transform is configured in the console, running `hasura metadata export` should export the transform information so that it can be instantly configured on a fresh instance.

### Keywords

Action Transforms

### What is the current behaviour?

After creating a new action with a transform in the console and running `hasura metadata export`, the transform information is missing

```
- name: getMetadata
  definition:
    kind: ""
    handler: https://arweave.net
   <----- This is missing ----->
    request_transform:
      method: GET
      url: '{{$base_url}}/{{$body.input.id}}'
  <--------------------------------->
```

### How to reproduce the issue?

1. Create new action with transform configured
2. Run `export metadata`
3. Tear down hasura server and create a fresh install with exported metadata

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/54160127/148453963-450d8b02-0fb9-4a5f-89a1-4e3e7541a113.png)
