### ISSUE TITLE
[docs] Fix nav hierarchy and add more examples of `claims_map` configurations

### ISSUE THREAD

**Issue by coco98** [hasura/graphql-engine#8069]
Claims map is a powerful enough feature to deserve its own section on our docs page. 
In addition we can add a few more examples, especially using literals for the `x-hasura-roles` bit.

For example, here's possibly the most common claims_map configuration I would use while getting started with an out of the box identity provider:

```
claims_map:
  x-hasura-roles: ["user"]
  x-hasura-default-role: "user"
  x-hasura-user-id: {"path": "$.sub"}
```

This reads as:
- Always use the Hasura role user when an API call is made with this JWT
- Grab the user-id session variable from the `sub` field
