### ISSUE TITLE
Upgrade from 2.0.9 -> 2.1.1+ fails to start with /v1alpha1/config

### ISSUE THREAD

**Issue by hipitihop** [hasura/graphql-engine#8276]
### Version Information

Server Version:
image: hasura/graphql-engine:v2.0.9.cli-migrations-v3

### Environment

Local docker-compose on Ubuntu 20.04.x

### What is the expected behavior?

v2.0.9 starts, but 2.1.1 fails to start.

### Keywords

`v1alpha1`

### How to reproduce the issue?

1. Change docker-compose to `image: hasura/graphql-engine:v2.1.1.cli-migrations-v3`
2. `docker-compose pull`
3. `docker-compose up`

### Please provide any traces or logs that could help here.

```
hasura_1       | {"timestamp":"2022-03-04T02:50:16.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-apply","info":"applying migrations from /hasura-migrations"}}
hasura_1       | {"type":"http-log","timestamp":"2022-03-04T02:50:16.959+0000","level":"error","detail":{"operation":{"error":{"path":"$","error":"resource does not exist","code":"not-found"},"request_id":"78eb450e-b0c3-4b4a-800e-6ad65cf8e2e4","response_size":65,"request_mode":"error"},"request_id":"78eb450e-b0c3-4b4a-800e-6ad65cf8e2e4","http_info":{"status":404,"http_version":"HTTP/1.1","url":"/v1alpha1/config","ip":"127.0.0.1","method":"GET","content_encoding":null}}}
hasura_1       | {"level":"info","msg":"getting lists of databases from server ","time":"2022-03-04T02:50:16Z"}
hasura_1       | {"level":"error","msg":"skipping applying migrations on database default, encountered: \nexpected to find a migrations directory for database default in /tmp/hasura-project/migrations, but encountered error: stat /tmp/hasura-project/migrations/default: no such file or directory","time":"2022-03-04T02:50:16Z"}
hasura_1       | {"type":"http-log","timestamp":"2022-03-04T02:50:16.959+0000","level":"info","detail":{"operation":{"request_id":"09bcd63e-b106-4c6b-a841-c7438d4c0ff7","response_size":15,"request_mode":"non-graphql"},"request_id":"09bcd63e-b106-4c6b-a841-c7438d4c0ff7","http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/version","ip":"127.0.0.1","method":"GET","content_encoding":null}}}
hasura_1       | {"type":"http-log","timestamp":"2022-03-04T02:50:16.959+0000","level":"info","detail":{"operation":{"request_id":"be2bead2-f317-4016-94d7-4cb9e6bf85fc","response_size":15,"request_mode":"non-graphql"},"request_id":"be2bead2-f317-4016-94d7-4cb9e6bf85fc","http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/version","ip":"127.0.0.1","method":"GET","content_encoding":null}}}
hasura_1       | {"type":"http-log","timestamp":"2022-03-04T02:50:16.959+0000","level":"info","detail":{"operation":{"query_execution_time":1.374775e-3,"user_vars":{"x-hasura-role":"admin"},"request_id":"ac52d7ac-9d7c-4c58-a256-b85d7283c4e0","response_size":1852,"request_mode":"non-graphql","request_read_time":6.42e-7},"request_id":"ac52d7ac-9d7c-4c58-a256-b85d7283c4e0","http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/query","ip":"127.0.0.1","method":"POST","content_encoding":"gzip"}}}
hasura_1       | {"type":"http-log","timestamp":"2022-03-04T02:50:16.959+0000","level":"info","detail":{"operation":{"query_execution_time":1.960036e-3,"user_vars":{"x-hasura-role":"admin"},"request_id":"06e2812c-baaa-4b77-8af6-ddd47941b902","response_size":218,"request_mode":"non-graphql","request_read_time":1.143e-6},"request_id":"06e2812c-baaa-4b77-8af6-ddd47941b902","http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/metadata","ip":"127.0.0.1","method":"POST","content_encoding":"gzip"}}}
hasura_1       | {"type":"http-log","timestamp":"2022-03-04T02:50:16.959+0000","level":"info","detail":{"operation":{"query_execution_time":1.444779e-3,"user_vars":{"x-hasura-role":"admin"},"request_id":"58f51288-876b-469b-8fa6-19e284b5d618","response_size":1852,"request_mode":"non-graphql","request_read_time":7.01e-7},"request_id":"58f51288-876b-469b-8fa6-19e284b5d618","http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/metadata","ip":"127.0.0.1","method":"POST","content_encoding":"gzip"}}}
hasura_1       | time="2022-03-04T02:50:18Z" level=fatal msg="operation failed on : default"
hasura_1       | 2022/03/04 02:50:18 Command exited with error: exit status 1
```

### Any possible solutions?

Switching back to v2.0.9 works.

### Can you identify the location in the source code where the problem exists?

NO. It is mentioned in my config.yaml but commenting it out makes no difference:
```
api_paths:
  v1_query: v1/query
  v2_query: v2/query
  v1_metadata: v1/metadata
  graphql: v1/graphql
#  config: v1alpha1/config
  pg_dump: v1alpha1/pg_dump
  version: v1/version
```

### If the bug is confirmed, would you be willing to submit a PR?

Yes

**Comment by arjunyel** [comment]
The error is `expected to find a migrations directory for database default in /tmp/hasura-project/migrations, but encountered error: stat /tmp/hasura-project/migrations/default: no such file or directory","time":"2022-03-04T02:50:16Z"`

To fix, in your hasura directory make sure the folder `migrations/default` exists. Does that fix it?

**Comment by hipitihop** [comment]
@arjunyel  That worked. Note, we also had to add `HASURA_GRAPHQL_MIGRATIONS_DIR` to our docker-compose.
I'm not sure why it worked without this in 2.0.9 Either we are now on latest 2.6.1 thanks.

Our docker-compose.ymp looks like this:
```yml
services:
  hasura:
    # https://docs.hasura.io/1.0/graphql/manual/migrations/auto-apply-migrations.html
    image: hasura/graphql-engine:v2.6.1.cli-migrations-v3
    volumes:
      - ./hasura:/hasura-migrations
      - ./s/dockerize:/usr/bin/dockerize
    ports:
      - "${HASURA_PORT:-8080}:8080"
    entrypoint: dockerize -wait tcp://${POSTGRES_HOST}:5432 -timeout 30s "docker-entrypoint.sh" graphql-engine serve
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${POSTGRES_CONNECTION}
      HASURA_GRAPHQL_METADATA_DIR: /hasura-migrations/metadata
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations/migrations
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE}
      HASURA_GRAPHQL_ACCESS_KEY: our-secret-key
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "SecretJWTKey"}'
    init: true
```

Appreciate your feedback
