### ISSUE TITLE
fatal error: runtime: out of memory (GHC bug)

### ISSUE THREAD

**Issue by zabaat** [hasura/graphql-engine#8332]
### Version Information

Server Version: 2.0.9 & 2.2.2

### Environment

AWS Elasticbeanstalk
t3.xlarge EC2
Ubuntu 20.04 
Docker 20.10.17

### What is the expected behavior?

Normal operation :) 

### Keywords

hasura, GHC crash, fatal out of memory, sadness

### What is the current behaviour?

During normal production workloads hasura crashes with error.
This is despite there being plenty of resources available on that ec2

### How to reproduce the issue?
:(
Currently unknown how to reproduce, would be helpful if there were better debugging commands to replay queries before crash? I will look this up.

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/3325067/158645629-62401a80-da5a-4c69-a386-2d925cff7967.png)
![image](https://user-images.githubusercontent.com/3325067/158645887-b5cd0e63-f7eb-45cb-aec7-6f5e6cd3c8c7.png)

### If the bug is confirmed, would you be willing to submit a PR?

We most likely don't have the relevant experience to create a fix :/

**Comment by zabaat** [comment]
Thanks @jberryman 
To start, here's my docker-compose template with relevant hasura config, I'm not doing any memory or cpu limits.
```
    hasura:
        image: $IMAGE_URI_BASE/hasura:latest
        ports:
            - "9000:8080"
        restart: always
        environment:
            - HASURA_FOLDER=/hasura
            - DOCKER_TAG=$DOCKER_TAG
        env_file:
            - .env
        networks:
            - datadog
        volumes:
            - "/efs:/efs"
```
