### ISSUE TITLE
Console Errorring Out When Event and Data Exist / Events not being created in Postgres on metadata apply

### ISSUE THREAD

**Issue by stevenkaspar** [hasura/graphql-engine#8367]
I keep getting the below error when I try to navigate to this URL in my console

VERSION: Server: 2.1.1 and CLI: 2.5.0-beta.1 (was getting on non beta version too)
URL: http://localhost:9695/console/data/postgres/schema/public/tables/thread_messages/browse (I get the same result when going through hasura container image)

```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at oc (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5486981)
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5432151
    at Zo (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5442287)
    at Ql (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5482766)
    at zl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5473739)
    at jl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5473664)
    at kl (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5470514)
    at https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5421486
    at t.unstable_runWithPriority (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5497297)
    at oa (https://graphql-engine-cdn.hasura.io/console/assets/channel/stable/v2.1/vendor.js.gz:1:5421195)
```

![Screen Shot 2022-04-02 at 7 45 16 AM](https://user-images.githubusercontent.com/6884144/161383975-acf0f19c-866f-49c2-9c01-b6995024d885.png)

TABLE METADATA:
```yaml
table:
  name: thread_messages
  schema: public
object_relationships:
- name: thread
  using:
    foreign_key_constraint_on: thread_id
- name: user
  using:
    foreign_key_constraint_on: user_id
event_triggers:
- definition:
    enable_manual: true
    insert:
      columns: "*"
    update:
      columns: "*"
  name: thread_message_insert_update
  retry_conf:
    interval_sec: 10
    num_retries: 5
    timeout_sec: 60
  webhook_from_env: HASURA_HANDLER_EVENTS_URL
```

It only show error after inserting value into table (from Hasura console)

![Screen Shot 2022-04-02 at 7 47 29 AM](https://user-images.githubusercontent.com/6884144/161384030-a78d8baf-0ab5-4d40-868e-32025cc9555c.png)

![Screen Shot 2022-04-02 at 7 49 01 AM](https://user-images.githubusercontent.com/6884144/161384075-d082f203-88f5-47fc-a5ab-42a9cd0afc9b.png)

It does have the event and this is the first time I've used those so I'm going to try removing the event and then removing date fields and see what causes the issue

---

**UPDATE**

Removing the event causes it to work and adding the event back immediately returns the error

Heading to the event docs to see if I'm missing something
