### ISSUE TITLE
Cannot have more than one Root Field Namespace

### ISSUE THREAD

**Issue by Hongbo-Miao** [hasura/graphql-engine#8438]
### Version Information

Server Version: graphql-engine:v2.5.0.cli-migrations-v3

### What is the expected behaviour?

I have two remote schemas. I try to set Root Field Namespace for both of them.

### Keywords

Root Field Namespace

### What is the current behaviour?

I can set first Root Field Namespace for first remote schema successfully.

However, when I set for second remote schema, it failed with error

> Found conflicting definitions for "Query". The definition at "query_root.hm_graphql_server" differs from the the definition at "query_root.hm_dgraph".

### Screenshots or Screencast

![iShot2022-04-26_02 20 52](https://user-images.githubusercontent.com/3375461/165268764-7609217a-658d-45ca-9366-46758c77ef0a.jpg)

**Comment by Hongbo-Miao** [comment]
I tried to manually add two `root_fields_namespace` in the remote_schemas.yaml file.

```
- name: hm-dgraph-schema
  definition:
    url: http://dgraph-dgraph-alpha.hm-dgraph:8080/graphql
    timeout_seconds: 60
    customization:
      root_fields_namespace: hm_graphql_server
    forward_client_headers: true
  comment: ""
- name: hm-graphql-server-schema
  definition:
    url: http://graphql-server-service.hm:31800/graphql
    timeout_seconds: 60
    customization:
      root_fields_namespace: hm_graphql_server
    forward_client_headers: true
  comment: ""
```

The server will crash. So seems right now Hasura does not support adding namespaces for more than one remote schemas.
