### ISSUE TITLE
[MSSQL] Adding relationship between two tables in different schemas fail

### ISSUE THREAD

**Issue by AndrewCraswell** [hasura/graphql-engine#8511]
### Version Information

Server Version: `v2.6.2-cloud.1`
Database: `MSSQL`

### Environment
Cloud

### What is the expected behaviour?

Clicking "Track" on a detected relationship between two tables in different schemas should not throw errors 

### What is the current behaviour?

I have two tables that each sit in a different schema. One table is in the default `dbo` schema, while the second table is in the `assessments` schema. Hasura is correctly detecting the relationship between the tables since there is a primary/foreign key constraint configured.

![image](https://user-images.githubusercontent.com/1908292/169726220-be22afd9-d6f5-4999-9695-2bff06e0ce0d.png)

I'm presented with an option to "Add" the relationship, but when clicking, I get an error that the table in `dbo` schema could not be found, although the error message makes it clear that it's attempting to locate the table in the wrong schema.

![image](https://user-images.githubusercontent.com/1908292/169726261-5023ff7d-11c3-419c-9580-8f7daedfdcea.png)

### How to reproduce the issue?

1. Create two tables each in a different schema.
2. Configure a primary/foreign key between the tables
3. Use Hasura Cloud to track the relationship between the two tables

### Any possible solutions?

I am using a workaround in the Hasura Cloud UI where I manually configure the relationship, since this allows me to choose the correct schema.

**Comment by prajzwol7** [comment]
@AndrewCraswell this issue must have been solved, I tried the same , its correctly identifying relationship and is creating relationship between two tables in two different schemas.

**Comment by rijx** [comment]
I have the same problem. I was going to file a new issue but after some digging I found this one. Here's my issue:

### Version Information

Server Version: v2.12.0
CLI Version (for CLI related issue):

### Environment

OSS, local Docker container, MS SQL 2017 running in Docker.

### What is the current behaviour?

An error appears saying "Inconsistent object: table "Schema1.Table2" is not tracked".

Raw response:

```json
{
  "code": "invalid-configuration",
  "error": "Inconsistent object: table \"Schema1.Table2\" is not tracked",
  "internal": [
    {
      "definition": {
        "comment": null,
        "name": "Table2",
        "source": "test",
        "table": { "name": "Table1", "schema": "Schema1" },
        "using": { "foreign_key_constraint_on": "UserId" }
      },
      "name": "object_relation Table2 in table Schema1.Table1 in source test",
      "reason": "Inconsistent object: table \"Schema1.Table2\" is not tracked",
      "type": "object_relation"
    }
  ],
  "path": "$.args[0].args"
}
```

### What is the expected behaviour?

The relationship is added. Furthermore the wrong schema is assumed in the error message, likely relating to the underlying issue. The schema of the table we're adding the relationship to is combined with the target table which won't work.

### How to reproduce the issue?

Docker compose:

```yaml
version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5440:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MSSQL_PASSWORD:-Password1}
    ports:
      - "1633:1433"
    volumes:
      - mssql_data_2017:/var/opt/mssql
  graphql-engine:
    image: hasura/graphql-engine:v2.12.0
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
      - "mssql"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      MSSQL_DATABASE_URL: Driver={ODBC Driver 17 for SQL Server};Server=tcp:mssql,1433;Database=test;Uid=sa;Pwd=Password1;
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
volumes:
  pg_data:
  mssql_data_2017:
```

Prepare a MS SQL database using the following query:

```sql
CREATE SCHEMA [Schema1]
GO
CREATE SCHEMA [Schema2]
GO

CREATE TABLE [Schema1].[Table1](
	[Id] [uniqueidentifier] NOT NULL,
	[UserId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Token] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [Schema2].[Table2](
	[UserId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Token] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [Schema1].[Table1]  WITH CHECK ADD  CONSTRAINT [Table1 <-> Table2] FOREIGN KEY([UserId])
REFERENCES [Schema2].[Table2] ([UserId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [Schema1].[Table1] CHECK CONSTRAINT [Table1 <-> Table2]
GO
```

Then call the API:

```bash
curl 'http://localhost:8080/v1/metadata' \
  -H 'content-type: application/json' \
  --data-raw '{"type":"bulk","source":"test","resource_version":32,"args":[{"type":"mssql_create_object_relationship","args":{"name":"Table2","table":{"name":"Table1","schema":"Schema1"},"using":{"foreign_key_constraint_on":"UserId"},"source":"test"}}]}'
```

### Screenshots or Screencast

N/A

### Please provide any traces or logs that could help here.

N/A

### Any possible solutions?

Make sure the relationship's tables can be from two separate schemas.

### Can you identify the location in the source code where the problem exists?

No.

### If the bug is confirmed, would you be willing to submit a PR?

Not a Rust dev, but I can test the PR and do some code review.

### Keywords
