### ISSUE TITLE
HASURA_GRAPHQL_DATABASE_URL no effect

### ISSUE THREAD

**Issue by rongcuid** [hasura/graphql-engine#8535]
### Version Information

Server Version: 2.7.0

### Environment

Docker compose

### What is the expected behaviour?

The following `docker-compose.yml` should give a running instance with `default` database connection, but it does not.

```yaml
version: '3.6'
services:
  postgres:
    image: postgres:14
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.7.0.cli-migrations-v3
    # volumes:
    # - ./hasura/migrations:/hasura-migrations
    # - ./hasura/metadata:/hasura-metadata
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      # PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres 
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:

```

### Keywords

* HASURA_GRAPHQL_DATABASE_URL
* PG_DATABASE_URL
* Configuration
