### ISSUE TITLE
cli-migrations-v3 Image fails on startup with key "tables" not found path `$.args.metadata`

### ISSUE THREAD

**Issue by switchnollie** [hasura/graphql-engine#8538]
I am trying to run Hasura in a Docker container on AWS Elastic Beanstalk using the cli-migrations-v3 Image to auto-apply metadata (I manage migrations with another tool).

I followed the steps from https://hasura.io/docs/latest/graphql/core/migrations/advanced/auto-apply-migrations/ and got the error `failed waiting for 9691` which is also described here: https://github.com/hasura/graphql-engine/issues/5172

Setting `HASURA_GRAPHQL_CLI_ENVIRONMENT=default` now leads to another error:

```
graphql-engine_1  | time="2022-05-30T14:35:52Z" level=fatal msg="error applying metadata \n{\n  \"path\": \"$.args.metadata\",\n  \"error\": \"key \\\"tables\\\" not found\",\n  \"code\": \"parse-failed\"\n}"
```

On my local machine everything works just fine, the issue only occurs on AWS.
I tried different versions from 2.6.2 to 2.7.0 and tried different settings for `HASURA_GRAPHQL_DEV_MODE`. I also tried explicitly setting the `HASURA_GRAPHQL_METADATA_DIR` and `HASURA_GRAPHQL_MIGRATIONS_DIR`, without success.

The default images work just fine, only the cli-migrations-v3 images on AWS fail.

My current configuration is as follows:
```
graphql-engine:
    image: hasura/graphql-engine:v2.6.2.cli-migrations-v3
    links:
      - backend
    ports:
      - 8080:8080
    volumes:
      - ../packages/graphql-engine/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: ${DATABASE_URL} # set on Elastic Beanstalk
      PG_DATABASE_URL: ${DATABASE_URL} # set on Elastic Beanstalk
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: ${HASURA_GRAPHQL_DEV_MODE} # set on Elastic Beanstalk
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET} # set on Elastic Beanstalk
      HASURA_GRAPHQL_CLI_ENVIRONMENT: 'default'
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
```

### Version Information

Server Version: v2.6.2
CLI Version (for CLI related issue): specified in container image hasura/graphql-engine:v2.6.2.cli-migrations-v3

### Environment

Docker running on 64bit Amazon Linux 2/3.4.10 (AWS Elastic Beanstalk)

### What is the expected behaviour?

Metadata is applied on container startup.

### Keywords

Metadata import, cli-migrations-v3, AWS Elastic Beanstalk
