### ISSUE TITLE
Being able to join from a database table to an action result

### ISSUE THREAD

**Issue by gstewart-anduin** [hasura/graphql-engine#8566]
Currently, we can only link actions to database entities via action relationships. However, this functionality is extremely limited. There is no ability to filter out results or iterate. It would also be nice to be able to join from a table to an action result so you can get a superset of the table entity against the action dataset when the action is of type query.

**Comment by m-revetria** [comment]
Hello everybody! I have a related use case, where I need to extend the GraphQL schema by joining with the result of a query action. 

Suppose the following example:

1. There's a `local_table` table stored in my Hasura project's primary database with the `external_table_id` column on it, and exposed via graphql.
2. I've defined a query action to get data from a third party REST API, defined as follows:

   ```yaml
   # in actions.yaml
   actions:
     - name: external_table
       definition:
         kind: ""
         handler: http://thirdpartyserver
       permissions:
         - role: anonymous
       comment: Get external table
   ```
3. The output of this actions is:

   ```graphql
   type ExternalTable {
     id: Int!
     # additional information
   }
   ```

   > The column `external_table_id` works as a FK to the `ExternalTable.id` column

In this scenario, I'd like to run the following query:

   ```graphql
   query MyQuery {
     local_table {
       id
       external_table_id
       external_table {
         id
       }
     }
   }
   ```

Would this be possible to implement?
