### ISSUE TITLE
Missing schema  { query: Query mutation: Mutation } on remote_schemas.yaml hasura-cli export

### ISSUE THREAD

**Issue by lorenzofaresin** [hasura/graphql-engine#8579]
### Version Information

Server Version:
CLI Version (for CLI related issue): >= 2.6.0-beta.1

### Environment

OSS

### What is the expected behaviour?

I expect to get 
```
  permissions:
    - role: example
      definition:
        schema: |-
          schema  { query: Query mutation: Mutation }
```
on remote_schemas.yaml

### Keywords

hasura-cli remote schema permission metadata

### What is the current behaviour?

Missing schema  { query: Query mutation: Mutation } and when a missing role user make a query or mutation we receive a No mutation exists

### How to reproduce the issue?

1. Connect remote schema
2. Save permissions for a role ad save on a remote query
3. Try to make that query with that user role

### Any possible solutions?

Please check differences from 2.5.1 to 2.6.0-beta.1
