### ISSUE TITLE
Console: `ALTER VIEW` does not update data tab properly

### ISSUE THREAD

**Issue by rongcuid** [hasura/graphql-engine#8695]
### Version Information

Server Version: 2.8.0

### Environment

Self hosted, `docker-compose.yaml`:

```
version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.8.4.cli-migrations-v3
    #volumes:
    #  - ./hasura/migrations:/hasura-migrations
    #  - ./hasura/metadata:/hasura-metadata
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```

### What is the expected behaviour?

When view is renamed, the left side of data tab still holds the old view name

### How to reproduce the issue?

1. Create a view using `CREATE VIEW view AS something`
2. Rename the view with `ALTER VIEW view RENAME TO view2`
3. Databases view not updated and still shows `view`. Clicking it shows 404.

### Keywords

ALTER VIEW
