### ISSUE TITLE
apollo federation: reference entities

### ISSUE THREAD

**Issue by mac2000** [hasura/graphql-engine#8725]
Hurray #3064 is here, so giving it a try

Trying to build the following graph:

**Authors Service**

```graphql
type Author key(fields: "id") {
  id: ID!
  name: String!
}
```

**Books Service**

```graphql
type Book key(fields: "id") {
  id: ID!
  name: String!
  # author_id: ID!
  author: Author!
}

extend type Author key(fields: "id") {
  id: ID! @external
  books: [Book!]!
}
```

to do so I have prepared following docker compose:

<details>
<summary>docker-compose.yml</summary>

```yml
version: "3.6"
services:

  pgbooks:
    hostname: pgbooks
    container_name: pgbooks
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres

  pgauthors:
    hostname: pgauthors
    container_name: pgauthors
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      
  books:
    hostname: books
    container_name: books
    image: hasura/graphql-engine:v2.10.0-beta.1
    restart: always
    ports:
    - 8081:8080
    depends_on:
    - pgbooks
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@pgbooks:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgres@pgbooks:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # HASURA_GRAPHQL_ADMIN_SECRET: postgres
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: apollo_federation
  
  authors:
    hostname: authors
    container_name: authors
    image: hasura/graphql-engine:v2.10.0-beta.1
    restart: always
    ports:
    - 8082:8080
    depends_on:
    - pgauthors
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@pgauthors:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgres@pgauthors:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # HASURA_GRAPHQL_ADMIN_SECRET: postgres
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: apollo_federation
```

</details>

After starting it up, connected both databases to corresponding consoles and created basic tables, then untrack them and via API add them back so they are federated, e.g.:

```bash
curl -s -i -X POST http://localhost:8081/v1/metadata -H "Content-Type: application/json" -H "X-Hasura-Admin-Secret: postgres" -d '{
  "type": "pg_track_table",
  "args": {
    "source": "postgres",
    "table": "book",
    "apollo_federation_config": {
      "enable": "v1"
    }
  }
}'
```

Id do see tables in `{ _service { sdl } }` query response and can compose graph from both services with help of apollo federation:

<details>
<summary>gateway.js</summary>

```js
// npm init -y -f
// npm i -S @apollo/gateway apollo-server graphql
// node gateway.js
const { ApolloServer } = require("apollo-server");
const { ApolloGateway, IntrospectAndCompose } = require("@apollo/gateway");

const server = new ApolloServer({
    gateway: new ApolloGateway({
        supergraphSdl: new IntrospectAndCompose({
            subgraphs: [
                { name: "books", url: "http://localhost:8081/v1/graphql" },
                { name: "authors", url: "http://localhost:8082/v1/graphql" }
            ],
            introspectionHeaders: {
                'X-Hasura-Admin-Secret': 'postgres'
            }
        })
    })
})

server.listen({port: 4000}).then(({ url }) => console.log({ url }));
```

</details>

But there is no description of how should we tell hasura that there is some other type which we are extending

My very first attempt was to put it into actions (e.g. it wont resolve anything in either case)

But console does not allowing me to do so, complaining that given type is wrong:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/88868/181464653-d2b06dac-855c-4b7c-abda-352724095135.png">

The second attempt was with remote schema (which probably is not what we want here) but still it does not work, complaining that there are same _entity and _service fields 🤷‍♂️

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/88868/181464987-41afff49-e161-4a82-962f-c58201126b9c.png">

Maybe it is possible by adding computed field to a books table and with help of postgres function do something around this, but I'm not sure what is a right way to create function itself e.g. one from [docs](https://hasura.io/docs/latest/schema/postgres/computed-fields/) expecting to have a table, but in our case there wont be any table and we will just resolve given ids always, e..g something like (pseudo code):

```
create function author(author_row author) {
  return select author.author_id as id
}

create function author_books(author_row author) {
  return select * from books where authori_id = author.author_id
}
```
