### ISSUE TITLE
Support environment variables in migrations

### ISSUE THREAD

**Issue by andoks** [hasura/graphql-engine#8975]
### Is your proposal related to a problem?

I want to add one or more users to postgresql as part of a feature I'm working on. I'am using Hasura for handling migrations. I want to provide the users' password as a environment variable, and in that way configure the password differently between different systems using the same Hasura image (with the migrations scripts included in the hasura image)

### Describe the solution you'd like

1. Create a migration (ie. up.sql) e.g `CREATE USER readOnlyUser WITH ENCRYPTED PASSWORD :readOnlyUserPassword`
2. Add a variable configuration for the migration that inserts the password parameter above from an environment variable. e.g in up_config.yaml:
   ```yaml
   variables:
     readOnlyUserPassword:
       fromEnvVar: READ_ONLY_USER_PASSWORD
     someOtherVariable:
       value: "some value"
   ```

### Describe alternatives you've considered

using psql syntax (\\SET and similar), this seemingly does not work, since the up/down files are .sql, not .psql files

### If the feature is approved, would you be willing to submit a PR?

Unsure, probably no, since I by then might have found a work-around.
