### ISSUE TITLE
Metadata cannot be cleared/replaced once reloaded with missing sources

### ISSUE THREAD

**Issue by jflambert** [hasura/graphql-engine#9297]
### Version Information

Server Version: 2.16.0

### Environment

OSS

### What is the current behaviour?

Metadata can no longer be cleared or replaced with the API after it has been reloaded while sources were missing.

### What is the expected behaviour?

Both the replace and clear metadata API calls should either work no matter what, or have a force flag to override inconsistencies.

### How to reproduce the issue?

1. track two databases (test1 and test2)
2. drop database test2
3. `reload_metadata` complains about inconsistent object test2
4. `replace_metadata` (with only test1) fails with `{"code":"not-exists","error":"source with name \"test2\" does not exist","path":"$.args"}`
5. `clear_metadata` fails with the same error

### Any possible solutions/workarounds you're aware of?

`drop_inconsistent_metadata` will allow `clear_metadata` and `replace_metadata` to continue.

### Proof

`docker-compose.yaml`:

```
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  graphql-engine:
    image: hasura/graphql-engine:v2.16.0
    #image: hasura/graphql-engine:v2.11.2
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_LOG_LEVEL: "warn"
```

`query_hasura.sh`
```
#!/bin/bash

export PGOPTIONS='--client-min-messages=warning'
export PGPASSWORD=password

TEMPLATE="
        {
          \"name\": \"test%u\",
          \"kind\": \"postgres\",
          \"tables\": [],
          \"configuration\": {
            \"connection_info\": {
              \"database_url\": \"postgresql://postgres:password@postgres:5432/test%u\"
            }
          }
        },"

echo "* create and register DBs"
SOURCES=$(printf "$TEMPLATE" 1 1)
dropdb -h 127.0.0.1 -U postgres test1 --force --if-exists
createdb -h 127.0.0.1 -U postgres test1
SOURCES="$SOURCES"$(printf "$TEMPLATE" 2 2)
dropdb -h 127.0.0.1 -U postgres test2 --force --if-exists
createdb -h 127.0.0.1 -U postgres test2

curl -w "\n" --location --request POST 'http://localhost:8080/v1/metadata' \
--header 'Content-Type: application/json' \
--data-binary @- << EOF
{
  "type" : "replace_metadata",
  "version": 2,
  "args": {
    "allow_inconsistent_metadata": true,
    "metadata": {
      "version": 3,
      "sources": [
        ${SOURCES}
        {
          "name": "default",
          "kind": "postgres",
          "tables": [],
          "configuration": {
            "connection_info": {
              "database_url": {
                "from_env": "HASURA_GRAPHQL_DATABASE_URL"
              }
            }
          }
        }
      ]
    }
  }
}
EOF

echo -e "\n* drop test2 DB and reload metadata"
dropdb -h 127.0.0.1 -U postgres test2 --force
curl -w "\n" --location --request POST 'http://localhost:8080/v1/metadata' \
--header 'Content-Type: application/json' \
--data-binary @- << EOF
{
  "type" : "reload_metadata",
  "args": {
      "reload_sources": true
  }
}
EOF

echo -e "\n* register test1 DB only (FAIL)"
SOURCES=$(printf "$TEMPLATE" 1 1)
curl -w "\n" --location --request POST 'http://localhost:8080/v1/metadata' \
--header 'Content-Type: application/json' \
--data-binary @- << EOF
{
  "type" : "replace_metadata",
  "version": 2,
  "args": {
    "allow_inconsistent_metadata": true,
    "metadata": {
      "version": 3,
      "sources": [
        ${SOURCES}
        {
          "name": "default",
          "kind": "postgres",
          "tables": [],
          "configuration": {
            "connection_info": {
              "database_url": {
                "from_env": "HASURA_GRAPHQL_DATABASE_URL"
              }
            }
          }
        }
      ]
    }
  }
}
EOF

echo -e "\n* clear metadata (FAIL)"
curl -w "\n" --location --request POST 'http://localhost:8080/v1/metadata' \
--header 'Content-Type: application/json' \
--data-binary @- << EOF
{
  "type" : "clear_metadata",
  "args": {}
}
EOF

echo -e "\n* drop inconsistent metadata (PASS)"
curl -w "\n" --location --request POST 'http://localhost:8080/v1/metadata' \
--header 'Content-Type: application/json' \
--data-binary @- << EOF
{
  "type" : "drop_inconsistent_metadata",
  "args": {}
}
EOF

echo -e "\n* clear metadata (PASS)"
curl -w "\n" --location --request POST 'http://localhost:8080/v1/metadata' \
--header 'Content-Type: application/json' \
--data-binary @- << EOF
{
  "type" : "clear_metadata",
  "args": {}
}
EOF
```

output with 2.16.0
```
$ ./query_hasura.sh 
* create and register DBs
{"inconsistent_objects":[],"is_consistent":true}

* drop test2 DB and reload metadata
{"inconsistent_objects":[{"definition":"test2","message":"connection to server at \"postgres\" (172.19.0.2), port 5432 failed: FATAL:  database \"test2\" does not exist\n","name":"source test2","reason":"Inconsistent object: connection error","type":"source"}],"is_consistent":false,"message":"success"}

* register test1 DB only (FAIL)
{"code":"not-exists","error":"source with name \"test2\" does not exist","path":"$.args"}

* clear metadata (FAIL)
{"code":"not-exists","error":"source with name \"test2\" does not exist","path":"$.args"}

* drop inconsistent metadata (PASS)
{"message":"success"}

* clear metadata (PASS)
{"message":"success"}
```
