### ISSUE TITLE
Null comments on rest endpoints prevent editing endpoint.

### ISSUE THREAD

**Issue by BenoitRanque** [hasura/graphql-engine#9347]
### Version Information

Server Version: v2.15.2

### Environment

OSS

### What is the current behaviour?

Some older versions of hasura allowed null values for comment on rest endpoints.
Here is example metadata:
```yaml
- comment: null
  definition:
    query:
      collection_name: allowed-queries
      query_name: AlbumsByArtist
  methods:
    - GET
  name: AlbumsByArtist
  url: AlbumsByArtist/:ArtistId
```

With this metadata, attempting to edit the endpoint (eg. modify the underlying graphql query) results in some kind of infinite loop, the console stays in a loading state and never confirms the edit went through.

Newer versions of the console will use empty strings instead of null when there is no comment, and are thus not affected by this problem for new endpoints.

### What is the expected behaviour?

It should be possible to edit rest endpoints, even if the comment is null.

### How to reproduce the issue?

1. Create a rest endpoint with a null comment. This may be easiest by creating an endpoint, exporting metadata, editing metadata, and the applying the edited metadata.
2. Attempt to edit the query used by the rest endpoint and save the change.
3. The console enters a loading state and never finishes.

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/25712958/210026545-c6ad8072-db77-45ed-85c9-116f0a873e05.png)

### Any possible solutions/workarounds you're aware of?

Users can edit metadata manually to replace all instances of `comment: null` with `comment: ""` in the `rest_endpoints.yaml` file.
Applying this metadata will resolve the issue.
