### ISSUE TITLE
Hasura console is not able to reach your Hasura GraphQL engine instance

### ISSUE THREAD

**Issue by jasonmccallister** [hasura/graphql-engine#9400]
### Version Information

Server Version: 2.17.0
CLI Version (for CLI related issue): 2.17.0

### Environment

OSS

### What is the current behaviour?

I'm running Hasura in a docker-compose file, when running `hasura console` I am seeing repeated error messages stating:

```
Hasura console is not able to reach your Hasura GraphQL engine instance. Please ensure that your instance is running and the endpoint is configured correctly.
```

I verfied that both the graphql engine and postgres database are running and have had no issues.

Also, This only started after I upgraded to 2.17.0, same setup worked without any errors on < 2.17.0.

### What is the expected behaviour?

No errors should appear in the console.

### How to reproduce the issue?

1. Attaching the docker-compose file here.

```
version: '3.7'
services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 3s
      retries: 10
  graphql-engine:
    image: hasura/graphql-engine:v2.17.0.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_AUTH_HOOK: "http://auth-server:8080/v1/cloud/auth"
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
```
