### ISSUE TITLE
Console auto directs to oauth.lux-dev.hasura.me ? is it Hasura ?

### ISSUE THREAD

**Issue by phamquyhai** [hasura/graphql-engine#9460]
### Version Information

Server Version: v2.19.0
CLI Version (for CLI related issue): v2.19.0

### Environment

OSS in local

### What is the current behaviour?

When I setting env `HASURA_GRAPHQL_ADMIN_SECRET: "admin"`
I go to `http://localhost:8080/console`. my browser auto directs me to 
`http://oauth.lux-dev.hasura.me/oauth2/auth?client_id=undefined&response_type=code&scope=openid%20offline&redirect_uri=http://localhost:8080/console/oauth2/callback&state=f5cc8755-498a-45c0-b9fd-dff457f629d4&code_challenge_method=S256&code_challenge=lOu_YJpmPs6cqKeEZ3HWyLKq2-YVdWwZ7Fek_vxSdo4`
It`s a bug or ... i see `hasura.me` not from hasura

My docker-compose.yaml
```
graphql-engine:
    image: hasura/graphql-engine:v2.19.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: "naming_convention"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256","key":"-----BEGIN RSA PUBLIC KEY-----xxxxx\n"}'
      HASURA_GRAPHQL_ADMIN_SECRET: "admin"
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      
```

### Screenshots or Screencast
<img width="1345" alt="CleanShot 2023-02-23 at 14 43 57@2x" src="https://user-images.githubusercontent.com/1430683/220847133-6102fe79-32eb-4dbd-855d-04b278946c94.png">
