### ISSUE TITLE
CLI segmentation fault when applying CockroachDB migrations

### ISSUE THREAD

**Issue by GreenCappuccino** [hasura/graphql-engine#9498]
### Version Information

Server Version: v2.16.1
CLI Version (for CLI related issue): v2.20.0

### Environment

docker-compose:
```yaml
version: '3.6'
services:
  postgres:
    image: postgres:14
    restart: always
    volumes:
      - '${PWD}/volumes/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword

  ## Hasura is compatible with CockroachDB 22.2 onwards
  cockroach:
    image: cockroachdb/cockroach:v22.2.1
    # starts an _insecure_, single-node CockroachDB intended for non-production uses only
    # follow the CockroachDB Cloud Guide to connect to a production CockroachDB cluster
    command:
      - start-single-node
      - --insecure
      - --accept-sql-without-tls
    ports:
      - '26257:26257'
    environment:
      COCKROACH_USER: 'root'
      COCKROACH_DATABASE: 'torad'
    volumes:
      - '${PWD}/volumes/cockroach:/cockroach/cockroach-data'

  graphql-engine:
    image: hasura/graphql-engine:v2.16.1
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
      - 'cockroach'
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## cockroachdb
      HASURA_GRAPHQL_DB_COCKROACH: postgres://root@cockroach:26257/torad?sslmode=disable
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  postgres-data:
  cockroach-data:
```

### What is the current behaviour?

Trying to perform `hasura migrate apply` results in a segmentation fault.

### What is the expected behaviour?

Migration is performed succesfully.

### How to reproduce the issue?

1. Start with docker-compose
2. `hasura console`
3. Add CockroachDB to databases
4. `hasura migrate create init`
5. Write migrations
6. `hasura migrate apply`

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/28021387/225535806-10434b15-d85c-4e9a-8d60-2cbad4244f81.png)

### Please provide any traces or logs that could help here.

```sh
hasura migrate apply                                                                                                                                                              ⏎
? Select a database to use cockroach
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                               
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x766b81]

goroutine 38 [running]:
github.com/hasura/graphql-engine/cli/v2/migrate/database/hasuradb.(*HasuraDB).Run(0xc0004f2240, 0x47ac620, 0xc00011e160, 0x12085c5, 0x3, 0xc00031a5c0, 0x19, 0xc0002fdcb0, 0xf2c673)
        /workdir/cli/migrate/database/hasuradb/hasuradb.go:270 +0x7a1
github.com/hasura/graphql-engine/cli/v2/migrate.(*Migrate).runMigrations(0xc0000a6ea0, 0xc000114c60, 0xc0004de000, 0x0, 0x0)
        /workdir/cli/migrate/migrate.go:1305 +0x4cc
github.com/hasura/graphql-engine/cli/v2/migrate.(*Migrate).Up(0xc0000a6ea0, 0xc0000a6dd0, 0x12091f2)
        /workdir/cli/migrate/migrate.go:748 +0x4cb
github.com/hasura/graphql-engine/cli/v2/migrate/cmd.UpCmd(0xc0000a6ea0, 0xffffffffffffffff, 0x0, 0x0)
        /workdir/cli/migrate/cmd/commands.go:186 +0x11c
github.com/hasura/graphql-engine/cli/v2/commands.ExecuteMigration(0x1207f6d, 0x2, 0xc0000a6ea0, 0xffffffffffffffff, 0xc000306cf0, 0x9)
        /workdir/cli/commands/migrate.go:97 +0x159
github.com/hasura/graphql-engine/cli/v2/commands.(*MigrateApplyOptions).Exec(0xc0004b6090, 0x0, 0x0)
        /workdir/cli/commands/migrate_apply.go:304 +0x445
github.com/hasura/graphql-engine/cli/v2/commands.(*MigrateApplyOptions).Apply.func3(0xc000046840, 0xc0004b6090, 0xc0004e65c0)
        /workdir/cli/commands/migrate_apply.go:266 +0x98
created by github.com/hasura/graphql-engine/cli/v2/commands.(*MigrateApplyOptions).Apply
        /workdir/cli/commands/migrate_apply.go:259 +0x125
```

### Any possible solutions/workarounds you're aware of?

N/A

### Keywords

CockroachDB, Migrations
