### ISSUE TITLE
HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT issue while running docker compose up

### ISSUE THREAD

**Issue by tashigeekyants** [hasura/graphql-engine#9533]
### Version Information

Server Version: Ubuntu
CLI Version (for CLI related issue):
INFO hasura cli                                    version=v2.19.0
### Environment

I am trying to run docker compose yaml with posgres and graphql-engine in docker. While it was running few day back, I start seeing this error now.
### What is the current behaviour?
trying to run postgres and graphql engine with below config. but getting error
```
#########################
  # POSTGRES #
  #########################
  postgres:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./init-pg.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d ${DB_NAME} -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER}
      interval: 10s
      timeout: 15s
      retries: 5
    networks:
      - ips_verlagg

  #########################
  # HASURA #
  #########################
  graphql-engine:
    image: hasura/graphql-engine:latest.cli-migrations-v3
    ports:
      - '8081:8080'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://graphql-engine:8080/healthz']
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    env_file:
      - .env
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      PG_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
```

### What is the expected behaviour?
while the same code run fine in local docker desktop, but getting HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT in ubuntu server.

### How to reproduce the issue?

1. docker compose up

### Please provide any traces or logs that could help here.

```
 {"timestamp":"2023-03-30T12:53:52.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"failed waiting for 9691, try increasing HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT (default: 30)"}}

```

### Any possible solutions/workarounds you're aware of?

I tried connectin db with below and it is working fine.
```
psql -h <database_host> -p <database_port> -U <database_username> -d <database_name>
```

### Keywords
graphql-engine, hasura, postgres
