### ISSUE TITLE
Integer environment variables for timeouts

### ISSUE THREAD

**Issue by camargo** [hasura/graphql-engine#9630]
### Is your proposal related to a problem?

Currently when trying to use an environment variable for an action `timeout` (or event `timeout_sec`):

```yaml
actions:
  - name: someAction
    definition:
      kind: synchronous
      handler: "http://some_service/someEndpoint"
      timeout: "{{TIMEOUT_ENV_VAR}}"
```

The `TIMEOUT_ENV_VAR` get's interpreted as a string and throws an error.

```txt
time="2023-05-09T19:06:21Z" level=fatal msg="error applying metadata \ncannot build actions from project: error parsing metadata \nobject: actions\nfile: actions.yaml\nerror: error in reading actions.yaml: yaml: unmarshal errors:\n  line 6: cannot unmarshal !!str `HASURA_...` into int"
```

### Describe the solution you'd like

Interpret environment variables for timeouts as integers so configuration is easier.

### Describe alternatives you've considered

Currently we deliver metadata to customers and they have to edit the metadata manually to get around this.
