### ISSUE TITLE
Error fetching JWK: ConnectionFailure Network.Socket.connect: <socket: 57> only at first container start

### ISSUE THREAD

**Issue by bogi158** [hasura/graphql-engine#9659]
### Version Information

Server Version: v2.22.0

### Environment

Docker

### What is the current behaviour?

The first time I start my docker-compose, the docker container of Hasura gets an error and automatically restarts. The error is:

`Error fetching JWK: ConnectionFailure Network.Socket.connect: <socket: 57>: does not exist (Connection refused)`

Seems like Hasura cannot download the JWK configuration from Keycloak. The strange thing is that, after the hasura container restarts automatically, everything works normally. The error appears only at the first startup.
Moreover, the keycloak container is healthy and the JWT url is indeed reachable before Hasura starts up.

The problem is that the first error block the docker compose startup procedure so every container that depends from Hasura will not start, even if Hasura restarts automatically and works correctly.

### What is the expected behaviour?

Hasura container should start normally at first startup

### How to reproduce the issue?

Try to run this docker compose

### Please provide any traces or logs that could help here.

```bash
Executing task: docker logs --tail 1000 -f 026d1e76a3a81cac0b018d55037f94f8a074792e3e69ab94a68bbdf3cc7710de 

{"detail":{"info":{"admin_secret_set":true,"auth_hook":null,"auth_hook_mode":null,"console_assets_dir":null,"console_sentry_dsn":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"enable_allowlist":false,"enable_console":true,"enable_maintenance_mode":false,"enable_metadata_query_logging":false,"enable_telemetry":true,"enabled_apis":["config","pgdump","metadata","graphql"],"enabled_log_types":["webhook-log","http-log","startup","query-log","websocket-log"],"events_fetch_batch_size":100,"experimental_features":[],"graceful_shutdown_timeout":60,"infer_function_permissions":true,"jwt_secret":[{"audience":null,"claims_format":"json","claims_namespace":"https://hasura.io/jwt/claims","header":null,"issuer":null,"jwk_url":"http://keycloak:8080/realms/vc/protocol/openid-connect/certs"}],"live_query_options":{"batch_size":100,"refetch_delay":1},"log_level":"info","port":8080,"remote_schema_permissions":false,"server_host":"HostAny","stringify_numeric_types":false,"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","unauth_role":"guest","use_prepared_statements":true,"v1-boolean-null-collapse":false,"websocket_compression_options":"NoCompression","websocket_connection_init_timeout":"Refined (Seconds {seconds = 3s})","websocket_keep_alive":"KeepAliveDelay {unKeepAliveDelay = Refined (Seconds {seconds = 5s})}"},"kind":"server_configuration"},"level":"info","timestamp":"2023-05-22T12:06:13.105+0000","type":"startup"}
{"detail":{"info":{"database_url":"postgres://postgres:...@postgres:5432/postgres","retries":5},"kind":"postgres_connection"},"level":"info","timestamp":"2023-05-22T12:06:13.105+0000","type":"startup"}
{"detail":{"info":{"message":"source \"default\" is already at the latest catalog version (3).","source":"default"},"kind":"source_catalog_migrate"},"level":"info","timestamp":"2023-05-22T12:06:13.105+0000","type":"startup"}
{"detail":{"info":"Already at the latest catalog version (47); nothing to do.","kind":"catalog_migrate"},"level":"info","timestamp":"2023-05-22T12:06:13.105+0000","type":"startup"}
Error fetching JWK: ConnectionFailure Network.Socket.connect: <socket: 57>: does not exist (Connection refused)
 *  Terminal will be reused by tasks, press any key to close it. 
```

### Keywords

jwk fetch, socket, error, docker, startup, restart

**Comment by adas98012** [comment]
@bogi158 
Can you attach the docker-compose file (redacting any sensitive info) that you are using ?

**Comment by Enkdress** [comment]
Hi I'm having the same issue here, it was working fine till a pull I did yesterday from a branch in my repo (There are no changes to docker files or infrastructure).

Here is my docker compose file. Any help is welcome, my teammate and I are blocked by this issue

```dockerfile
version: '3.6'
services:
  postgres:
    image: postgres:12
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: xxxx
    ports:
    - "5432"
  backend:
    build:
      context: ./flask
    volumes:
    - ./flask:/app
    environment:
      FLASK_DEBUG: 1
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      PG_DATABASE_URL: postgres://xxxx:xxxx@xxxx:5432/xxxx
    env_file:
    - frontend/.env.local
  graphql:
    image: hasura/graphql-engine:v2.9.0
    ports:
    - "8082:8080"
    depends_on:
    - "postgres"
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://xxxx:xxxx@xxxx:5432/xxxx
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://xxxx:xxxx@xxxx:5432/xxxx
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
    env_file:
    - frontend/.env.local
volumes:
  db_data:
```

This is the error I'm getting
```
{"detail":"Stopping immortal SchemeUpdate.listener thread","level":"info","timestamp":"2023-05-30T17:00:41.915+0000","type":"unstructured"}
Error fetching JWK: InternalException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa)))
```

**Comment by bogi158** [comment]
> @bogi158 Can you attach the docker-compose file (redacting any sensitive info) that you are using ?

Here it is the part of the docker-compose that could help you. I have other services for our backend and frontend but they're dependent from Hasura so they should not be relevant. Also usually they do not correctly startup because Hasura fails the first startup.

```
version: '3.8'

services:

  postgres:
    image: postgres:13
    restart: always
    hostname: postgres
    container_name: postgres
    env_file:
      - .envs/postgres.env
    volumes:
      - hasura_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks: 
      - server

  hasura:
    image: graphql-engine:v2.22.0
    restart: always
    hostname: hasura
    container_name: hasura
    env_file:
      - .envs/hasura.env
    ports:
      - 8080:8080
    healthcheck:        
        test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 5s
    depends_on:
      postgres:
          condition: service_healthy
      keycloak:
          condition: service_healthy
    networks: 
      - server

  ######################
  ###### KEYCLOAK ######
  ######################

  keycloak:
    image: keycloak:21.0.2
    restart: always
    hostname: keycloak
    container_name: keycloak
    working_dir: /opt/keycloak/
    entrypoint: ["sh", "-c", "./bin/kc.sh build && ./bin/kc.sh start-dev --features=scripts"]
    env_file:
      - .envs/keycloak.env
    ports:
      - 28080:8080
    volumes:
      - .config/keycloak/providers/jars:/opt/keycloak/providers:ro
      - .config/keycloak/scripts:/opt/keycloak-scripts:ro
    depends_on:
      keycloak_db:
          condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "bash", "/opt/keycloak-scripts/healthcheck.sh"]
      interval: 2s
      timeout: 5s
      retries: 10
    networks: 
      - server

  keycloak_db:
    image: postgres:13
    restart: always
    hostname: keycloak_db
    container_name: keycloak_db
    env_file:
      - .envs/keycloak_db.env
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "keycloak"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks: 
      - server

  ###################
  ###### PROXY ######
  ###################

  proxy:
    image: nginx:1.23.4-alpine
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.config/nginx:/etc/nginx/conf.d
      - ./.logs/nginx:/var/log/nginx/:rw
      - ./.config/ssl:/etc/ssl
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks: 
      - server

networks:
  server:
    name: server
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1

volumes:
  hasura_data:
    name: "hasura_data"
  keycloak_data:
    name: "keycloak_data"
```
