### ISSUE TITLE
Can't view custom permissions for computed fields, but they are added to the metadata yaml using the [toogle all] button from the UI

### ISSUE THREAD

**Issue by alexander-mart** [hasura/graphql-engine#9752]
### Version Information

Server Version: v2.27.0-ce
CLI Version (for CLI related issue):

### Environment

OSS

### What is the current behaviour?

Can't view custom permissions for computed fields, but they are added to the metadata yaml using the [toogle all] button from the UI of permissions editor (see screenshot):

```yaml
# nhost/metadata/databases/default/tables/public_attempts.yaml

table:
  name: attempts
  schema: public
computed_fields:
  - name: is_answered
    definition:
      function:
        name: attempt_is_answered
        schema: public
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - created_at
        - updated_at
        - task__id
        - user__id
        - answer_boolean
      computed_fields:
        - is_answered # <----- this is select permission for computed field that added by [toogle all] button
      filter:
        _or:
          - user__id:
              _is_null: true
          - user__id:
              _eq: X-Hasura-User-Id
      allow_aggregations: true
```

### What is the expected behaviour?

I can view and toogle custom permissions for computed fields (see same screenshot)

### How to reproduce the issue?

1. Add table with one or more computed field
2. Set select or other permission (may be with custom checks) and click [toogle all] button to allow to select all fields
3. Check diff of matadata and see thats computed field added to permissions sections in yaml but still not visible from ui

### Screenshots or Screencast

Permissions editor:
![image](https://github.com/hasura/graphql-engine/assets/14993551/93fc1d88-09c5-4f6c-9714-a63d62f7f099)

### Please provide any traces or logs that could help here.

—

### Any possible solutions/workarounds you're aware of?

—

### Keywords

permissions, computed fields, console
