### ISSUE TITLE
Data Connectors: Use Environment Variables

### ISSUE THREAD

**Issue by nickthegroot** [hasura/graphql-engine#9777]
### Is your proposal related to a problem?

We use two different Hasura instances depending on whether we're developing locally or deploying publicly, both connected to different databases. We'd like to be able to check in and deploy the same Hasura config, only changing the environment variables depending on the environment.

### Describe the solution you'd like

When defining a data connector (and it's config), allow substituting/specifying environment variables.

For example:

- `backend_configs.yaml`
```yaml
dataconnector:
  weaviate:
      from_env: WEAVIATE_DATABASE_GDC_URL
```

- `databases.yaml`
```yaml
- name: vectors
  ...
  configuration:
    value:
      host:
        from_env: WEAVIATE_DATABASE_URL
```
