### ISSUE TITLE
fixtures / test data

### ISSUE THREAD

**Issue by maxpain** [hasura/graphql-engine#980]
How to manage test data (fixtures) or initial data with Hasura migrations in dev/prod environments?
We use docker-compose for developers environment and Kubernetes for prod.
Putting initial data to migration files (for both dev/prod env.) is OK. But what if we need test data only on dev environment?

It is an example of our `docker-compose.yml` file.

```yaml
version: '3'
services:
  postgres:
    image: postgres:11.0-alpine
    ports:
    - "5432:5432"
    logging:
      driver: none

  hasura:
    image: "hasura/graphql-engine:v1.0.0-alpha28.cli-migrations"
    ports:
    - "9000:8080"
    # logging:
    #   driver: none
    volumes:
      - ../backend/hasura/migrations:/hasura-migrations
    depends_on:
    - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
    command:
      - graphql-engine
      - serve
      - --enable-console
```

Question number two:
In case using above docker-compose config, Hasura is not creating migration files on edit schema in a console. How to fix it?

**Comment by shahidhk** [comment]
@Maxpain177 in the first case, you're saying that you need some extra migrations (which may contain fixtures) to be applied on `dev` environment, right? This would require separating migration files for different environments. 

Thoughts @coco98 @0x777 @arvi3411301?

We already have a discussion going on at #326 which could address this issue.

On the second point, the console will only create migration files when it is served by the CLI (using `hasura console` command). You can run the console with the docker image using `hasura-cli` binary embedded in it.

**Comment by Maxpain177** [comment]
> @Maxpain177 in the first case, you're saying that you need some extra migrations (which may contain fixtures) to be applied on `dev` environment, right? This would require separating migration files for different environments.

Yes



> On the second point, the console will only create migration files when it is served by the CLI (using `hasura console` command). You can run the console with the docker image using `hasura-cli` binary embedded in it.

I need to run two Hasura containers to make migrations generation work:
```yaml
  hasura:
    image: "hasura/graphql-engine:v1.0.0-alpha28.cli-migrations"
    restart: always
    logging:
      driver: none
    ports:
    - "9000:8080"
    volumes:
    - ../backend/hasura/migrations:/hasura-migrations
    depends_on:
    - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${POSTGRES_URL}
    command:
      - graphql-engine
      - serve

  hasura_console:
    image: "hasura/graphql-engine:v1.0.0-alpha28.cli-migrations"
    restart: always
    logging:
      driver: none
    ports:
    - "9693:9693"
    - "9695:9695"
    volumes:
    - ../backend/hasura:/hasura
    depends_on:
    - hasura
    working_dir: /hasura
    entrypoint: hasura-cli
    environment:
      - HOST_HOSTNAME
    command:
    - console
    - --address
    - "0.0.0.0"
    - --endpoint
    - http://$HOST_HOSTNAME:9000
```
