### ISSUE TITLE
Key directive missing in subgraph with apollo federation enabled

### ISSUE THREAD

**Issue by uhcrowdhouse** [hasura/graphql-engine#9881]
### Version Information

Server Version: v2.33.0
CLI Version (for CLI related issue): -

### Environment

OSS

### What is the current behaviour?

In the generated subgraph with apollo federation support, the key directive is missing on the graphql types.
E.g. for table "test" with Apollo Federation mode enable the type is
```
"""
columns and relationships of "test"
"""
type test {
  id: Int!
}
```
However, there is the following entry in the graphql schema indicating that the apollo federation mode has at least some effect:
```
"""A union of all types that use the @key directive"""
union _Entity = test
```

### What is the expected behaviour?

According to the documentation https://hasura.io/docs/latest/data-federation/apollo-federation/ the key directive should be added with the primary key being used in the @key directive's fields argument.
```
type test @key(fields: "id") {
  id: Int!
}
```

### How to reproduce the issue?

1. Follow the quickstart guide https://hasura.io/docs/latest/getting-started/docker-simple/
2. Add apollo federation support in the docker compose by setting HASURA_GRAPHQL_ENABLE_APOLLO_FEDERATION to true.
3. Run hasura server, add a simple table with a primary key column.
4. Under `Data -> [table-name] -> Modify` toggle the switch in the Enable Apollo Federation section.

The full docker compose file used is
```
version: "3.6"
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.33.0
    ports:
      - "8080:8080"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_METADATA_DEFAULTS: '{"backend_configs":{"dataconnector":{"athena":{"uri":"http://data-connector-agent:8081/api/v1/athena"},"mariadb":{"uri":"http://data-connector-agent:8081/api/v1/mariadb"},"mysql8":{"uri":"http://data-connector-agent:8081/api/v1/mysql"},"oracle":{"uri":"http://data-connector-agent:8081/api/v1/oracle"},"snowflake":{"uri":"http://data-connector-agent:8081/api/v1/snowflake"}}}}'
      HASURA_GRAPHQL_ENABLE_APOLLO_FEDERATION: "true"
    depends_on:
      data-connector-agent:
        condition: service_healthy
  data-connector-agent:
    image: hasura/graphql-data-connector:v2.33.0
    restart: always
    ports:
      - 8081:8081
    environment:
      QUARKUS_LOG_LEVEL: ERROR # FATAL, ERROR, WARN, INFO, DEBUG, TRACE
      ## https://quarkus.io/guides/opentelemetry#configuration-reference
      QUARKUS_OPENTELEMETRY_ENABLED: "false"
      ## QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/athena/health"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
volumes:
  db_data:
```

### Screenshots or Screencast

<img width="790" alt="image" src="https://github.com/hasura/graphql-engine/assets/104766446/9108bec4-60d3-48b4-be1d-9c3e66a4d548">

### Any possible solutions/workarounds you're aware of?

Searched through opened and closed issues, but couldn't find any directly related issue.

### Keywords

apollo federation, key directive, subgraph
