### ISSUE TITLE
Select Row Permissions Break Down When Using Multi-Foreign Key Relationships

### ISSUE THREAD

**Issue by joanrodriguez** [hasura/graphql-engine#9955]
### Version Information

Server Version: v2.8.4
CLI Version (for CLI related issue):

### Environment

OSS

### What is the current behaviour?

Permissions break down (console crashes + other unexpected behaviour) when trying to add a filter using an object relationship on more than one column.

### What is the expected behaviour?

Either I shouldn't be able to use the relationship, or if I do, the console shouldn't crash.

### How to reproduce the issue?

1. Create an object relationship from table A to table B using two columns
2. In the select permissions for any role, use a filter on that object relationship
3. That's it, the console will crash

### Screenshots or Screencast

Example offending table:

```yaml
table:
  name: property_transactions
  schema: public
object_relationships:
  - name: buyer_broker
    using:
      foreign_key_constraint_on:
        - buyer_broker_id
        - tenant_id
  - name: lot
    using:
      foreign_key_constraint_on: lot_id
  - name: seller_broker
    using:
      foreign_key_constraint_on: seller_broker_id
select_permissions:
  - role: agent
    permission:
      columns:
        - ...
      filter:
        _and:
          - tenant_id:
              _eq: x-hasura-tenant-id
          - _or:
              - lot:
                  broker:
                    teams_users:
                      team_id:
                        _in: x-hasura-teams-ids
              - seller_broker:  <--- WORKS FINE
                  teams_users:
                    team_id:
                      _in: x-hasura-teams-ids
              - seller_broker: <---- CRASHES
                  teams_users:
                    team_id:
                      _in: x-hasura-teams-ids
```

### Please provide any traces or logs that could help here.

n/a

### Any possible solutions/workarounds you're aware of?

Avoid using multi-column object relationships in your permissions.

In my case, the user_ids are unique accross tenants, so thankfully I was able to fix it by removing tenant_id from the relationship.

### Keywords

n/a
