### ISSUE TITLE
Logical Model can't find fields with uppercase characters in Native Query

### ISSUE THREAD

**Issue by AxelUlmestig** [hasura/graphql-engine#9961]
### Version Information

Server Version: v2.33.0-ce.cli-migrations-v3
CLI Version (for CLI related issue):

### Environment

Ubuntu 22.04.3 LTS

### What is the current behaviour?

I'm trying to set up a Native Query in Hasura. To expose it I need to have a Logical Model to go along with it. I would like the columns in the output to be in camel case but it seems to insist that everything be lower case.

I set up my Logical Model like so:
```yaml
logical_models:
  - name: acquirer_transaction_lm
    fields:
      - name: organizationId
        type:
          nullable: false
          scalar: bigint
    select_permissions:
      - role: organization-finance
        permission:
          filter:
            organizationId:
              _eq: X-Hasura-Organization-Id
          columns:
            - organizationId
```

Along with a Native query like so:

```yaml
native_queries:
  - root_field_name: settlementTransactions
    arguments:
      createdAtAfter:
        description: ""
        nullable: true
        type: timestamptz
      organizationId:
        description: ""
        nullable: false
        type: bigint
    code: |-
      select
        organization_id as organizationId
      from reconciliation.acquirer_transaction
      where
        organization_id = {{organizationId}}
        and created_at > coalesce({{createdAtAfter}}, '1970-01-01'::timestamptz)
      order by created_at asc
      limit 100;
    returns: acquirer_transaction_lm
```

When I try to apply this Hasura complains that the meta data is inconsistent:
```json
{
  "arguments": [],
  "error": {
    "description": null,
    "exec_status": "FatalError",
    "hint": "Perhaps you meant to reference the column \"_cte_logimo_vali_.organizationid\".",
    "message": "column \"organizationId\" does not exist",
    "status_code": "42703"
  },
  "prepared": false,
  "statement": "PREPARE _logimo_vali_(bigint, timestamptz) AS WITH _cte_logimo_vali_ AS (\nselect\n  organization_id as organizationId\nfrom reconciliation.acquirer_transaction\nwhere\n  organization_id = $1\n  and created_at > coalesce($2, '1970-01-01'::timestamptz)\norder by created_at asc\nlimit 100\n\n)\nSELECT \"organizationId\"\nFROM _cte_logimo_vali_"
}
```

Changing `organizationId` to `organizationid` in the Logical Model removes the error despite having `as organizationId` in camel case in the Native Query

### PS

I'm using the following environment variables:
```
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: naming_convention
      HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: graphql-default
```

### What is the expected behaviour?

I expected the fields in the Logical Model to align with the column names in the Native Query.

### How to reproduce the issue?

Put the config above in the databases.yaml file and run `hasura-cli metadata apply`

### Keywords

Native Query, Logical Model, camel case, snake_case
